"""
holiday_enrichment/un_days.py
UN International Days — curated list of ~178 days.
Each entry: (MM-DD, name_en, agency)
Loaded into holiday_un_day table.
"""
from datetime import date

# (date_str MM-DD, name, agency, description)
UN_DAYS = [
    # January
    ("01-01", "Global Family Day", "UN", "Promotes the idea that the family is the basic unit of society"),
    ("01-04", "World Braille Day", "UNESCO", "Raises awareness of the importance of Braille as a means of communication"),
    ("01-24", "International Day of Education", "UN", "Celebrates the role of education for peace and development"),
    ("01-27", "International Day of Commemoration in Memory of the Victims of the Holocaust", "UN", "Honors the memory of Holocaust victims"),
    ("01-30", "World Neglected Tropical Diseases Day", "WHO", "Raises awareness of NTDs"),
    # February
    ("02-04", "World Cancer Day", "WHO", "Raises awareness of cancer and its prevention"),
    ("02-04", "International Day of Human Fraternity", "UN", "Promotes interfaith dialogue"),
    ("02-06", "International Day of Zero Tolerance for Female Genital Mutilation", "UNFPA", "Aims to eliminate FGM"),
    ("02-10", "World Pulses Day", "FAO", "Recognizes the importance of pulses"),
    ("02-11", "International Day of Women and Girls in Science", "UNESCO", "Promotes full and equal access to science for women"),
    ("02-11", "World Day of the Sick", "Vatican", "Recognizes the sick and their caregivers"),
    ("02-13", "World Radio Day", "UNESCO", "Celebrates radio as a medium"),
    ("02-15", "International Childhood Cancer Day", "WHO", "Raises awareness of childhood cancer"),
    ("02-20", "World Day of Social Justice", "UN", "Promotes social justice and equality"),
    ("02-21", "International Mother Language Day", "UNESCO", "Promotes linguistic diversity"),
    # March
    ("03-01", "Zero Discrimination Day", "UNAIDS", "Celebrates the right of everyone to live a full life with dignity"),
    ("03-01", "World Civil Defence Day", "UN", "Recognizes the role of civil defense"),
    ("03-03", "World Wildlife Day", "UN", "Celebrates wildlife"),
    ("03-04", "World Engineering Day", "UNESCO", "Celebrates engineering and engineers"),
    ("03-08", "International Women's Day", "UN", "Celebrates the social, economic, cultural achievements of women"),
    ("03-10", "International Day of Women Judges", "UN", "Recognizes women in the judiciary"),
    ("03-14", "International Day of Mathematics", "UNESCO", "Celebrates mathematics"),
    ("03-15", "International Day to Combat Islamophobia", "UN", "Combat Islamophobia"),
    ("03-15", "World Consumer Rights Day", "UN", "Promotes consumer rights"),
    ("03-20", "International Day of Happiness", "UN", "Recognizes happiness as a fundamental human goal"),
    ("03-20", "World Frog Day", "UN", "Raises awareness of amphibians"),
    ("03-20", "French Language Day", "UN", "Celebrates the French language"),
    ("03-21", "International Day for the Elimination of Racial Discrimination", "UN", "Calls for the elimination of all forms of racial discrimination"),
    ("03-21", "World Poetry Day", "UNESCO", "Recognizes the unique ability of poetry to capture the creative spirit"),
    ("03-21", "International Day of Nowruz", "UN", "Celebrates Nowruz, the Persian new year"),
    ("03-21", "World Down Syndrome Day", "UN", "Raises awareness of Down syndrome"),
    ("03-21", "International Day of Forests", "UN", "Celebrates forests"),
    ("03-22", "World Water Day", "UN", "Raises awareness of the importance of freshwater"),
    ("03-23", "World Meteorological Day", "WMO", "Celebrates meteorology"),
    ("03-24", "World Tuberculosis Day", "WHO", "Raises awareness of tuberculosis"),
    ("03-24", "International Day for the Right to the Truth concerning Gross Human Rights Violations", "UN", "Honors victims of human rights violations"),
    ("03-25", "International Day of Remembrance of the Victims of Slavery and the Transatlantic Slave Trade", "UN", "Honors the victims of slavery"),
    ("03-25", "International Day of Solidarity with Detained and Missing Staff Members", "UN", "Honors UN staff detained or missing"),
    ("03-27", "World Theatre Day", "UNESCO", "Celebrates theatre"),
    # April
    ("04-02", "World Autism Awareness Day", "UN", "Raises awareness of autism"),
    ("04-04", "International Day for Mine Awareness", "UN", "Raises awareness of landmines"),
    ("04-05", "International Day of Conscience", "UN", "Promotes the culture of peace"),
    ("04-06", "International Day of Sport for Development and Peace", "UN", "Celebrates the role of sport in development"),
    ("04-07", "World Health Day", "WHO", "Celebrates the founding of WHO"),
    ("04-07", "Day of Remembrance of the Victims of the Rwanda Genocide", "UN", "Honors the victims of the Rwanda genocide"),
    ("04-12", "International Day of Human Space Flight", "UN", "Commemorates Yuri Gagarin's flight"),
    ("04-14", "World Chagas Disease Day", "WHO", "Raises awareness of Chagas disease"),
    ("04-15", "World Art Day", "UNESCO", "Celebrates fine arts"),
    ("04-17", "World Hemophilia Day", "WHO", "Raises awareness of hemophilia"),
    ("04-20", "Chinese Language Day", "UN", "Celebrates Chinese language and culture"),
    ("04-21", "World Creativity and Innovation Day", "UN", "Raises awareness of the role of creativity"),
    ("04-22", "Earth Day", "UN", "Demonstrates support for environmental protection"),
    ("04-23", "World Book and Copyright Day", "UNESCO", "Celebrates books and authors"),
    ("04-23", "International Girls in ICT Day", "ITU", "Encourages girls to pursue ICT careers"),
    ("04-23", "World Spanish Language Day", "UN", "Celebrates Spanish language"),
    ("04-23", "English Language Day", "UN", "Celebrates English language"),
    ("04-24", "International Day of Multilateralism and Diplomacy for Peace", "UN", "Promotes multilateralism"),
    ("04-25", "International Delegates' Day", "UN", "Honors delegates"),
    ("04-25", "World Malaria Day", "WHO", "Raises awareness of malaria"),
    ("04-26", "World Intellectual Property Day", "WIPO", "Celebrates IP"),
    ("04-26", "International Chernobyl Disaster Remembrance Day", "UN", "Commemorates the Chernobyl disaster"),
    ("04-28", "World Day for Safety and Health at Work", "ILO", "Promotes safe and healthy working environments"),
    ("04-30", "International Jazz Day", "UNESCO", "Raises awareness of jazz"),
    # May
    ("05-01", "International Workers' Day", "UN", "Celebrates workers"),
    ("05-01", "World Tuna Day", "UN", "Raises awareness of tuna conservation"),
    ("05-02", "World Tuna Day", "UN", "Raises awareness of tuna"),  # alternate date
    ("05-03", "World Press Freedom Day", "UNESCO", "Celebrates press freedom"),
    ("05-05", "World Portuguese Language Day", "UN", "Celebrates Portuguese language"),
    ("05-08", "Time of Remembrance and Reconciliation for Those Who Lost Their Lives during the Second World War", "UN", "Honors WWII victims"),
    ("05-08", "World Ovarian Cancer Day", "WHO", "Raises awareness of ovarian cancer"),
    ("05-08", "World Red Cross and Red Crescent Day", "ICRC", "Celebrates the Red Cross movement"),
    ("05-09", "World Migratory Bird Day", "UNEP", "Raises awareness of migratory birds"),
    ("05-10", "International Day of Argania", "UN", "Raises awareness of argan trees"),
    ("05-12", "International Nurses Day", "WHO", "Celebrates nurses"),
    ("05-15", "International Day of Families", "UN", "Celebrates families"),
    ("05-16", "International Day of Living Together in Peace", "UN", "Promotes peace and unity"),
    ("05-16", "International Day of Light", "UNESCO", "Celebrates light"),
    ("05-17", "World Telecommunication and Information Society Day", "ITU", "Raises awareness of ICTs"),
    ("05-20", "World Bee Day", "UN", "Raises awareness of bees"),
    ("05-20", "World Autoimmune Autoinflammatory Arthritis Day", "UN", "Raises awareness"),
    ("05-21", "World Day for Cultural Diversity for Dialogue and Development", "UN", "Celebrates cultural diversity"),
    ("05-21", "International Tea Day", "UN", "Raises awareness of tea production"),
    ("05-22", "International Day for Biological Diversity", "UN", "Raises awareness of biodiversity"),
    ("05-23", "International Day to End Obstetric Fistula", "UNFPA", "Raises awareness of obstetric fistula"),
    ("05-25", "World Football Day", "UN", "Celebrates football"),
    ("05-25", "Africa Day", "UN", "Celebrates African unity"),
    ("05-25", "International Missing Children's Day", "ICMEC", "Raises awareness of missing children"),
    ("05-28", "International Day of Action for Women's Health", "UN", "Advocates for women's health"),
    ("05-29", "International Day of UN Peacekeepers", "UN", "Honors UN peacekeepers"),
    ("05-30", "World Multiple Sclerosis Day", "WHO", "Raises awareness of MS"),
    ("05-31", "World No Tobacco Day", "WHO", "Raises awareness of tobacco risks"),
    # June
    ("06-01", "Global Day of Parents", "UN", "Honors parents"),
    ("06-03", "World Bicycle Day", "UN", "Celebrates bicycles"),
    ("06-04", "International Day of Innocent Children Victims of Aggression", "UN", "Acknowledges the pain suffered by children"),
    ("06-05", "World Environment Day", "UNEP", "Raises awareness of environmental protection"),
    ("06-05", "International Day for the Fight against Illegal, Unreported and Unregulated Fishing", "UN", "Combats illegal fishing"),
    ("06-06", "Day of the Russian Language", "UN", "Celebrates Russian language"),
    ("06-07", "World Food Safety Day", "FAO", "Raises awareness of food safety"),
    ("06-08", "World Oceans Day", "UN", "Celebrates the ocean"),
    ("06-11", "International Day of Play", "UN", "Celebrates play"),
    ("06-12", "World Day Against Child Labour", "ILO", "Raises awareness of child labor"),
    ("06-13", "International Albinism Awareness Day", "UN", "Promotes albinism awareness"),
    ("06-14", "World Blood Donor Day", "WHO", "Thanks blood donors"),
    ("06-15", "World Elder Abuse Awareness Day", "UN", "Raises awareness of elder abuse"),
    ("06-16", "International Day of Family Remittances", "UN", "Recognizes the contribution of migrants"),
    ("06-17", "World Day to Combat Desertification and Drought", "UN", "Raises awareness of desertification"),
    ("06-18", "Sustainable Gastronomy Day", "UN", "Promotes sustainable gastronomy"),
    ("06-19", "International Day for the Elimination of Sexual Violence in Conflict", "UN", "Raises awareness of sexual violence in conflict"),
    ("06-20", "World Refugee Day", "UNHCR", "Honors refugees"),
    ("06-21", "International Day of Yoga", "UN", "Raises awareness of yoga benefits"),
    ("06-21", "International Day of the Celebration of the Solstice", "UN", "Celebrates solstice"),
    ("06-23", "Public Service Day", "UN", "Celebrates public service"),
    ("06-23", "International Widows' Day", "UN", "Raises awareness of widow issues"),
    ("06-25", "Day of the Seafarer", "IMO", "Honors seafarers"),
    ("06-26", "International Day Against Drug Abuse and Illicit Trafficking", "UN", "Expresses determination to strengthen action against drug abuse"),
    ("06-26", "International Day in Support of Victims of Torture", "UN", "Supports torture victims"),
    ("06-27", "Micro-, Small and Medium-sized Enterprises Day", "UN", "Celebrates SMEs"),
    ("06-29", "International Day of the Tropics", "UN", "Raises awareness of tropical regions"),
    ("06-30", "International Asteroid Day", "UN", "Raises awareness of asteroids"),
    ("06-30", "International Day of Parliamentarism", "UN", "Celebrates parliaments"),
    # July
    ("07-02", "World Sports Journalist Day", "UN", "Celebrates sports journalism"),
    ("07-04", "International Day of Cooperatives", "UN", "Celebrates cooperatives"),
    ("07-07", "World Chocolate Day", "UN", "Celebrates chocolate"),
    ("07-11", "World Population Day", "UN", "Raises awareness of population issues"),
    ("07-15", "World Youth Skills Day", "UN", "Celebrates youth skills"),
    ("07-18", "Nelson Mandela International Day", "UN", "Honors Nelson Mandela"),
    ("07-20", "World Chess Day", "UN", "Celebrates chess"),
    ("07-25", "World Drowning Prevention Day", "UN", "Raises awareness of drowning"),
    ("07-28", "World Hepatitis Day", "WHO", "Raises awareness of hepatitis"),
    ("07-30", "World Day against Trafficking in Persons", "UN", "Raises awareness of human trafficking"),
    ("07-30", "International Day of Friendship", "UN", "Celebrates friendship"),
    # August
    ("08-01", "World Lung Cancer Day", "WHO", "Raises awareness of lung cancer"),
    ("08-09", "International Day of the World's Indigenous Peoples", "UN", "Celebrates indigenous peoples"),
    ("08-11", "World Steel Day", "UN", "Recognizes the steel industry"),
    ("08-12", "International Youth Day", "UN", "Draws attention to youth issues"),
    ("08-19", "World Humanitarian Day", "UN", "Honors humanitarian workers"),
    ("08-19", "World Photography Day", "UN", "Celebrates photography"),
    ("08-21", "International Day of Remembrance and Tribute to the Victims of Terrorism", "UN", "Honors victims of terrorism"),
    ("08-22", "International Day Commemorating the Victims of Acts of Violence Based on Religion or Belief", "UN", "Honors victims of religious violence"),
    ("08-23", "International Day for the Remembrance of the Slave Trade and Its Abolition", "UN", "Remembers the slave trade"),
    ("08-29", "International Day against Nuclear Tests", "UN", "Calls for an end to nuclear tests"),
    ("08-30", "International Day of the Victims of Enforced Disappearances", "UN", "Honors victims of enforced disappearances"),
    ("08-31", "International Day for People of African Descent", "UN", "Celebrates people of African descent"),
    ("08-31", "International Overdose Awareness Day", "UN", "Raises awareness of overdose"),
    # September
    ("09-05", "International Day of Charity", "UN", "Recognizes the role of charity"),
    ("09-07", "International Day of Clean Air for Blue Skies", "UN", "Raises awareness of air quality"),
    ("09-08", "International Literacy Day", "UNESCO", "Raises awareness of literacy"),
    ("09-09", "International Day to Protect Education from Attack", "UN", "Protects education from attack"),
    ("09-10", "World Suicide Prevention Day", "WHO", "Raises awareness of suicide prevention"),
    ("09-12", "International Day for South-South Cooperation", "UN", "Promotes South-South cooperation"),
    ("09-15", "International Day of Democracy", "UN", "Promotes democracy"),
    ("09-16", "International Day for the Preservation of the Ozone Layer", "UN", "Preserves the ozone layer"),
    ("09-17", "World Patient Safety Day", "WHO", "Raises awareness of patient safety"),
    ("09-18", "International Equal Pay Day", "UN", "Advocates for equal pay"),
    ("09-21", "International Day of Peace", "UN", "Strengthens the ideals of peace"),
    ("09-23", "International Day of Sign Languages", "UN", "Raises awareness of sign languages"),
    ("09-24", "World Maritime Day", "IMO", "Celebrates maritime industry"),
    ("09-25", "World Pharmacists Day", "WHO", "Celebrates pharmacists"),
    ("09-26", "International Day for the Total Elimination of Nuclear Weapons", "UN", "Calls for nuclear disarmament"),
    ("09-27", "World Tourism Day", "UNWTO", "Raises awareness of tourism"),
    ("09-28", "International Day for Universal Access to Information", "UN", "Promotes access to information"),
    ("09-28", "World Rabies Day", "WHO", "Raises awareness of rabies"),
    ("09-29", "International Day of Awareness of Food Loss and Waste", "UN", "Raises awareness of food loss"),
    ("09-29", "World Heart Day", "WHO", "Raises awareness of heart disease"),
    ("09-30", "International Translation Day", "UN", "Celebrates translators"),
    # October
    ("10-01", "International Day of Older Persons", "UN", "Raises awareness of older persons"),
    ("10-01", "International Music Day", "UNESCO", "Celebrates music"),
    ("10-02", "International Day of Non-Violence", "UN", "Spreads the message of non-violence"),
    ("10-04", "World Animal Welfare Day", "UN", "Raises awareness of animal welfare"),
    ("10-05", "World Teachers' Day", "UNESCO", "Celebrates teachers"),
    ("10-05", "World Habitat Day", "UN", "Reflects on the state of towns and cities"),
    ("10-06", "World Cerebral Palsy Day", "UN", "Raises awareness of cerebral palsy"),
    ("10-07", "World Day for Decent Work", "ILO", "Promotes decent work"),
    ("10-09", "World Post Day", "UPU", "Celebrates the postal service"),
    ("10-10", "World Mental Health Day", "WHO", "Raises awareness of mental health"),
    ("10-10", "World Migratory Bird Day", "UNEP", "Raises awareness of migratory birds"),
    ("10-11", "International Day of the Girl Child", "UN", "Recognizes girls' rights"),
    ("10-12", "World Arthritis Day", "WHO", "Raises awareness of arthritis"),
    ("10-13", "International Day for Disaster Risk Reduction", "UN", "Promotes disaster risk reduction"),
    ("10-14", "World Standards Day", "UN", "Raises awareness of standards"),
    ("10-15", "International Day of Rural Women", "UN", "Recognizes the role of rural women"),
    ("10-16", "World Food Day", "FAO", "Raises awareness of food security"),
    ("10-17", "International Day for the Eradication of Poverty", "UN", "Calls for the eradication of poverty"),
    ("10-24", "United Nations Day", "UN", "Marks the anniversary of the UN Charter"),
    ("10-24", "World Development Information Day", "UN", "Improves dissemination of information"),
    ("10-27", "World Day for Audiovisual Heritage", "UNESCO", "Raises awareness of audiovisual heritage"),
    ("10-29", "World Stroke Day", "WHO", "Raises awareness of stroke"),
    ("10-31", "World Cities Day", "UN", "Promotes urbanization"),
    # November
    ("11-02", "International Day to End Impunity for Crimes against Journalists", "UN", "Ends impunity for crimes against journalists"),
    ("11-05", "World Tsunami Awareness Day", "UN", "Raises awareness of tsunamis"),
    ("11-06", "International Day for Preventing the Exploitation of the Environment in War and Armed Conflict", "UN", "Prevents environmental exploitation"),
    ("11-10", "World Science Day for Peace and Development", "UNESCO", "Raises awareness of science"),
    ("11-14", "World Diabetes Day", "WHO", "Raises awareness of diabetes"),
    ("11-15", "World Day of Remembrance for Road Traffic Victims", "WHO", "Remembers road traffic victims"),
    ("11-16", "International Day for Tolerance", "UN", "Generates public awareness of the dangers of intolerance"),
    ("11-17", "World Prematurity Day", "WHO", "Raises awareness of premature birth"),
    ("11-19", "World Toilet Day", "UN", "Raises awareness of sanitation"),
    ("11-19", "World Philosophy Day", "UNESCO", "Celebrates philosophy"),
    ("11-19", "International Men's Day", "UN", "Celebrates men"),
    ("11-20", "World Children's Day", "UNICEF", "Celebrates children"),
    ("11-20", "Africa Industrialization Day", "UN", "Raises awareness of Africa's industrialization"),
    ("11-21", "World Television Day", "UN", "Recognizes television's role"),
    ("11-21", "World Fisheries Day", "UN", "Celebrates fisheries"),
    ("11-25", "International Day for the Elimination of Violence against Women", "UN", "Eliminates violence against women"),
    ("11-26", "World Sustainable Transport Day", "UN", "Promotes sustainable transport"),
    ("11-29", "International Day of Solidarity with the Palestinian People", "UN", "Supports Palestinian people"),
    ("11-30", "Day of Remembrance for all Victims of Chemical Warfare", "OPCW", "Remembers chemical warfare victims"),
    # December
    ("12-01", "World AIDS Day", "WHO", "Raises awareness of HIV/AIDS"),
    ("12-02", "International Day for the Abolition of Slavery", "UN", "Abolishes slavery"),
    ("12-03", "International Day of Persons with Disabilities", "UN", "Promotes disability rights"),
    ("12-04", "International Day of Banks", "UN", "Recognizes the role of banks"),
    ("12-05", "International Volunteer Day for Economic and Social Development", "UN", "Celebrates volunteers"),
    ("12-05", "World Soil Day", "FAO", "Raises awareness of soil"),
    ("12-07", "International Civil Aviation Day", "ICAO", "Recognizes civil aviation"),
    ("12-09", "International Anti-Corruption Day", "UN", "Raises awareness of corruption"),
    ("12-09", "World Genocide Commemoration Day", "UN", "Commemorates genocide victims"),
    ("12-10", "Human Rights Day", "UN", "Commemorates the Universal Declaration of Human Rights"),
    ("12-11", "International Mountain Day", "UN", "Raises awareness of mountains"),
    ("12-12", "International Day of Neutrality", "UN", "Promotes neutrality"),
    ("12-12", "Universal Health Coverage Day", "WHO", "Promotes universal health coverage"),
    ("12-14", "Monkey Day", "UN", "Celebrates monkeys"),
    ("12-18", "International Migrants Day", "UN", "Protects migrant rights"),
    ("12-18", "Arabic Language Day", "UN", "Celebrates Arabic language"),
    ("12-20", "International Human Solidarity Day", "UN", "Promotes solidarity"),
    ("12-27", "International Day of Epidemic Preparedness", "UN", "Promotes epidemic preparedness"),
]


def get_un_days_for_year(year):
    """Return UN days for a given year as list of dicts with start_date."""
    from datetime import date as _date
    out = []
    for mm_dd, name, agency, desc in UN_DAYS:
        month, day = mm_dd.split("-")
        d = _date(year, int(month), int(day))
        out.append({
            "date": d.isoformat(),
            "name_en": name,
            "agency": agency,
            "description": desc,
        })
    return out
