const FILTERS = [
  ["PUBLIC_NATIONAL", "Federal/National Holidays"],
  ["PUBLIC_COMMON_LOCAL", "Common Local Holidays"],
  ["PUBLIC_LOCAL", "Local Holidays"],
  ["DE_FACTO_HOLIDAY", "De Facto Holidays"],
  ["OPTIONAL_HOLIDAY", "Optional/Restricted Holidays"],
  ["HALF_DAY_HOLIDAY", "Half-Day Holidays"],
  ["SPECIAL_WORKING_DAY", "Special Weekend Working Days"],
  ["FLAG_DAY", "Flag Day(s)"],
  ["BANK_CLOSURE", "Bank and Payment Closures"],
  ["GOVERNMENT_CLOSURE", "Government Office Closures"],
  ["MARKET_CLOSURE", "Financial Market Closures"],
  ["SCHOOL_HOLIDAY", "School Holidays"],
  ["OBS_IMPORTANT", "Important Observances"],
  ["OBS_COMMON", "Common Observances"],
  ["OBS_OTHER", "Other Observances"],
  ["OBS_LOCAL", "Local Observances"],
  ["ELECTION_EVENT", "Elections and Civic Events"],
  ["AWARENESS_PERIOD", "Awareness Days and Weeks"],
  ["FUN_HOLIDAY", "Fun and Trivial Holidays"],
  ["UN_OBSERVANCE", "United Nations Observances"],
  ["WORLD_OBSERVANCE", "Worldwide Observances"],
  ["SEASON", "Seasons"],
  ["CLOCK_CHANGE", "Clock Change Dates"],
  ["SPORTING_EVENT", "Sporting Events"],
  ["CHRISTIAN_MAJOR", "Major Christian"],
  ["CHRISTIAN_MORE", "More Christian"],
  ["JEWISH_MAJOR", "Major Jewish"],
  ["JEWISH_MORE", "More Jewish"],
  ["MUSLIM_MAJOR", "Major Muslim"],
  ["MUSLIM_MORE", "More Muslim"],
  ["HINDU_MAJOR", "Major Hindu"],
  ["HINDU_MORE", "More Hindu"],
  ["ORTHODOX_MAJOR", "Major Orthodox"],
  ["ORTHODOX_MORE", "More Orthodox"],
  ["BUDDHIST", "Buddhist Holidays"],
  ["OTHER_RELIGION", "Other Religious Observances"],
];
