#!/usr/bin/env python3
"""
Generate SQL seed files for regions, subregions, and countries from dr5hn source data.

Output:
  - migrations/102_seed_regions.sql       (6 rows)
  - migrations/103_seed_subregions.sql   (22 rows)
  - migrations/104_seed_countries.sql    (250 rows)

Usage:
  python3 scripts/seed/102_generate_regions_subs_countries.py
"""
import json
import urllib.request
import sys
from pathlib import Path

# UN M49 codes for regions (per UN Statistics Division)
# https://unstats.un.org/unsd/methodology/m49/
UN_M49_REGIONS = {
    1: ('AF', '002'),  # Africa
    2: ('AM', '019'),  # Americas
    3: ('AS', '142'),  # Asia
    4: ('EU', '150'),  # Europe
    5: ('OC', '009'),  # Oceania
    6: ('AN', 'AQ'),  # Polar (Antarctica) — UN M49 doesn't have a code; using AQ (Antarctica ISO 3166-1)
}

# UN M49 codes for sub-regions (per dr5hn's subregion_id)
# Source: UN M49 standard (https://unstats.un.org/unsd/methodology/m49/)
# Map keyed by dr5hn subregion_id. Some are approximate because the
# UN M49 standard is more granular than dr5hn's 22 sub-regions.
# Use NULL when there's no good match (column is nullable).
UN_M49_SUBREGIONS = {
    1:  None,    # Polar (Antarctica) — no UN M49 sub-region code
    2:  '011',   # Western Africa
    3:  '155',   # Western Europe
    4:  '014',   # Eastern Africa
    5:  '015',   # Northern Africa
    6:  '017',   # Middle Africa
    7:  '029',   # Caribbean
    8:  '018',   # Southern Africa
    9:  '013',   # Central America
    10: '143',   # Central Asia
    11: None,    # Sub-region not in standard (dr5hn has it as 'South-Eastern Africa' which is non-standard)
    12: '057',   # Micronesia
    13: '154',   # Northern Europe
    14: '034',   # Southern Asia
    15: '039',   # Southern Europe
    16: '035',   # South-Eastern Asia
    17: '151',   # Eastern Europe
    18: '034',   # Southern Asia (alt dr5hn id; same UN M49 as 14)
    19: '053',   # Australia and New Zealand
    20: '145',   # Western Asia
    21: '021',   # Northern America
    22: '030',   # Eastern Asia
}


def download(url: str, out_path: str) -> None:
    print(f"  Downloading {url}...")
    urllib.request.urlretrieve(url, out_path)
    print(f"  → {out_path}")


def escape_sql(s: str) -> str:
    """Escape a string for SQL."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"


def sql_num(v) -> str:
    """Coerce a numeric value to SQL literal.
    - None → 'NULL'
    - 0   → '0' (preserved; using `or` would turn 0 into 'NULL')
    - 12.5 → '12.5'
    """
    if v is None:
        return 'NULL'
    if isinstance(v, bool):
        return '1' if v else '0'
    return str(v)


def main():
    # Download the source JSON files
    print("=== Downloading dr5hn source data ===")
    download(
        "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/regions.json",
        "/tmp/regions.json"
    )
    download(
        "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/subregions.json",
        "/tmp/subregions.json"
    )
    download(
        "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/countries.json",
        "/tmp/countries.json"
    )

    # Load
    with open('/tmp/regions.json') as f:
        regions = json.load(f)
    with open('/tmp/subregions.json') as f:
        subregions = json.load(f)
    with open('/tmp/countries.json') as f:
        countries = json.load(f)

    # === 102_seed_regions.sql ===
    print(f"\n=== Generating 102_seed_regions.sql ({len(regions)} rows) ===")
    sql = """-- Migration 102: Seed regions (6 rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database/blob/master/json/regions.json
-- Generated by: scripts/seed/102_generate_regions_subs_countries.py

INSERT INTO regions (id, code, name, un_m49_code) VALUES\n"""
    rows = []
    for r in regions:
        code, m49 = UN_M49_REGIONS.get(r['id'], ('XX', '999'))
        rows.append(f"  ({r['id']}, {escape_sql(code)}, {escape_sql(r['name'])}, {escape_sql(m49)})")
    sql += ",\n".join(rows) + ";\n"
    Path('migrations/102_seed_regions.sql').write_text(sql)
    print(f"  → migrations/102_seed_regions.sql")

    # === 103_seed_subregions.sql ===
    print(f"=== Generating 103_seed_subregions.sql ({len(subregions)} rows) ===")
    sql = """-- Migration 103: Seed sub-regions (22 rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database/blob/master/json/subregions.json

INSERT INTO subregions (id, code, name, region_id) VALUES\n"""
    rows = []
    for sr in subregions:
        m49 = UN_M49_SUBREGIONS.get(sr['id'])
        rows.append(f"  ({sr['id']}, {escape_sql(m49)}, {escape_sql(sr['name'])}, {sql_num(sr['region_id'])})")
    sql += ",\n".join(rows) + ";\n"
    Path('migrations/103_seed_subregions.sql').write_text(sql)
    print(f"  → migrations/103_seed_subregions.sql")

    # === 104_seed_countries.sql ===
    print(f"=== Generating 104_seed_countries.sql ({len(countries)} rows) ===")
    # Note: dr5hn has timezone as an object/array; we flatten to comma-separated IANA names
    sql = """-- Migration 104: Seed countries (250 rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database/blob/master/json/countries.json

INSERT INTO countries
  (id, cca2, cca3, ccn3, cioc, name, official_name, capital,
   region_id, subregion_id, currency_code, currency_name, currency_symbol,
   phone_code, latitude, longitude, area_km2, population, tld, nationality)
VALUES\n"""
    rows = []
    for c in countries:
        # Get lat/lng from latlng field (it's [lat, lng] in dr5hn)
        lat, lng = (None, None)
        if c.get('latlng') and len(c['latlng']) == 2:
            lat, lng = c['latlng']

        # dr5hn has 2 territories (BV, HM) with no region_id — they're
        # sub-Antarctic islands that should be in the 'Polar' region (id=6).
        # Fall back to 6 if region_id is None.
        region_id = c.get('region_id') if c.get('region_id') is not None else 6

        # Official name: try to construct from native + name, or use name
        official_name = c.get('native') or c.get('name')

        row = f"""  ({c['id']}, {escape_sql(c.get('iso2'))}, {escape_sql(c.get('iso3'))}, {escape_sql(c.get('numeric_code'))}, NULL, {escape_sql(c.get('name'))}, {escape_sql(official_name)}, {escape_sql(c.get('capital'))},
   {sql_num(region_id)}, {sql_num(c.get('subregion_id'))}, {escape_sql(c.get('currency'))}, {escape_sql(c.get('currency_name'))}, {escape_sql(c.get('currency_symbol'))},
   {escape_sql(c.get('phonecode'))}, {sql_num(lat)}, {sql_num(lng)}, {sql_num(c.get('area_sq_km'))}, {sql_num(c.get('population'))}, {escape_sql(c.get('tld'))}, {escape_sql(c.get('nationality'))})"""
        rows.append(row)
    sql += ",\n".join(rows) + ";\n"
    Path('migrations/104_seed_countries.sql').write_text(sql)
    print(f"  → migrations/104_seed_countries.sql")

    print(f"\n=== Done. Files generated: ===")
    print(f"  migrations/102_seed_regions.sql      ({len(regions)} rows)")
    print(f"  migrations/103_seed_subregions.sql   ({len(subregions)} rows)")
    print(f"  migrations/104_seed_countries.sql    ({len(countries)} rows)")


if __name__ == '__main__':
    main()
