#!/usr/bin/env python3
"""
Generate SQL seed files for regions, subregions, and countries from dr5hn source data.

Output:
  - migrations/102_seed_regions.sql       (6 rows)
  - migrations/103_seed_subregions.sql   (22 rows)
  - migrations/104_seed_countries.sql    (250 rows)

Usage:
  python3 scripts/seed/102_generate_regions_subs_countries.py
"""
import json
import urllib.request
import sys
from pathlib import Path

# UN M49 codes for regions (per UN Statistics Division)
# https://unstats.un.org/unsd/methodology/m49/
UN_M49_REGIONS = {
    1: ('AF', '002'),  # Africa
    2: ('AM', '019'),  # Americas
    3: ('AS', '142'),  # Asia
    4: ('EU', '150'),  # Europe
    5: ('OC', '009'),  # Oceania
    6: ('AN', 'AQ'),  # Polar (Antarctica) — UN M49 doesn't have a code; using AQ (Antarctica ISO 3166-1)
}

# UN M49 codes for sub-regions (per dr5hn's subregion_id)
UN_M49_SUBREGIONS = {
    19: '053',   # Australia and New Zealand
    7:  '029',   # Caribbean
    9:  '013',   # Central America
    10: '143',   # Central Asia
    4:  '014',   # Eastern Africa
    17: '151',   # Eastern Europe
    21: '030',   # Eastern Asia
    18: '034',   # Southern Asia
    14: '034',   # Southern Asia (alt)
    15: '039',   # Southern Europe
    11: '005',   # South-Eastern Africa
    6:  '017',   # Middle Africa
    5:  '015',   # Northern Africa
    21: '021',   # Northern America
    13: '154',   # Northern Europe
    12: '009',   # Micronesia (subregion of Oceania)
    16: '035',   # South-Eastern Asia
    22: '127',   # Central Asia
    8:  '005',   # Western Africa (sometimes '011')
    20: '145',   # Western Asia
    2:  '011',   # Western Africa
    3:  '155',   # Western Europe
    1:  None,    # placeholder for Antarctic (no sub-regions)
}


def download(url: str, out_path: str) -> None:
    print(f"  Downloading {url}...")
    urllib.request.urlretrieve(url, out_path)
    print(f"  → {out_path}")


def escape_sql(s: str) -> str:
    """Escape a string for SQL."""
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"


def main():
    # Download the source JSON files
    print("=== Downloading dr5hn source data ===")
    download(
        "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/regions.json",
        "/tmp/regions.json"
    )
    download(
        "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/subregions.json",
        "/tmp/subregions.json"
    )
    download(
        "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/master/json/countries.json",
        "/tmp/countries.json"
    )

    # Load
    with open('/tmp/regions.json') as f:
        regions = json.load(f)
    with open('/tmp/subregions.json') as f:
        subregions = json.load(f)
    with open('/tmp/countries.json') as f:
        countries = json.load(f)

    # === 102_seed_regions.sql ===
    print(f"\n=== Generating 102_seed_regions.sql ({len(regions)} rows) ===")
    sql = """-- Migration 102: Seed regions (6 rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database/blob/master/json/regions.json
-- Generated by: scripts/seed/102_generate_regions_subs_countries.py

INSERT INTO regions (id, code, name, un_m49_code) VALUES\n"""
    rows = []
    for r in regions:
        code, m49 = UN_M49_REGIONS.get(r['id'], ('XX', '999'))
        rows.append(f"  ({r['id']}, {escape_sql(code)}, {escape_sql(r['name'])}, {escape_sql(m49)})")
    sql += ",\n".join(rows) + ";\n"
    Path('migrations/102_seed_regions.sql').write_text(sql)
    print(f"  → migrations/102_seed_regions.sql")

    # === 103_seed_subregions.sql ===
    print(f"=== Generating 103_seed_subregions.sql ({len(subregions)} rows) ===")
    sql = """-- Migration 103: Seed sub-regions (22 rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database/blob/master/json/subregions.json

INSERT INTO subregions (id, code, name, region_id) VALUES\n"""
    rows = []
    for sr in subregions:
        m49 = UN_M49_SUBREGIONS.get(sr['id'], '999')
        rows.append(f"  ({sr['id']}, {escape_sql(m49)}, {escape_sql(sr['name'])}, {sr['region_id']})")
    sql += ",\n".join(rows) + ";\n"
    Path('migrations/103_seed_subregions.sql').write_text(sql)
    print(f"  → migrations/103_seed_subregions.sql")

    # === 104_seed_countries.sql ===
    print(f"=== Generating 104_seed_countries.sql ({len(countries)} rows) ===")
    # Note: dr5hn has timezone as an object/array; we flatten to comma-separated IANA names
    sql = """-- Migration 104: Seed countries (250 rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database/blob/master/json/countries.json

INSERT INTO countries
  (id, cca2, cca3, ccn3, cioc, name, official_name, capital,
   region_id, subregion_id, currency_code, currency_name, currency_symbol,
   phone_code, latitude, longitude, area_km2, population, tld, nationality)
VALUES\n"""
    rows = []
    for c in countries:
        # Get lat/lng from latlng field (it's [lat, lng] in dr5hn)
        lat, lng = (None, None)
        if c.get('latlng') and len(c['latlng']) == 2:
            lat, lng = c['latlng']

        # Official name: try to construct from native + name, or use name
        official_name = c.get('native') or c.get('name')

        row = f"""  ({c['id']}, {escape_sql(c.get('iso2'))}, {escape_sql(c.get('iso3'))}, {escape_sql(c.get('numeric_code'))}, NULL, {escape_sql(c.get('name'))}, {escape_sql(official_name)}, {escape_sql(c.get('capital'))},
   {c.get('region_id')}, {c.get('subregion_id')}, {escape_sql(c.get('currency'))}, {escape_sql(c.get('currency_name'))}, {escape_sql(c.get('currency_symbol'))},
   {escape_sql(c.get('phonecode'))}, {lat or 'NULL'}, {lng or 'NULL'}, {c.get('area_sq_km') or 'NULL'}, {c.get('population') or 'NULL'}, {escape_sql(c.get('tld'))}, {escape_sql(c.get('nationality'))})"""
        rows.append(row)
    sql += ",\n".join(rows) + ";\n"
    Path('migrations/104_seed_countries.sql').write_text(sql)
    print(f"  → migrations/104_seed_countries.sql")

    print(f"\n=== Done. Files generated: ===")
    print(f"  migrations/102_seed_regions.sql      ({len(regions)} rows)")
    print(f"  migrations/103_seed_subregions.sql   ({len(subregions)} rows)")
    print(f"  migrations/104_seed_countries.sql    ({len(countries)} rows)")


if __name__ == '__main__':
    main()
