#!/usr/bin/env python3
"""
Generate migration 105: seed administrative_regions (5,308 rows) from dr5hn.

Output:
  - migrations/105_seed_admin_regions.sql

The dr5hn `countries+states+cities.json` file has states nested under
each country. We extract them all and emit as INSERT statements.

Usage:
  python3 scripts/seed/105_generate_admin_regions.py
"""
import json
import urllib.request
import sys
from pathlib import Path

DOWNLOAD_URL = (
    "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/"
    "master/json/countries+states+cities.json"
)
TMP_FILE = "/tmp/countries-states-cities.json"
OUTPUT = "migrations/105_seed_admin_regions.sql"


def download():
    print(f"  Downloading {DOWNLOAD_URL}...")
    urllib.request.urlretrieve(DOWNLOAD_URL, TMP_FILE)
    print(f"  → {TMP_FILE}")


def escape_sql(s):
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"


def main():
    # Download
    print("=== Downloading dr5hn source data ===")
    download()

    # Load
    with open(TMP_FILE) as f:
        data = json.load(f)
    print(f"  Countries in file: {len(data)}")

    # Build country map (cca2 -> dr5hn_id) for FK resolution
    country_map = {}
    for c in data:
        cca2 = c.get('iso2')
        if cca2:
            country_map[cca2] = c['id']

    # Extract all states
    all_states = []
    for c in data:
        cca2 = c.get('iso2')
        country_id = c['id']
        for state in c.get('states', []):
            all_states.append({
                'id': state['id'],
                'country_id': country_id,
                'name': state.get('name'),
                'ascii_name': state.get('name'),  # dr5hn doesn't separate
                'code': state.get('state_code'),
                'iso2': state.get('iso2'),  # e.g. 'US-CA'
                'type': state.get('type'),
                'latitude': state.get('latitude'),
                'longitude': state.get('longitude'),
            })

    print(f"  Total states: {len(all_states)}")

    # Determine type/level defaults
    def infer_type(name, code, country_cca2):
        # Simple heuristics — refine if needed
        if country_cca2 in ('US', 'CA', 'AU'):
            if code and len(code) == 2 and code.isupper():
                return 'state', 1
        if country_cca2 in ('GB', 'IE'):
            return 'province', 1
        if country_cca2 in ('IN'):
            return 'state', 1
        if country_cca2 in ('CN', 'RU', 'BR'):
            return 'province', 1
        if country_cca2 in ('MX'):
            return 'state', 1
        return 'region', 1  # default

    # Enrich each state with type/level
    for s in all_states:
        # Find country cca2 from country_id
        cca2 = next((c for c, cid in country_map.items() if cid == s['country_id']), None)
        s['type'], s['level'] = infer_type(s.get('name'), s.get('code'), cca2)

    # Generate SQL
    BATCH = 9  # 9 columns × 9 = 81 vars, under 100

    rows = []
    for s in all_states:
        row = f"""  ({s['id']}, {s['country_id']}, NULL, {escape_sql(s.get('code'))}, {escape_sql(s.get('name'))}, {escape_sql(s.get('ascii_name'))}, {escape_sql(s.get('type'))}, {s.get('level', 1)}, {s.get('latitude') or 'NULL'}, {s.get('longitude') or 'NULL'}, {escape_sql(s.get('iso2'))}, {s.get('population') or 'NULL'}, NULL)"""
        rows.append(row)

    chunks = [rows[i:i+BATCH] for i in range(0, len(rows), BATCH)]

    sql_parts = [f"""-- Migration 105: Seed administrative_regions ({len(all_states)} rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database
-- Generated by: scripts/seed/105_generate_admin_regions.py

INSERT INTO administrative_regions
  (id, country_id, parent_id, code, name, ascii_name, type, level, latitude, longitude, iso2, population, timezone)
VALUES"""]

    for chunk in chunks:
        sql_parts.append(",\n".join(chunk) + ";")

    Path(OUTPUT).write_text("\n\n".join(sql_parts) + "\n")
    print(f"\n  → {OUTPUT} ({len(all_states)} rows in {len(chunks)} batches)")


if __name__ == '__main__':
    main()
