#!/usr/bin/env python3
"""
Generate migration 105: seed administrative_regions (5,308 rows) from dr5hn.

Output:
  - migrations/105_seed_admin_regions.sql

The dr5hn `countries+states+cities.json` file has states nested under
each country. We extract them all and emit as INSERT statements.

Usage:
  python3 scripts/seed/105_generate_admin_regions.py
"""
import json
import urllib.request
import sys
from pathlib import Path

DOWNLOAD_URL = (
    "https://raw.githubusercontent.com/dr5hn/countries-states-cities-database/"
    "master/json/countries+states+cities.json"
)
TMP_FILE = "/tmp/countries-states-cities.json"
OUTPUT = "migrations/105_seed_admin_regions.sql"


def download():
    print(f"  Downloading {DOWNLOAD_URL}...")
    urllib.request.urlretrieve(DOWNLOAD_URL, TMP_FILE)
    print(f"  → {TMP_FILE}")


def escape_sql(s):
    if s is None:
        return 'NULL'
    return "'" + str(s).replace("'", "''") + "'"


def sql_num(v):
    """Coerce numeric value to SQL literal (handles 0 correctly, unlike `or`)."""
    if v is None:
        return 'NULL'
    if isinstance(v, bool):
        return '1' if v else '0'
    return str(v)


def main():
    # Download
    print("=== Downloading dr5hn source data ===")
    download()

    # Load
    with open(TMP_FILE) as f:
        data = json.load(f)
    print(f"  Countries in file: {len(data)}")

    # Build country map (cca2 -> dr5hn_id) for FK resolution
    country_map = {}
    for c in data:
        cca2 = c.get('iso2')
        if cca2:
            country_map[cca2] = c['id']

    # Extract all states
    all_states = []
    for c in data:
        cca2 = c.get('iso2')
        country_id = c['id']
        for state in c.get('states', []):
            all_states.append({
                'id': state['id'],
                'country_id': country_id,
                'name': state.get('name'),
                'ascii_name': state.get('name'),  # dr5hn doesn't separate
                'code': state.get('state_code'),
                'iso2': state.get('iso2'),  # e.g. 'US-CA'
                'type': state.get('type'),
                'latitude': state.get('latitude'),
                'longitude': state.get('longitude'),
            })

    print(f"  Total states: {len(all_states)}")

    # Determine type/level defaults
    def infer_type(name, code, country_cca2):
        # Simple heuristics — refine if needed
        if country_cca2 in ('US', 'CA', 'AU'):
            if code and len(code) == 2 and code.isupper():
                return 'state', 1
        if country_cca2 in ('GB', 'IE'):
            return 'province', 1
        if country_cca2 in ('IN'):
            return 'state', 1
        if country_cca2 in ('CN', 'RU', 'BR'):
            return 'province', 1
        if country_cca2 in ('MX'):
            return 'state', 1
        return 'region', 1  # default

    # Enrich each state with type/level
    for s in all_states:
        # Find country cca2 from country_id
        cca2 = next((c for c, cid in country_map.items() if cid == s['country_id']), None)
        s['type'], s['level'] = infer_type(s.get('name'), s.get('code'), cca2)

    # Generate SQL
    # D1 has TWO limits we need to respect:
    #   1. ~100 vars per prepared statement (BATCH × 12 cols ≤ 100)
    #   2. Total statement size ~1MB
    # So we split into multiple INSERT statements, each with 8 rows.
    BATCH = 8
    CHUNK = 80  # rows per INSERT statement (8 rows per batch × 10 batches = 80 rows, ~12KB per INSERT)

    def row(s):
        return f"  ({s['id']}, {s['country_id']}, NULL, {escape_sql(s.get('code'))}, {escape_sql(s.get('name'))}, {escape_sql(s.get('ascii_name'))}, {escape_sql(s.get('type'))}, {s.get('level', 1)}, {sql_num(s.get('latitude'))}, {sql_num(s.get('longitude'))}, {escape_sql(s.get('iso2'))}, {sql_num(s.get('population'))}, NULL)"

    def make_insert(rows_in_chunk):
        return """INSERT INTO administrative_regions
  (id, country_id, parent_id, code, name, ascii_name, type, level, latitude, longitude, iso2, population, timezone)
VALUES
""" + ",\n".join(rows_in_chunk) + ";\n"

    header = f"""-- Migration 105: Seed administrative_regions ({len(all_states)} rows from dr5hn)
-- Source: https://github.com/dr5hn/countries-states-cities-database
-- Generated by: scripts/seed/105_generate_admin_regions.py
-- Split into {len(all_states) // CHUNK + 1} INSERT statements of {CHUNK} rows each
-- (D1 ~100-var/INSERT and ~1MB/statement limits)

"""

    inserts = []
    for i in range(0, len(all_states), CHUNK):
        chunk = all_states[i:i+CHUNK]
        inserts.append(make_insert([row(s) for s in chunk]))

    sql = header + "\n".join(inserts)
    Path(OUTPUT).write_text(sql)
    n_inserts = len(inserts)
    print(f"\n  → {OUTPUT} ({len(all_states)} rows in {n_inserts} INSERT statements of {CHUNK} rows each)")


if __name__ == '__main__':
    main()
