-- Cities for AD (Andorra): 10 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (1, 'Andorra la Vella', 6, 488, 42.50779000, 1.52109000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:1', 'dr5hn-2026-07-29'),
  (3, 'Canillo', 6, 489, 42.56760000, 1.59756000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:3', 'dr5hn-2026-07-29'),
  (4, 'El Tarter', 6, 489, 42.57952000, 1.65362000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:4', 'dr5hn-2026-07-29'),
  (5, 'Encamp', 6, 487, 42.53474000, 1.58014000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:5', 'dr5hn-2026-07-29'),
  (7, 'Pas de la Casa', 6, 487, 42.54277000, 1.73361000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:7', 'dr5hn-2026-07-29'),
  (10, 'les Escaldes', 6, 492, 42.50729000, 1.53414000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:10', 'dr5hn-2026-07-29'),
  (2, 'Arinsal', 6, 493, 42.57205000, 1.48453000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:2', 'dr5hn-2026-07-29'),
  (9, 'la Massana', 6, 493, 42.54499000, 1.51483000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:9', 'dr5hn-2026-07-29');
  (6, 'Ordino', 6, 491, 42.55623000, 1.53319000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:6', 'dr5hn-2026-07-29'),
  (8, 'Sant Julià de Lòria', 6, 490, 42.46372000, 1.49129000, 'Europe/Andorra', NULL, NULL, 'city', 'dr5hn:8', 'dr5hn-2026-07-29');
