-- Cities for AE (United Arab Emirates): 30 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 4 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (12, 'Abu Dhabi', 231, 3396, 24.41361000, 54.43295000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:12', 'dr5hn-2026-07-29'),
  (16, 'Al Ain City', 231, 3396, 24.19167000, 55.76056000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:16', 'dr5hn-2026-07-29'),
  (19, 'Al Dhafra', 231, 3396, 23.65745000, 53.72225000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:19', 'dr5hn-2026-07-29'),
  (26, 'Bani Yas City', 231, 3396, 24.30978000, 54.62944000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:26', 'dr5hn-2026-07-29'),
  (11, 'Ghayathi', 231, 3396, 23.90453420, 52.58710260, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:11', 'dr5hn-2026-07-29'),
  (34, 'Khalifa City', 231, 3396, 24.42588000, 54.60500000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:34', 'dr5hn-2026-07-29'),
  (17, 'Liwa Oasis', 231, 3396, 22.86972550, 53.24086080, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:17', 'dr5hn-2026-07-29'),
  (41, 'Mussafah', 231, 3396, 24.35893000, 54.48267000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:41', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (42, 'Muzayri‘', 231, 3396, 23.14355000, 53.78810000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:42', 'dr5hn-2026-07-29'),
  (25, 'Ruwais', 231, 3396, 24.11028000, 52.73056000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:25', 'dr5hn-2026-07-29'),
  (49, 'Zayed City', 231, 3396, 23.65416000, 53.70522000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:49', 'dr5hn-2026-07-29'),
  (14, 'Ajman', 231, 3395, 25.40328000, 55.52341000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:14', 'dr5hn-2026-07-29'),
  (37, 'Manama', 231, 3395, 25.32568000, 56.00259000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:37', 'dr5hn-2026-07-29'),
  (38, 'Masfut', 231, 3395, 24.83982000, 56.05158000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:38', 'dr5hn-2026-07-29'),
  (32, 'Dubai', 231, 3391, 25.06570000, 55.17128000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:32', 'dr5hn-2026-07-29'),
  (28, 'Dibba Al Fujairah', 231, 3393, 25.58580000, 56.24792000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:28', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (30, 'Dibba Al-Fujairah', 231, 3393, 25.59246000, 56.26176000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:30', 'dr5hn-2026-07-29'),
  (31, 'Dibba Al-Hisn', 231, 3393, 25.61955000, 56.27291000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:31', 'dr5hn-2026-07-29'),
  (20, 'Fujairah', 231, 3393, 25.11641000, 56.34141000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:20', 'dr5hn-2026-07-29'),
  (43, 'Ras Al Khaimah', 231, 3394, 25.46116000, 56.04058000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:43', 'dr5hn-2026-07-29'),
  (18, 'Al Batayih', 231, 3390, 25.22317000, 55.74272000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:18', 'dr5hn-2026-07-29'),
  (13, 'Al Dhaid', 231, 3390, 25.28812000, 55.88157000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:13', 'dr5hn-2026-07-29'),
  (22, 'Al Hamriyah', 231, 3390, 25.46121000, 55.54813000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:22', 'dr5hn-2026-07-29'),
  (23, 'Al Madam', 231, 3390, 24.95536000, 55.76820000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:23', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (33, 'Kalba', 231, 3390, 24.99816000, 56.27207000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:33', 'dr5hn-2026-07-29'),
  (36, 'Khor Fakkan', 231, 3390, 25.33966000, 56.30280000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:36', 'dr5hn-2026-07-29'),
  (39, 'Milehah', 231, 3390, 25.10097000, 55.91282000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:39', 'dr5hn-2026-07-29'),
  (40, 'Murbaḩ', 231, 3390, 25.27623000, 56.36256000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:40', 'dr5hn-2026-07-29'),
  (46, 'Sharjah', 231, 3390, 25.33737000, 55.41206000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:46', 'dr5hn-2026-07-29'),
  (47, 'Umm AL Quwain', 231, 3392, 25.49326000, 55.73520000, 'Asia/Dubai', NULL, NULL, 'city', 'dr5hn:47', 'dr5hn-2026-07-29');
