-- Cities for AW (Aruba): 12 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 2 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (160400, 'Alto Vista', 13, 5341, 12.57050000, -70.01912000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160400', 'dr5hn-2026-07-29'),
  (160398, 'Moco', 13, 5341, 12.55134000, -70.00843000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160398', 'dr5hn-2026-07-29'),
  (160395, 'Noord', 13, 5341, 12.56596000, -70.03198000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160395', 'dr5hn-2026-07-29'),
  (160396, 'Oranjestad', 13, 5341, 12.52398000, -70.02703000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160396', 'dr5hn-2026-07-29'),
  (160399, 'Palm Beach', 13, 5341, 12.56847000, -70.03887000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160399', 'dr5hn-2026-07-29'),
  (160397, 'Paradera', 13, 5341, 12.53510000, -70.00688000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160397', 'dr5hn-2026-07-29'),
  (160394, 'Pos Chiquito', 13, 5341, 12.46497000, -69.96233000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160394', 'dr5hn-2026-07-29'),
  (160401, 'San Nicolas', 13, 5341, 12.43624000, -69.90713000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160401', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (160404, 'Santa Cruz', 13, 5341, 12.50953000, -69.98094000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160404', 'dr5hn-2026-07-29'),
  (160405, 'Savaneta', 13, 5341, 12.45026000, -69.93811000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160405', 'dr5hn-2026-07-29'),
  (160402, 'Tanki Leendert', 13, 5341, 12.53914000, -70.02004000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160402', 'dr5hn-2026-07-29'),
  (160403, 'Washington', 13, 5341, 12.55837000, -70.03816000, 'America/Aruba', NULL, NULL, 'city', 'dr5hn:160403', 'dr5hn-2026-07-29');
