-- Cities for BD (Bangladesh): 64 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 8 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153876, 'Bagerhat', 19, 5473, 22.34880590, 89.07470250, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153876', 'dr5hn-2026-07-29'),
  (8457, 'Bandarban', 19, 5474, 22.00000000, 92.33333000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8457', 'dr5hn-2026-07-29'),
  (153858, 'Barguna', 19, 5475, 22.17167870, 89.79740240, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153858', 'dr5hn-2026-07-29'),
  (153857, 'Barisal', 19, 5476, 22.42035790, 89.78250340, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153857', 'dr5hn-2026-07-29'),
  (153859, 'Bhola', 19, 5477, 22.32452480, 90.10568470, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153859', 'dr5hn-2026-07-29'),
  (153894, 'Bogra', 19, 5478, 24.82966450, 89.02598570, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153894', 'dr5hn-2026-07-29'),
  (8470, 'Brahmanbaria', 19, 5479, 23.98333000, 91.16667000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8470', 'dr5hn-2026-07-29'),
  (8474, 'Chandpur', 19, 5480, 23.25000000, 90.83333000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8474', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153895, 'Chapai Nawabganj', 19, 5481, 24.59988690, 88.28504660, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153895', 'dr5hn-2026-07-29'),
  (8481, 'Chittagong', 19, 5482, 22.48750000, 91.96333000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8481', 'dr5hn-2026-07-29'),
  (153877, 'Chuadanga', 19, 5483, 23.60352730, 88.48732400, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153877', 'dr5hn-2026-07-29'),
  (8484, 'Cox''s Bazar', 19, 5484, 21.58389000, 92.01528000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8484', 'dr5hn-2026-07-29'),
  (8483, 'Comilla', 19, 5485, 23.44170000, 91.00987000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8483', 'dr5hn-2026-07-29'),
  (153863, 'Dhaka', 19, 5486, 23.78417980, 89.92859830, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153863', 'dr5hn-2026-07-29'),
  (153898, 'Dinajpur', 19, 5487, 25.64261030, 88.18344620, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153898', 'dr5hn-2026-07-29'),
  (153871, 'Faridpur', 19, 5488, 23.45115240, 89.52820380, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153871', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (8492, 'Feni', 19, 5489, 22.96667000, 91.31667000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8492', 'dr5hn-2026-07-29'),
  (153900, 'Gaibandha', 19, 5490, 25.34315570, 89.13978570, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153900', 'dr5hn-2026-07-29'),
  (153864, 'Gazipur', 19, 5491, 24.10914520, 90.09596140, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153864', 'dr5hn-2026-07-29'),
  (153872, 'Gopalganj', 19, 5492, 23.10660120, 89.57802710, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153872', 'dr5hn-2026-07-29'),
  (153906, 'Habiganj', 19, 5493, 24.33481970, 90.74899010, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153906', 'dr5hn-2026-07-29'),
  (153887, 'Jamalpur', 19, 5494, 25.00108250, 89.26050130, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153887', 'dr5hn-2026-07-29'),
  (153878, 'Jessore', 19, 5495, 23.08473560, 88.87480080, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153878', 'dr5hn-2026-07-29'),
  (153860, 'Jhalokati', 19, 5496, 22.56303520, 89.87191590, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153860', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153879, 'Jhenaidah', 19, 5497, 23.49521270, 88.70694930, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153879', 'dr5hn-2026-07-29'),
  (153897, 'Joypurhat', 19, 5498, 25.06567070, 88.76832650, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153897', 'dr5hn-2026-07-29'),
  (8512, 'Khagrachhari', 19, 5499, 23.16667000, 91.90000000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8512', 'dr5hn-2026-07-29'),
  (153880, 'Khulna', 19, 5500, 22.35351390, 88.83407090, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153880', 'dr5hn-2026-07-29'),
  (153865, 'Kishoreganj', 19, 5501, 24.33888030, 90.58499800, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153865', 'dr5hn-2026-07-29'),
  (153899, 'Kurigram', 19, 5502, 25.80827220, 89.00915030, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153899', 'dr5hn-2026-07-29'),
  (153881, 'Kushtia', 19, 5503, 23.94595240, 88.70179290, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153881', 'dr5hn-2026-07-29'),
  (8521, 'Lakshmipur', 19, 5504, 22.91667000, 90.83333000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8521', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153901, 'Lalmonirhat', 19, 5505, 26.12442390, 88.91060900, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153901', 'dr5hn-2026-07-29'),
  (153873, 'Madaripur', 19, 5506, 23.23455490, 89.81089030, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153873', 'dr5hn-2026-07-29'),
  (153882, 'Magura', 19, 5507, 23.46557740, 89.11547300, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153882', 'dr5hn-2026-07-29'),
  (153866, 'Manikganj', 19, 5508, 23.83174080, 89.64097890, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153866', 'dr5hn-2026-07-29'),
  (153883, 'Meherpur', 19, 5509, 23.78972180, 88.39319490, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153883', 'dr5hn-2026-07-29'),
  (153907, 'Moulvibazar', 19, 5510, 24.48617710, 91.28742410, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153907', 'dr5hn-2026-07-29'),
  (153867, 'Munshiganj', 19, 5511, 23.52615230, 90.11590910, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153867', 'dr5hn-2026-07-29'),
  (153886, 'Mymensingh', 19, 5512, 24.72309850, 89.78411730, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153886', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153896, 'Naogaon', 19, 5513, 24.87425080, 88.43751910, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153896', 'dr5hn-2026-07-29'),
  (153884, 'Narail', 19, 5514, 23.13175700, 89.26258440, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153884', 'dr5hn-2026-07-29'),
  (153868, 'Narayanganj', 19, 5515, 23.74880130, 90.25638500, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153868', 'dr5hn-2026-07-29'),
  (153869, 'Narsingdi', 19, 5516, 24.00966000, 90.44480420, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153869', 'dr5hn-2026-07-29'),
  (153890, 'Natore', 19, 5517, 24.38021070, 88.76302520, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153890', 'dr5hn-2026-07-29'),
  (153888, 'Netrokona', 19, 5518, 24.87204810, 90.52293810, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153888', 'dr5hn-2026-07-29'),
  (153902, 'Nilphamari', 19, 5519, 26.02264250, 88.63412710, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153902', 'dr5hn-2026-07-29'),
  (8553, 'Noakhali', 19, 5520, 22.75000000, 91.16667000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8553', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153893, 'Pabna', 19, 5521, 24.08126720, 89.03724420, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153893', 'dr5hn-2026-07-29'),
  (153903, 'Panchagarh', 19, 5522, 26.32094460, 88.54711390, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153903', 'dr5hn-2026-07-29'),
  (153861, 'Patuakhali', 19, 5523, 22.18709170, 89.71647060, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153861', 'dr5hn-2026-07-29'),
  (153862, 'Pirojpur', 19, 5524, 22.50937910, 89.36434220, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153862', 'dr5hn-2026-07-29'),
  (153874, 'Rajbari', 19, 5525, 23.73843000, 89.25547000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153874', 'dr5hn-2026-07-29'),
  (153891, 'Rajshahi', 19, 5526, 24.42073360, 88.29602140, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153891', 'dr5hn-2026-07-29'),
  (8576, 'Rangamati', 19, 5527, 22.63333000, 92.20000000, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:8576', 'dr5hn-2026-07-29'),
  (153904, 'Rangpur', 19, 5528, 25.62390240, 88.90094980, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153904', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153885, 'Satkhira', 19, 5529, 22.29898590, 88.47540870, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153885', 'dr5hn-2026-07-29'),
  (153875, 'Shariatpur', 19, 5530, 23.23124340, 90.08293470, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153875', 'dr5hn-2026-07-29'),
  (153889, 'Sherpur', 19, 5531, 25.09260380, 89.76352070, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153889', 'dr5hn-2026-07-29'),
  (153892, 'Sirajganj', 19, 5532, 24.39876240, 88.87641810, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153892', 'dr5hn-2026-07-29'),
  (153908, 'Sunamganj', 19, 5533, 24.88905540, 91.00248270, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153908', 'dr5hn-2026-07-29'),
  (153909, 'Sylhet', 19, 5534, 24.89189110, 91.73554950, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153909', 'dr5hn-2026-07-29'),
  (153870, 'Tangail', 19, 5535, 24.37630700, 89.35804610, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153870', 'dr5hn-2026-07-29'),
  (153905, 'Thakurgaon', 19, 5536, 25.93648420, 88.03366640, 'Asia/Dhaka', NULL, NULL, 'city', 'dr5hn:153905', 'dr5hn-2026-07-29');
