-- Cities for BL (Saint-Barthelemy): 1 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 1 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161653, 'Gustavia', 189, 5819, 17.89790833, -62.85055556, 'America/St_Barthelemy', NULL, NULL, 'city', 'dr5hn:161653', 'dr5hn-2026-07-29');
