-- Cities for CF (Central African Republic): 42 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 6 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (17296, 'Bamingui', 42, 1259, 7.88897000, 20.04875000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17296', 'dr5hn-2026-07-29'),
  (17329, 'Ndélé', 42, 1259, 8.74287000, 20.89108000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17329', 'dr5hn-2026-07-29'),
  (17298, 'Bangui', 42, 1262, 4.36122000, 18.55496000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17298', 'dr5hn-2026-07-29'),
  (17294, 'Alindao', 42, 1264, 5.02667000, 21.20876000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17294', 'dr5hn-2026-07-29'),
  (17323, 'Kembé', 42, 1264, 4.62275000, 21.88645000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17323', 'dr5hn-2026-07-29'),
  (17327, 'Mobaye', 42, 1264, 4.31902000, 21.17861000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17327', 'dr5hn-2026-07-29'),
  (17331, 'Obo', 42, 1258, 5.39586000, 26.49211000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17331', 'dr5hn-2026-07-29'),
  (17338, 'Zemio', 42, 1258, 5.03144000, 25.13614000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17338', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (17313, 'Bria', 42, 1268, 6.54233000, 21.98633000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17313', 'dr5hn-2026-07-29'),
  (17332, 'Ouadda', 42, 1268, 8.07771000, 22.40075000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17332', 'dr5hn-2026-07-29'),
  (17337, 'Sibut', 42, 1263, 5.71801000, 19.07389000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17337', 'dr5hn-2026-07-29'),
  (17307, 'Boda', 42, 1256, 4.31887000, 17.46953000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17307', 'dr5hn-2026-07-29'),
  (17308, 'Boganangone', 42, 1256, 4.73558000, 17.14047000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17308', 'dr5hn-2026-07-29'),
  (17325, 'Mbaiki', 42, 1256, 3.97145000, 17.93352000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17325', 'dr5hn-2026-07-29'),
  (17328, 'Mongoumba', 42, 1256, 3.64153000, 18.59364000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17328', 'dr5hn-2026-07-29'),
  (17301, 'Berberati', 42, 1257, 4.31211000, 15.88948000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17301', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (17314, 'Carnot', 42, 1257, 4.94273000, 15.87735000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17314', 'dr5hn-2026-07-29'),
  (17317, 'Gamboula', 42, 1257, 4.11775000, 15.13926000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17317', 'dr5hn-2026-07-29'),
  (17297, 'Bangassou', 42, 1266, 4.74132000, 22.81838000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17297', 'dr5hn-2026-07-29'),
  (17316, 'Gambo', 42, 1266, 4.64816000, 22.26331000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17316', 'dr5hn-2026-07-29'),
  (17334, 'Ouango', 42, 1266, 4.31325000, 22.55524000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17334', 'dr5hn-2026-07-29'),
  (17336, 'Rafai', 42, 1266, 5.81012000, 24.20305000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17336', 'dr5hn-2026-07-29'),
  (17321, 'Kaga Bandoro', 42, 1253, 6.98961000, 19.18744000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17321', 'dr5hn-2026-07-29'),
  (17299, 'Baoro', 42, 1260, 5.66667000, 15.96667000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17299', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (17310, 'Bouar', 42, 1260, 5.93404000, 15.59599000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17310', 'dr5hn-2026-07-29'),
  (17303, 'Bimbo', 42, 1255, 4.25671000, 18.41583000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17303', 'dr5hn-2026-07-29'),
  (17305, 'Boali', 42, 1255, 4.80048000, 18.12747000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17305', 'dr5hn-2026-07-29'),
  (17315, 'Damara', 42, 1255, 4.96075000, 18.70350000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17315', 'dr5hn-2026-07-29'),
  (17295, 'Bambari', 42, 1265, 5.76795000, 20.67565000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17295', 'dr5hn-2026-07-29'),
  (17318, 'Grimari', 42, 1265, 5.73549000, 19.91209000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17318', 'dr5hn-2026-07-29'),
  (17319, 'Ippy', 42, 1265, 6.26793000, 21.22468000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17319', 'dr5hn-2026-07-29'),
  (17324, 'Kouango', 42, 1265, 4.99337000, 19.96186000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17324', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (17300, 'Batangafo', 42, 1254, 7.30082000, 18.28330000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17300', 'dr5hn-2026-07-29'),
  (17309, 'Bossangoa', 42, 1254, 6.49263000, 17.45518000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17309', 'dr5hn-2026-07-29'),
  (17311, 'Bouca', 42, 1254, 6.50734000, 18.27670000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17311', 'dr5hn-2026-07-29'),
  (17320, 'Kabo', 42, 1254, 7.69937000, 18.62903000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17320', 'dr5hn-2026-07-29'),
  (17306, 'Bocaranga', 42, 1267, 6.76546000, 15.77873000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17306', 'dr5hn-2026-07-29'),
  (17312, 'Bozoum', 42, 1267, 6.31933000, 16.37992000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17312', 'dr5hn-2026-07-29'),
  (17335, 'Paoua', 42, 1267, 7.24269000, 16.44059000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17335', 'dr5hn-2026-07-29'),
  (17330, 'Nola', 42, 1252, 3.52494000, 16.04583000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17330', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (17304, 'Birao', 42, 1261, 10.28488000, 22.78818000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17304', 'dr5hn-2026-07-29'),
  (17333, 'Ouanda-Djallé', 42, 1261, 9.05877000, 22.42741000, 'Africa/Bangui', NULL, NULL, 'city', 'dr5hn:17333', 'dr5hn-2026-07-29');
