-- Cities for DJ (Djibouti): 12 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (30561, 'Ali Sabieh', 60, 2933, 11.15583000, 42.71250000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30561', 'dr5hn-2026-07-29'),
  (30567, 'Goubétto', 60, 2933, 11.42389000, 43.00028000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30567', 'dr5hn-2026-07-29'),
  (30569, 'Holhol', 60, 2933, 11.31028000, 42.92944000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30569', 'dr5hn-2026-07-29'),
  (30563, 'Arta', 60, 2932, 11.52639000, 42.85194000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30563', 'dr5hn-2026-07-29'),
  (30564, 'Dikhil', 60, 2930, 11.10454000, 42.36971000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30564', 'dr5hn-2026-07-29'),
  (30568, 'Gâlâfi', 60, 2930, 11.71583000, 41.83611000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30568', 'dr5hn-2026-07-29'),
  (30565, 'Djibouti', 60, 2929, 11.58901000, 43.14503000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30565', 'dr5hn-2026-07-29'),
  (30570, 'Loyada', 60, 2929, 11.46111000, 43.25278000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30570', 'dr5hn-2026-07-29');
  (30562, 'Alaïli Ḏaḏḏa‘', 60, 2928, 12.42167000, 42.89556000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30562', 'dr5hn-2026-07-29'),
  (30571, 'Obock', 60, 2928, 11.96693000, 43.28835000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30571', 'dr5hn-2026-07-29'),
  (30566, 'Dorra', 60, 2931, 12.15028000, 42.47624000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30566', 'dr5hn-2026-07-29'),
  (30572, 'Tadjourah', 60, 2931, 11.78778000, 42.88222000, 'Africa/Djibouti', NULL, NULL, 'city', 'dr5hn:30572', 'dr5hn-2026-07-29');
