-- Cities for EC (Ecuador): 114 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 15 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31493, 'Cantón San Fernando', 64, 2923, -3.13349000, -79.26893000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31493', 'dr5hn-2026-07-29'),
  (31501, 'Cuenca', 64, 2923, -2.90055000, -79.00453000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31501', 'dr5hn-2026-07-29'),
  (31507, 'Gualaceo', 64, 2923, -2.89264000, -78.77814000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31507', 'dr5hn-2026-07-29'),
  (31519, 'La Unión', 64, 2923, -2.85000000, -78.78333000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31519', 'dr5hn-2026-07-29'),
  (31521, 'Llacao', 64, 2923, -2.86667000, -78.88333000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31521', 'dr5hn-2026-07-29'),
  (31535, 'Nulti', 64, 2923, -2.91667000, -78.85000000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31535', 'dr5hn-2026-07-29'),
  (31510, 'Guaranda', 64, 2920, -1.59263000, -79.00098000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31510', 'dr5hn-2026-07-29'),
  (31569, 'San Miguel', 64, 2920, -1.70884000, -79.04311000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31569', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31484, 'Azogues', 64, 2917, -2.73969000, -78.84860000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31484', 'dr5hn-2026-07-29'),
  (31496, 'Cañar', 64, 2917, -2.56062000, -78.93940000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31496', 'dr5hn-2026-07-29'),
  (31518, 'La Troncal', 64, 2917, -2.42355000, -79.33977000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31518', 'dr5hn-2026-07-29'),
  (31503, 'El Ángel', 64, 2915, 0.62279000, -77.94003000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31503', 'dr5hn-2026-07-29'),
  (31567, 'San Gabriel', 64, 2915, 0.59318000, -77.83078000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31567', 'dr5hn-2026-07-29'),
  (31583, 'Tulcán', 64, 2915, 0.81187000, -77.71727000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31583', 'dr5hn-2026-07-29'),
  (31479, 'Alausí', 64, 2925, -2.20329000, -78.84714000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31479', 'dr5hn-2026-07-29'),
  (31509, 'Guano', 64, 2925, -1.60789000, -78.63105000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31509', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31562, 'Riobamba', 64, 2925, -1.67098000, -78.64712000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31562', 'dr5hn-2026-07-29'),
  (31517, 'La Maná', 64, 2921, -0.94094000, -79.22506000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31517', 'dr5hn-2026-07-29'),
  (31520, 'Latacunga', 64, 2921, -0.93521000, -78.61554000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31520', 'dr5hn-2026-07-29'),
  (31556, 'Pujilí', 64, 2921, -0.95759000, -78.69636000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31556', 'dr5hn-2026-07-29'),
  (31570, 'San Miguel de Salcedo', 64, 2921, -1.04547000, -78.59063000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31570', 'dr5hn-2026-07-29'),
  (31578, 'Saquisilí', 64, 2921, -0.83990000, -78.66700000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31578', 'dr5hn-2026-07-29'),
  (31512, 'Huaquillas', 64, 2924, -3.47523000, -80.23084000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31512', 'dr5hn-2026-07-29'),
  (31526, 'Machala', 64, 2924, -3.25861000, -79.96053000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31526', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31542, 'Pasaje', 64, 2924, -3.32561000, -79.80697000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31542', 'dr5hn-2026-07-29'),
  (31547, 'Piñas', 64, 2924, -3.68107000, -79.68083000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31547', 'dr5hn-2026-07-29'),
  (31549, 'Portovelo', 64, 2924, -3.72145000, -79.62187000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31549', 'dr5hn-2026-07-29'),
  (31553, 'Puerto Bolívar', 64, 2924, -3.26649000, -79.99749000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31553', 'dr5hn-2026-07-29'),
  (31576, 'Santa Rosa', 64, 2924, -3.44882000, -79.95952000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31576', 'dr5hn-2026-07-29'),
  (31592, 'Zaruma', 64, 2924, -3.69132000, -79.61174000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31592', 'dr5hn-2026-07-29'),
  (31505, 'Esmeraldas', 64, 2922, 0.95920000, -79.65397000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31505', 'dr5hn-2026-07-29'),
  (31531, 'Muisne', 64, 2922, 0.61129000, -80.01863000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31531', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31541, 'Pampanal de Bolívar', 64, 2922, 1.35251000, -78.89360000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31541', 'dr5hn-2026-07-29'),
  (31561, 'Rio Verde', 64, 2922, 1.06235000, -79.39939000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31561', 'dr5hn-2026-07-29'),
  (31564, 'Rosa Zarate', 64, 2922, 0.32779000, -79.47407000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31564', 'dr5hn-2026-07-29'),
  (31568, 'San Lorenzo de Esmeraldas', 64, 2922, 1.28626000, -78.83514000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31568', 'dr5hn-2026-07-29'),
  (31585, 'Valdez', 64, 2922, 1.24917000, -78.98306000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31585', 'dr5hn-2026-07-29'),
  (31551, 'Puerto Ayora', 64, 2905, -0.74018000, -90.31380000, 'Pacific/Galapagos', NULL, NULL, 'city', 'dr5hn:31551', 'dr5hn-2026-07-29'),
  (31552, 'Puerto Baquerizo Moreno', 64, 2905, -0.90172000, -89.61021000, 'Pacific/Galapagos', NULL, NULL, 'city', 'dr5hn:31552', 'dr5hn-2026-07-29'),
  (31555, 'Puerto Villamil', 64, 2905, -0.95542000, -90.96654000, 'Pacific/Galapagos', NULL, NULL, 'city', 'dr5hn:31555', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31480, 'Alfredo Baquerizo Moreno', 64, 2914, -1.91667000, -79.51667000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31480', 'dr5hn-2026-07-29'),
  (31488, 'Baláo', 64, 2914, -2.91100000, -79.81441000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31488', 'dr5hn-2026-07-29'),
  (31487, 'Balzar', 64, 2914, -1.36501000, -79.90494000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31487', 'dr5hn-2026-07-29'),
  (31498, 'Colimes', 64, 2914, -1.54553000, -80.01165000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31498', 'dr5hn-2026-07-29'),
  (31499, 'Coronel Marcelino Maridueña', 64, 2914, -2.20924000, -79.43248000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31499', 'dr5hn-2026-07-29'),
  (31502, 'El Triunfo', 64, 2914, -1.93333000, -79.96667000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31502', 'dr5hn-2026-07-29'),
  (31504, 'Eloy Alfaro', 64, 2914, -2.17579000, -79.85519000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31504', 'dr5hn-2026-07-29'),
  (31511, 'Guayaquil', 64, 2914, -2.19616000, -79.88621000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31511', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31522, 'Lomas de Sargentillo', 64, 2914, -1.88333000, -80.08333000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31522', 'dr5hn-2026-07-29'),
  (31528, 'Milagro', 64, 2914, -2.13404000, -79.59415000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31528', 'dr5hn-2026-07-29'),
  (31532, 'Naranjal', 64, 2914, -2.67364000, -79.61830000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31532', 'dr5hn-2026-07-29'),
  (31533, 'Naranjito', 64, 2914, -2.16671000, -79.46540000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31533', 'dr5hn-2026-07-29'),
  (31539, 'Palestina', 64, 2914, -1.93709000, -79.71396000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31539', 'dr5hn-2026-07-29'),
  (31544, 'Pedro Carbo', 64, 2914, -1.81563000, -80.23309000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31544', 'dr5hn-2026-07-29'),
  (31548, 'Playas', 64, 2914, -2.63199000, -80.38808000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31548', 'dr5hn-2026-07-29'),
  (31566, 'Samborondón', 64, 2914, -1.96276000, -79.72402000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31566', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31575, 'Santa Lucía', 64, 2914, -2.18333000, -80.00000000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31575', 'dr5hn-2026-07-29'),
  (31586, 'Velasco Ibarra', 64, 2914, -1.04376000, -79.63837000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31586', 'dr5hn-2026-07-29'),
  (31589, 'Yaguachi Nuevo', 64, 2914, -2.09680000, -79.69485000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31589', 'dr5hn-2026-07-29'),
  (31483, 'Atuntaqui', 64, 2911, 0.33247000, -78.21371000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31483', 'dr5hn-2026-07-29'),
  (31500, 'Cotacachi', 64, 2911, 0.30107000, -78.26428000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31500', 'dr5hn-2026-07-29'),
  (31513, 'Ibarra', 64, 2911, 0.35171000, -78.12233000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31513', 'dr5hn-2026-07-29'),
  (31536, 'Otavalo', 64, 2911, 0.23457000, -78.26248000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31536', 'dr5hn-2026-07-29'),
  (31546, 'Pimampiro', 64, 2911, 0.39116000, -77.94068000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31546', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (149262, 'Loja', 64, 5068, -3.99313000, -79.20422000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:149262', 'dr5hn-2026-07-29'),
  (31485, 'Babahoyo', 64, 2910, -1.80217000, -79.53443000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31485', 'dr5hn-2026-07-29'),
  (31494, 'Catarama', 64, 2910, -1.57504000, -79.45998000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31494', 'dr5hn-2026-07-29'),
  (31529, 'Montalvo', 64, 2910, -1.79008000, -79.28759000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31529', 'dr5hn-2026-07-29'),
  (31538, 'Palenque', 64, 2910, -1.43795000, -79.75647000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31538', 'dr5hn-2026-07-29'),
  (31559, 'Quevedo', 64, 2910, -1.02863000, -79.46352000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31559', 'dr5hn-2026-07-29'),
  (31587, 'Ventanas', 64, 2910, -1.44158000, -79.45943000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31587', 'dr5hn-2026-07-29'),
  (31588, 'Vinces', 64, 2910, -1.55611000, -79.75191000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31588', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31486, 'Bahía de Caráquez', 64, 2913, -0.59792000, -80.42367000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31486', 'dr5hn-2026-07-29'),
  (31491, 'Calceta', 64, 2913, -0.84582000, -80.16389000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31491', 'dr5hn-2026-07-29'),
  (31492, 'Cantón Portoviejo', 64, 2913, -1.05000000, -80.45000000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31492', 'dr5hn-2026-07-29'),
  (31497, 'Chone', 64, 2913, -0.69819000, -80.09361000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31497', 'dr5hn-2026-07-29'),
  (31514, 'Jipijapa', 64, 2913, -1.34872000, -80.57875000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31514', 'dr5hn-2026-07-29'),
  (31515, 'Junín', 64, 2913, -0.92777000, -80.20583000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31515', 'dr5hn-2026-07-29'),
  (31527, 'Manta', 64, 2913, -0.96212000, -80.71271000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31527', 'dr5hn-2026-07-29'),
  (31530, 'Montecristi', 64, 2913, -1.04576000, -80.65889000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31530', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31537, 'Paján', 64, 2913, -1.55238000, -80.42958000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31537', 'dr5hn-2026-07-29'),
  (31543, 'Pedernales', 64, 2913, 0.07167000, -80.05250000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31543', 'dr5hn-2026-07-29'),
  (31550, 'Portoviejo', 64, 2913, -1.05458000, -80.45445000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31550', 'dr5hn-2026-07-29'),
  (31563, 'Rocafuerte', 64, 2913, -0.92360000, -80.44946000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31563', 'dr5hn-2026-07-29'),
  (31571, 'San Vicente', 64, 2913, -0.60435000, -80.40267000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31571', 'dr5hn-2026-07-29'),
  (31573, 'Santa Ana', 64, 2913, -1.20726000, -80.37132000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31573', 'dr5hn-2026-07-29'),
  (31579, 'Sucre', 64, 2913, -1.27974000, -80.41885000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31579', 'dr5hn-2026-07-29'),
  (31582, 'Tosagua', 64, 2913, -0.78679000, -80.23473000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31582', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31508, 'Gualaquiza', 64, 2918, -3.40359000, -78.58166000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31508', 'dr5hn-2026-07-29'),
  (31524, 'Macas', 64, 2918, -2.30868000, -78.11135000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31524', 'dr5hn-2026-07-29'),
  (31540, 'Palora', 64, 2918, -1.70131000, -77.96516000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31540', 'dr5hn-2026-07-29'),
  (31580, 'Sucúa', 64, 2918, -2.45866000, -78.17171000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31580', 'dr5hn-2026-07-29'),
  (31482, 'Archidona', 64, 2916, -0.90950000, -77.80772000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31482', 'dr5hn-2026-07-29'),
  (31581, 'Tena', 64, 2916, -0.99380000, -77.81286000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31581', 'dr5hn-2026-07-29'),
  (31490, 'Boca Suno', 64, 2926, -0.69832000, -77.14083000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31490', 'dr5hn-2026-07-29'),
  (31506, 'Francisco de Orellana Canton', 64, 2926, -0.46667000, -76.96667000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31506', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31523, 'Loreto Canton', 64, 2926, -0.69487000, -77.30255000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31523', 'dr5hn-2026-07-29'),
  (31554, 'Puerto Francisco de Orellana', 64, 2926, -0.46645000, -76.98719000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31554', 'dr5hn-2026-07-29'),
  (31557, 'Puyo', 64, 2907, -1.48369000, -78.00257000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31557', 'dr5hn-2026-07-29'),
  (31495, 'Cayambe', 64, 2927, 0.04084000, -78.14524000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31495', 'dr5hn-2026-07-29'),
  (31525, 'Machachi', 64, 2927, -0.51011000, -78.56712000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31525', 'dr5hn-2026-07-29'),
  (31560, 'Quito', 64, 2927, -0.22985000, -78.52495000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31560', 'dr5hn-2026-07-29'),
  (31572, 'Sangolquí', 64, 2927, -0.33405000, -78.45217000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31572', 'dr5hn-2026-07-29'),
  (31516, 'La Libertad', 64, 2912, -2.23300000, -80.91039000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31516', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31565, 'Salinas', 64, 2912, -2.21452000, -80.95151000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31565', 'dr5hn-2026-07-29'),
  (31574, 'Santa Elena', 64, 2912, -2.22622000, -80.85873000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31574', 'dr5hn-2026-07-29'),
  (31577, 'Santo Domingo de los Colorados', 64, 2919, -0.25305000, -79.17536000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31577', 'dr5hn-2026-07-29'),
  (31534, 'Nueva Loja', 64, 2906, 0.08600000, -76.89528000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31534', 'dr5hn-2026-07-29'),
  (31481, 'Ambato', 64, 2908, -1.24908000, -78.61675000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31481', 'dr5hn-2026-07-29'),
  (31489, 'Baños', 64, 2908, -1.39699000, -78.42289000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31489', 'dr5hn-2026-07-29'),
  (31545, 'Pelileo', 64, 2908, -1.32990000, -78.54341000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31545', 'dr5hn-2026-07-29'),
  (31558, 'Píllaro', 64, 2908, -1.17414000, -78.54676000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31558', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (31590, 'Yantzaza', 64, 2909, -3.83261000, -78.76076000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31590', 'dr5hn-2026-07-29'),
  (31591, 'Zamora', 64, 2909, -4.06685000, -78.95488000, 'America/Guayaquil', NULL, NULL, 'city', 'dr5hn:31591', 'dr5hn-2026-07-29');
