-- Cities for GA (Gabon): 28 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (48131, 'Cocobeach', 79, 2727, 1.00019000, 9.58229000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48131', 'dr5hn-2026-07-29'),
  (48138, 'Libreville', 79, 2727, 0.39241000, 9.45356000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48138', 'dr5hn-2026-07-29'),
  (48150, 'Ntoum', 79, 2727, 0.39051000, 9.76096000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48150', 'dr5hn-2026-07-29'),
  (48133, 'Franceville', 79, 2726, -1.63333000, 13.58357000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48133', 'dr5hn-2026-07-29'),
  (48139, 'Lékoni', 79, 2726, -1.58431000, 14.25905000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48139', 'dr5hn-2026-07-29'),
  (48145, 'Moanda', 79, 2726, -1.56652000, 13.19870000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48145', 'dr5hn-2026-07-29'),
  (48147, 'Mounana', 79, 2726, -1.40850000, 13.15857000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48147', 'dr5hn-2026-07-29'),
  (48151, 'Okondja', 79, 2726, -0.65487000, 13.67533000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48151', 'dr5hn-2026-07-29');
  (48136, 'Lambaréné', 79, 2730, -0.70010000, 10.24055000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48136', 'dr5hn-2026-07-29'),
  (48149, 'Ndjolé', 79, 2730, -0.17827000, 10.76488000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48149', 'dr5hn-2026-07-29'),
  (48132, 'Fougamou', 79, 2731, -1.21544000, 10.58378000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48132', 'dr5hn-2026-07-29'),
  (48142, 'Mbigou', 79, 2731, -1.90046000, 11.90600000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48142', 'dr5hn-2026-07-29'),
  (48143, 'Mimongo', 79, 2731, -1.61952000, 11.60675000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48143', 'dr5hn-2026-07-29'),
  (48146, 'Mouila', 79, 2731, -1.86846000, 11.05594000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48146', 'dr5hn-2026-07-29'),
  (48148, 'Ndendé', 79, 2731, -2.40077000, 11.35813000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48148', 'dr5hn-2026-07-29'),
  (48141, 'Mayumba', 79, 2725, -3.43198000, 10.65540000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48141', 'dr5hn-2026-07-29');
  (48155, 'Tchibanga', 79, 2725, -2.93323000, 10.98178000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48155', 'dr5hn-2026-07-29'),
  (48130, 'Booué', 79, 2724, -0.09207000, 11.93846000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48130', 'dr5hn-2026-07-29'),
  (48140, 'Makokou', 79, 2724, 0.57381000, 12.86419000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48140', 'dr5hn-2026-07-29'),
  (48156, 'Zadie', 79, 2724, 0.92582000, 13.90813000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48156', 'dr5hn-2026-07-29'),
  (48135, 'Koulamoutou', 79, 2729, -1.13667000, 12.46399000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48135', 'dr5hn-2026-07-29'),
  (48137, 'Lastoursville', 79, 2729, -0.81742000, 12.70818000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48137', 'dr5hn-2026-07-29'),
  (48134, 'Gamba', 79, 2728, -2.65000000, 10.00000000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48134', 'dr5hn-2026-07-29'),
  (48152, 'Omboué', 79, 2728, -1.57464000, 9.26184000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48152', 'dr5hn-2026-07-29');
  (48154, 'Port-Gentil', 79, 2728, -0.71933000, 8.78151000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48154', 'dr5hn-2026-07-29'),
  (48129, 'Bitam', 79, 2723, 2.07597000, 11.50065000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48129', 'dr5hn-2026-07-29'),
  (48144, 'Mitzic', 79, 2723, 0.78205000, 11.54904000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48144', 'dr5hn-2026-07-29'),
  (48153, 'Oyem', 79, 2723, 1.59950000, 11.57933000, 'Africa/Libreville', NULL, NULL, 'city', 'dr5hn:48153', 'dr5hn-2026-07-29');
