-- Cities for GF (French Guiana): 22 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (162109, 'Apatou', 76, 5818, 5.15666667, -54.34305556, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162109', 'dr5hn-2026-07-29'),
  (162110, 'Awala-Yalimapo', 76, 5818, 5.73611111, -53.90805556, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162110', 'dr5hn-2026-07-29'),
  (162111, 'Camopi', 76, 5818, 3.16694444, -52.33111111, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162111', 'dr5hn-2026-07-29'),
  (162112, 'Cayenne', 76, 5818, 4.93861111, -52.33500000, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162112', 'dr5hn-2026-07-29'),
  (162113, 'Grand-Santi', 76, 5818, 4.27333333, -54.38166667, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162113', 'dr5hn-2026-07-29'),
  (162114, 'Iracoubo', 76, 5818, 5.48000000, -53.20555556, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162114', 'dr5hn-2026-07-29'),
  (162115, 'Kourou', 76, 5818, 5.15833333, -52.64277778, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162115', 'dr5hn-2026-07-29'),
  (162116, 'Macouria', 76, 5818, 5.01361111, -52.47388889, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162116', 'dr5hn-2026-07-29');
  (162117, 'Mana', 76, 5818, 5.66722222, -53.77694444, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162117', 'dr5hn-2026-07-29'),
  (162118, 'Maripasoula', 76, 5818, 3.64111111, -54.02777778, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162118', 'dr5hn-2026-07-29'),
  (162119, 'Matoury', 76, 5818, 4.85055556, -52.33111111, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162119', 'dr5hn-2026-07-29'),
  (162120, 'Montsinéry-Tonnegrande', 76, 5818, 4.89277778, -52.49277778, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162120', 'dr5hn-2026-07-29'),
  (162121, 'Ouanary', 76, 5818, 4.20916667, -51.67166667, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162121', 'dr5hn-2026-07-29'),
  (162122, 'Papaichton', 76, 5818, 3.80972222, -54.14888889, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162122', 'dr5hn-2026-07-29'),
  (162123, 'Régina', 76, 5818, 4.31361111, -52.12916667, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162123', 'dr5hn-2026-07-29'),
  (162124, 'Remire-Montjoly', 76, 5818, 4.90500000, -52.27638889, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162124', 'dr5hn-2026-07-29');
  (162125, 'Roura', 76, 5818, 4.72833333, -52.32416667, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162125', 'dr5hn-2026-07-29'),
  (162126, 'Saint-Élie', 76, 5818, 4.82555556, -53.28805556, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162126', 'dr5hn-2026-07-29'),
  (162127, 'Saint-Georges', 76, 5818, 3.88944444, -51.80111111, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162127', 'dr5hn-2026-07-29'),
  (162128, 'Saint-Laurent-du-Maroni', 76, 5818, 5.50388889, -54.02888889, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162128', 'dr5hn-2026-07-29'),
  (162129, 'Saül', 76, 5818, 3.62277778, -53.20833333, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162129', 'dr5hn-2026-07-29'),
  (162130, 'Sinnamary', 76, 5818, 5.37750000, -52.95861111, 'America/Cayenne', NULL, NULL, 'city', 'dr5hn:162130', 'dr5hn-2026-07-29');
