-- Cities for JE (Jersey): 51 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 7 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154101, 'Vingtaine de la Rocque', 110, 5309, 49.17048880, -2.03389140, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154101', 'dr5hn-2026-07-29'),
  (154099, 'Vingtaine de la Rue', 110, 5309, 49.18661230, -2.05316130, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154099', 'dr5hn-2026-07-29'),
  (154100, 'Vingtaine de Longueville', 110, 5309, 49.19001830, -2.04917800, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154100', 'dr5hn-2026-07-29'),
  (154098, 'Vingtaine des Marais', 110, 5309, 49.18556300, -2.05042200, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154098', 'dr5hn-2026-07-29'),
  (154105, 'Vingtaine de la Moye', 110, 5310, 49.18445480, -2.23950470, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154105', 'dr5hn-2026-07-29'),
  (154102, 'Vingtaine de Noirmont', 110, 5310, 49.17269850, -2.22550510, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154102', 'dr5hn-2026-07-29'),
  (154104, 'Vingtaine des Quennevais', 110, 5310, 49.19704320, -2.21618080, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154104', 'dr5hn-2026-07-29'),
  (154103, 'Vingtaine du Coin', 110, 5310, 49.18753960, -2.18473710, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154103', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154106, 'Grande Vingtaine', 110, 5311, 49.17207130, -2.06199370, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154106', 'dr5hn-2026-07-29'),
  (154108, 'Vingtaine de Samarès', 110, 5311, 49.16497580, -2.09880290, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154108', 'dr5hn-2026-07-29'),
  (154107, 'Vingtaine du Rocquier', 110, 5311, 49.17250500, -2.06543840, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154107', 'dr5hn-2026-07-29'),
  (154111, 'Vingtaine de Bas du Mont au Prêtre', 110, 5312, 49.19939590, -2.11964080, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154111', 'dr5hn-2026-07-29'),
  (154112, 'Vingtaine de Haut du Mont au Prêtre', 110, 5312, 49.20242510, -2.09919230, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154112', 'dr5hn-2026-07-29'),
  (154109, 'Vingtaine de la Ville', 110, 5312, 49.17883320, -2.10357590, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154109', 'dr5hn-2026-07-29'),
  (154113, 'Vingtaine du Mont à l''Abbé', 110, 5312, 49.20036330, -2.13384390, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154113', 'dr5hn-2026-07-29'),
  (154114, 'Vingtaine du Mont Cochon', 110, 5312, 49.19975370, -2.14757550, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154114', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154110, 'Vingtaine du Rouge Bouillon', 110, 5312, 49.19291200, -2.10935300, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154110', 'dr5hn-2026-07-29'),
  (154116, 'Vingtaine de Hérupe', 110, 5313, 49.23330120, -2.12357080, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154116', 'dr5hn-2026-07-29'),
  (154117, 'Vingtaine du Douet', 110, 5313, 49.23459620, -2.17227710, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154117', 'dr5hn-2026-07-29'),
  (154115, 'Vingtaine du Nord', 110, 5313, 49.23938780, -2.12069720, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154115', 'dr5hn-2026-07-29'),
  (154119, 'Vingtaine Bas de la Vallée', 110, 5314, 49.19584680, -2.15669220, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154119', 'dr5hn-2026-07-29'),
  (154120, 'Vingtaine du Coin Hatain', 110, 5314, 49.22074360, -2.12697490, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154120', 'dr5hn-2026-07-29'),
  (154121, 'Vingtaine du Coin Motier', 110, 5314, 49.22490170, -2.13965400, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154121', 'dr5hn-2026-07-29'),
  (154122, 'Vingtaine du Coin Tourgis Nord', 110, 5314, 49.22924990, -2.15092570, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154122', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154123, 'Vingtaine du Coin Tourgis Sud', 110, 5314, 49.21059460, -2.15264330, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154123', 'dr5hn-2026-07-29'),
  (154125, 'Vingtaine de Faldouet', 110, 5315, 49.20322040, -2.05269720, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154125', 'dr5hn-2026-07-29'),
  (154126, 'Vingtaine de la Quéruée', 110, 5315, 49.21499100, -2.05603630, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154126', 'dr5hn-2026-07-29'),
  (154124, 'Vingtaine de Rozel', 110, 5315, 49.23569500, -2.05048470, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154124', 'dr5hn-2026-07-29'),
  (154128, 'Vingtaine du Fief de la Reine', 110, 5315, 49.21842770, -2.03518790, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154128', 'dr5hn-2026-07-29'),
  (154130, 'Vingtaine du Nord', 110, 5316, 49.24426390, -2.18082260, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154130', 'dr5hn-2026-07-29'),
  (154129, 'Vingtaine du Sud', 110, 5316, 49.23404250, -2.16730840, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154129', 'dr5hn-2026-07-29'),
  (154133, 'Cueillette de Grantez', 110, 5317, 49.23123970, -2.22339030, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154133', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154136, 'Cueillette de Léoville', 110, 5317, 49.23803240, -2.22634870, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154136', 'dr5hn-2026-07-29'),
  (154134, 'Cueillette de Millais', 110, 5317, 49.24085370, -2.24330420, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154134', 'dr5hn-2026-07-29'),
  (154135, 'Cueillette de Vinchelez', 110, 5317, 49.24447800, -2.23905430, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154135', 'dr5hn-2026-07-29'),
  (154132, 'Grande Cueillette', 110, 5317, 49.22331000, -2.21609880, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154132', 'dr5hn-2026-07-29'),
  (154131, 'Petite Cueillette', 110, 5317, 49.22456770, -2.19656550, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154131', 'dr5hn-2026-07-29'),
  (154138, 'Grande Vingtaine', 110, 5318, 49.21065500, -2.19606360, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154138', 'dr5hn-2026-07-29'),
  (154139, 'Vingtaine des Augerez', 110, 5318, 49.20776790, -2.18629780, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154139', 'dr5hn-2026-07-29'),
  (154140, 'Vingtaine du Coin Varin', 110, 5318, 49.21451950, -2.18722550, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154140', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154137, 'Vingtaine du Douet', 110, 5318, 49.20988070, -2.18453420, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154137', 'dr5hn-2026-07-29'),
  (154146, 'Vingtaine de la Grande Longueville', 110, 5319, 49.18786710, -2.07502150, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154146', 'dr5hn-2026-07-29'),
  (154141, 'Vingtaine de la Petite Longueville', 110, 5319, 49.18090340, -2.08121620, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154141', 'dr5hn-2026-07-29'),
  (154143, 'Vingtaine de Maufant', 110, 5319, 49.20822960, -2.10060600, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154143', 'dr5hn-2026-07-29'),
  (154144, 'Vingtaine de Sous la Hougue', 110, 5319, 49.21377110, -2.13576620, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154144', 'dr5hn-2026-07-29'),
  (154145, 'Vingtaine des Pigneaux', 110, 5319, 49.20262700, -2.07080670, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154145', 'dr5hn-2026-07-29'),
  (154151, 'Vingtaine de la Croiserie', 110, 5320, 49.21646930, -2.09164410, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154151', 'dr5hn-2026-07-29'),
  (154147, 'Vingtaine de la Ville-à-l''Évêque', 110, 5320, 49.23176480, -2.12236840, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154147', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (154148, 'Vingtaine de Rozel', 110, 5320, 49.23842870, -2.06704060, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154148', 'dr5hn-2026-07-29'),
  (154150, 'Vingtaine des Augrès', 110, 5320, 49.22857290, -2.08235050, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154150', 'dr5hn-2026-07-29'),
  (154149, 'Vingtaine du Rondin', 110, 5320, 49.23706240, -2.08753310, 'Europe/Jersey', NULL, NULL, 'city', 'dr5hn:154149', 'dr5hn-2026-07-29');
