-- Cities for KN (Saint Kitts and Nevis): 13 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 2 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65176, 'Nicola Town', 185, 3833, 17.37956000, -62.75318000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65176', 'dr5hn-2026-07-29'),
  (65178, 'Sandy Point Town', 185, 3836, 17.35908000, -62.84858000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65178', 'dr5hn-2026-07-29'),
  (65172, 'Market Shop', 185, 3837, 17.13218000, -62.57267000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65172', 'dr5hn-2026-07-29'),
  (65175, 'Newcastle', 185, 3835, 17.20000000, -62.58333000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65175', 'dr5hn-2026-07-29'),
  (65170, 'Dieppe Bay Town', 185, 3845, 17.41473000, -62.81390000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65170', 'dr5hn-2026-07-29'),
  (65171, 'Fig Tree', 185, 3840, 17.12623000, -62.60265000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65171', 'dr5hn-2026-07-29'),
  (65167, 'Cayon', 185, 3844, 17.35000000, -62.73333000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65167', 'dr5hn-2026-07-29'),
  (65177, 'Saint Paul’s', 185, 3834, 17.40605000, -62.83562000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65177', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65168, 'Charlestown', 185, 3838, 17.13333000, -62.61667000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65168', 'dr5hn-2026-07-29'),
  (65174, 'Monkey Hill', 185, 3831, 17.32327000, -62.72914000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65174', 'dr5hn-2026-07-29'),
  (65169, 'Cotton Ground', 185, 3839, 17.16667000, -62.61667000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65169', 'dr5hn-2026-07-29'),
  (65173, 'Middle Island', 185, 3842, 17.32590000, -62.81055000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65173', 'dr5hn-2026-07-29'),
  (65179, 'Trinity', 185, 3843, 17.30037000, -62.77584000, 'America/St_Kitts', NULL, NULL, 'city', 'dr5hn:65179', 'dr5hn-2026-07-29');
