-- Cities for KW (Kuwait): 25 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 4 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65572, 'Al Aḩmadī', 117, 977, 29.07694000, 48.08389000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65572', 'dr5hn-2026-07-29'),
  (65574, 'Al Faḩāḩīl', 117, 977, 29.08250000, 48.13028000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65574', 'dr5hn-2026-07-29'),
  (65575, 'Al Finţās', 117, 977, 29.17389000, 48.12111000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65575', 'dr5hn-2026-07-29'),
  (65578, 'Al Mahbūlah', 117, 977, 29.14500000, 48.13028000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65578', 'dr5hn-2026-07-29'),
  (65579, 'Al Manqaf', 117, 977, 29.09611000, 48.13278000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65579', 'dr5hn-2026-07-29'),
  (65580, 'Al Wafrah', 117, 977, 28.63917000, 47.93056000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65580', 'dr5hn-2026-07-29'),
  (65582, 'Ar Riqqah', 117, 977, 29.14583000, 48.09472000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65582', 'dr5hn-2026-07-29'),
  (65571, 'Ad Dasmah', 117, 976, 29.36500000, 48.00139000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65571', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65584, 'Ar Rābiyah', 117, 976, 29.29500000, 47.93306000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65584', 'dr5hn-2026-07-29'),
  (65586, 'Ash Shāmīyah', 117, 976, 29.34722000, 47.96167000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65586', 'dr5hn-2026-07-29'),
  (65587, 'Az Zawr', 117, 976, 29.44250000, 48.27472000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65587', 'dr5hn-2026-07-29'),
  (65590, 'Kuwait City', 117, 976, 29.36972000, 47.97833000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65590', 'dr5hn-2026-07-29'),
  (65573, 'Al Farwānīyah', 117, 975, 29.27750000, 47.95861000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65573', 'dr5hn-2026-07-29'),
  (65589, 'Janūb as Surrah', 117, 975, 29.26917000, 47.97806000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65589', 'dr5hn-2026-07-29'),
  (65577, 'Al Jahrā’', 117, 972, 29.33750000, 47.65806000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65577', 'dr5hn-2026-07-29'),
  (65583, 'Ar Rumaythīyah', 117, 973, 29.31167000, 48.07417000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65583', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65585, 'As Sālimīyah', 117, 973, 29.33389000, 48.07611000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65585', 'dr5hn-2026-07-29'),
  (65588, 'Bayān', 117, 973, 29.30320000, 48.04881000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65588', 'dr5hn-2026-07-29'),
  (65593, 'Ḩawallī', 117, 973, 29.33278000, 48.02861000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65593', 'dr5hn-2026-07-29'),
  (65591, 'Salwá', 117, 973, 29.29583000, 48.07861000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65591', 'dr5hn-2026-07-29'),
  (65569, 'Abu Al Hasaniya', 117, 974, 29.19076000, 48.11355000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65569', 'dr5hn-2026-07-29'),
  (65570, 'Abu Fatira', 117, 974, 29.19746000, 48.10278000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65570', 'dr5hn-2026-07-29'),
  (65576, 'Al Funayţīs', 117, 974, 29.22528000, 48.10167000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65576', 'dr5hn-2026-07-29'),
  (65581, 'Al-Masayel', 117, 974, 29.23930000, 48.08862000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65581', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65592, 'Şabāḩ as Sālim', 117, 974, 29.25722000, 48.05722000, 'Asia/Kuwait', NULL, NULL, 'city', 'dr5hn:65592', 'dr5hn-2026-07-29');
