-- Cities for KZ (Kazakhstan): 259 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 33 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65596, 'Akkol', 112, 145, 51.99374000, 70.94704000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65596', 'dr5hn-2026-07-29'),
  (65597, 'Akkol’', 112, 145, 53.29617000, 69.59997000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65597', 'dr5hn-2026-07-29'),
  (65600, 'Aksu', 112, 145, 52.44422000, 71.95761000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65600', 'dr5hn-2026-07-29'),
  (65619, 'Astrakhan', 112, 145, 51.53092000, 69.79684000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65619', 'dr5hn-2026-07-29'),
  (65624, 'Atbasar', 112, 145, 51.80652000, 68.35996000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65624', 'dr5hn-2026-07-29'),
  (65632, 'Balkashino', 112, 145, 52.51779000, 68.75160000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65632', 'dr5hn-2026-07-29'),
  (65647, 'Bestobe', 112, 145, 52.49795000, 73.09592000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65647', 'dr5hn-2026-07-29'),
  (65665, 'Derzhavīnsk', 112, 145, 51.09922000, 66.31557000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65665', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65672, 'Egindiköl', 112, 145, 51.05412000, 69.47928000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65672', 'dr5hn-2026-07-29'),
  (65676, 'Esil', 112, 145, 51.95495000, 66.40841000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65676', 'dr5hn-2026-07-29'),
  (65698, 'Kokshetau', 112, 145, 53.28333000, 69.40000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65698', 'dr5hn-2026-07-29'),
  (65703, 'Krasnogorskiy', 112, 145, 52.24560000, 66.52081000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65703', 'dr5hn-2026-07-29'),
  (65720, 'Makinsk', 112, 145, 52.63290000, 70.41911000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65720', 'dr5hn-2026-07-29'),
  (65781, 'Shantobe', 112, 145, 52.45376000, 68.17475000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65781', 'dr5hn-2026-07-29'),
  (65784, 'Shchuchinsk', 112, 145, 52.93592000, 70.18895000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65784', 'dr5hn-2026-07-29'),
  (65787, 'Shortandy', 112, 145, 51.69946000, 70.99457000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65787', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65796, 'Stepnogorsk', 112, 145, 52.35062000, 71.88161000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65796', 'dr5hn-2026-07-29'),
  (65797, 'Stepnyak', 112, 145, 52.83489000, 70.78861000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65797', 'dr5hn-2026-07-29'),
  (65830, 'Yermentau', 112, 145, 51.62364000, 73.10265000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65830', 'dr5hn-2026-07-29'),
  (65832, 'Zavodskoy', 112, 145, 52.47031000, 72.01514000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65832', 'dr5hn-2026-07-29'),
  (65840, 'Zhaqsy', 112, 145, 51.91058000, 67.31665000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65840', 'dr5hn-2026-07-29'),
  (65847, 'Zholymbet', 112, 145, 51.74211000, 71.71245000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65847', 'dr5hn-2026-07-29'),
  (65605, 'Aktobe', 112, 151, 50.27969000, 57.20718000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65605', 'dr5hn-2026-07-29'),
  (65636, 'Batamshinskiy', 112, 151, 50.56022000, 58.27715000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65636', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65638, 'Bayganin', 112, 151, 48.68975000, 55.87512000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65638', 'dr5hn-2026-07-29'),
  (65674, 'Embi', 112, 151, 48.82981000, 58.15042000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65674', 'dr5hn-2026-07-29'),
  (65687, 'Kandyagash', 112, 151, 49.46912000, 57.41914000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65687', 'dr5hn-2026-07-29'),
  (65697, 'Khromtau', 112, 151, 50.25117000, 58.44003000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65697', 'dr5hn-2026-07-29'),
  (65725, 'Martuk', 112, 151, 50.74746000, 56.50611000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65725', 'dr5hn-2026-07-29'),
  (65779, 'Shalqar', 112, 151, 47.83333000, 59.60000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65779', 'dr5hn-2026-07-29'),
  (65788, 'Shubarkuduk', 112, 151, 49.14391000, 56.48196000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65788', 'dr5hn-2026-07-29'),
  (65790, 'Shubarshi', 112, 151, 48.58022000, 57.18289000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65790', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65808, 'Temir', 112, 151, 49.14132000, 57.12855000, 'Asia/Aqtobe', NULL, NULL, 'city', 'dr5hn:65808', 'dr5hn-2026-07-29'),
  (65831, 'Yrghyz', 112, 151, 48.61667000, 61.26667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65831', 'dr5hn-2026-07-29'),
  (65631, 'Bakanas', 112, 143, 44.80838000, 76.27214000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65631', 'dr5hn-2026-07-29'),
  (65633, 'Balpyk Bī', 112, 143, 44.90225000, 78.23157000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65633', 'dr5hn-2026-07-29'),
  (65656, 'Burunday', 112, 143, 43.35567000, 76.85477000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65656', 'dr5hn-2026-07-29'),
  (65661, 'Chemolgan', 112, 143, 43.37633000, 76.62456000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65661', 'dr5hn-2026-07-29'),
  (65668, 'Druzhba', 112, 143, 45.25332000, 82.48044000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65668', 'dr5hn-2026-07-29'),
  (65675, 'Esik', 112, 143, 43.35520000, 77.45245000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65675', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65689, 'Kapshagay', 112, 143, 43.86681000, 77.06304000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65689', 'dr5hn-2026-07-29'),
  (65694, 'Kegen', 112, 143, 43.02143000, 79.22055000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65694', 'dr5hn-2026-07-29'),
  (65715, 'Lepsy', 112, 143, 46.23500000, 78.94556000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65715', 'dr5hn-2026-07-29'),
  (65726, 'Matay', 112, 143, 45.89500000, 78.71806000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65726', 'dr5hn-2026-07-29'),
  (65742, 'Otegen Batyra', 112, 143, 43.41949000, 77.02020000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65742', 'dr5hn-2026-07-29'),
  (65746, 'Pervomayka', 112, 143, 43.37361000, 76.94000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65746', 'dr5hn-2026-07-29'),
  (65763, 'Sarkand', 112, 143, 45.41126000, 79.91545000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65763', 'dr5hn-2026-07-29'),
  (65767, 'Saryozek', 112, 143, 44.36178000, 77.97279000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65767', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65800, 'Taldykorgan', 112, 143, 45.01556000, 78.37389000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65800', 'dr5hn-2026-07-29'),
  (65801, 'Talghar', 112, 143, 43.30348000, 77.24085000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65801', 'dr5hn-2026-07-29'),
  (65807, 'Tekeli', 112, 143, 44.83322000, 78.83089000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65807', 'dr5hn-2026-07-29'),
  (65818, 'Turgen', 112, 143, 43.40056000, 77.59333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65818', 'dr5hn-2026-07-29'),
  (65852, 'Ülken', 112, 143, 45.21194000, 73.97861000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65852', 'dr5hn-2026-07-29'),
  (65823, 'Ush-Tyube', 112, 143, 45.25201000, 77.98007000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65823', 'dr5hn-2026-07-29'),
  (65841, 'Zharkent', 112, 143, 44.16660000, 80.00655000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65841', 'dr5hn-2026-07-29'),
  (65607, 'Almaty', 112, 152, 43.25667000, 76.92861000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65607', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65737, 'Nur-Sultan', 112, 156, 51.18010000, 71.44598000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65737', 'dr5hn-2026-07-29'),
  (65598, 'Akkol’', 112, 153, 48.77177000, 53.18580000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65598', 'dr5hn-2026-07-29'),
  (65625, 'Atyrau', 112, 153, 47.11667000, 51.88333000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65625', 'dr5hn-2026-07-29'),
  (65635, 'Balykshi', 112, 153, 47.06667000, 51.86667000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65635', 'dr5hn-2026-07-29'),
  (65639, 'Bayshonas', 112, 153, 47.24139000, 52.94111000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65639', 'dr5hn-2026-07-29'),
  (65667, 'Dossor', 112, 153, 47.52722000, 52.98111000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65667', 'dr5hn-2026-07-29'),
  (65684, 'Inderbor', 112, 153, 48.55000000, 51.78333000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65684', 'dr5hn-2026-07-29'),
  (65719, 'Makhambet', 112, 153, 47.66667000, 51.58333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65719', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65722, 'Maloye Ganyushkino', 112, 153, 46.60000000, 49.26667000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65722', 'dr5hn-2026-07-29'),
  (65723, 'Maqat', 112, 153, 47.65000000, 53.31667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65723', 'dr5hn-2026-07-29'),
  (65729, 'Miyaly', 112, 153, 48.88504000, 53.79194000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65729', 'dr5hn-2026-07-29'),
  (65751, 'Qaraton', 112, 153, 46.43528000, 53.48639000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65751', 'dr5hn-2026-07-29'),
  (65759, 'Qulsary', 112, 153, 46.95307000, 54.01978000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65759', 'dr5hn-2026-07-29'),
  (65778, 'Shalkar', 112, 153, 48.03333000, 48.90000000, 'Asia/Atyrau', NULL, NULL, 'city', 'dr5hn:65778', 'dr5hn-2026-07-29'),
  (65608, 'Altayskiy', 112, 154, 50.24593000, 82.36252000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65608', 'dr5hn-2026-07-29'),
  (65613, 'Aqtoghay', 112, 154, 46.95000000, 79.66667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65613', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65621, 'Asūbulaq', 112, 154, 49.55688000, 83.06355000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65621', 'dr5hn-2026-07-29'),
  (65626, 'Auezov', 112, 154, 49.71003000, 81.58018000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65626', 'dr5hn-2026-07-29'),
  (65627, 'Ayagoz', 112, 154, 47.96447000, 80.43437000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65627', 'dr5hn-2026-07-29'),
  (65643, 'Belogorskīy', 112, 154, 49.47698000, 83.14803000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65643', 'dr5hn-2026-07-29'),
  (65645, 'Belousovka', 112, 154, 50.13287000, 82.52481000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65645', 'dr5hn-2026-07-29'),
  (65651, 'Borodulikha', 112, 154, 50.71841000, 80.92950000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65651', 'dr5hn-2026-07-29'),
  (65681, 'Georgīevka', 112, 154, 49.32671000, 81.57373000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65681', 'dr5hn-2026-07-29'),
  (65682, 'Glubokoye', 112, 154, 50.13887000, 82.31114000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65682', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65705, 'Kurchatov', 112, 154, 50.75617000, 78.54188000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65705', 'dr5hn-2026-07-29'),
  (65706, 'Kurchum', 112, 154, 48.56603000, 83.66146000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65706', 'dr5hn-2026-07-29'),
  (65721, 'Maleyevsk', 112, 154, 49.81441000, 84.29102000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65721', 'dr5hn-2026-07-29'),
  (65738, 'Ognevka', 112, 154, 49.68351000, 83.01674000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65738', 'dr5hn-2026-07-29'),
  (65749, 'Priisk Boko', 112, 154, 49.06028000, 81.64528000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65749', 'dr5hn-2026-07-29'),
  (65753, 'Qaraūyl', 112, 154, 48.94509000, 79.25502000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65753', 'dr5hn-2026-07-29'),
  (65761, 'Ridder', 112, 154, 50.34413000, 83.51287000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65761', 'dr5hn-2026-07-29'),
  (65774, 'Semey', 112, 154, 50.42675000, 80.26669000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65774', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65782, 'Shar', 112, 154, 49.58720000, 81.04883000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65782', 'dr5hn-2026-07-29'),
  (65785, 'Shemonaīkha', 112, 154, 50.62811000, 81.91213000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65785', 'dr5hn-2026-07-29'),
  (65798, 'Suykbulak', 112, 154, 49.70837000, 81.04854000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65798', 'dr5hn-2026-07-29'),
  (65821, 'Tūghyl', 112, 154, 47.72521000, 84.20629000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65821', 'dr5hn-2026-07-29'),
  (65822, 'Urzhar', 112, 154, 47.09302000, 81.62939000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65822', 'dr5hn-2026-07-29'),
  (65824, 'Ust-Kamenogorsk', 112, 154, 49.97143000, 82.60586000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65824', 'dr5hn-2026-07-29'),
  (65853, 'Ūst’-Talovka', 112, 154, 50.54927000, 81.84997000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65853', 'dr5hn-2026-07-29'),
  (65833, 'Zaysan', 112, 154, 47.46657000, 84.87144000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65833', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65835, 'Zhalghyztobe', 112, 154, 49.21094000, 81.21596000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65835', 'dr5hn-2026-07-29'),
  (65838, 'Zhanga Buqtyrma', 112, 154, 49.62950000, 83.52475000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65838', 'dr5hn-2026-07-29'),
  (65845, 'Zhezkent', 112, 154, 50.93112000, 81.36150000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65845', 'dr5hn-2026-07-29'),
  (65850, 'Zyryanovsk', 112, 154, 49.72654000, 84.27318000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65850', 'dr5hn-2026-07-29'),
  (65610, 'Aqbaqay', 112, 147, 45.00000000, 72.78333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65610', 'dr5hn-2026-07-29'),
  (65663, 'Chu', 112, 147, 43.60334000, 73.75919000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65663', 'dr5hn-2026-07-29'),
  (65680, 'Georgiyevka', 112, 147, 43.03882000, 74.71287000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65680', 'dr5hn-2026-07-29'),
  (65683, 'Granitogorsk', 112, 147, 42.74400000, 73.46848000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65683', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65692, 'Karatau', 112, 147, 43.17869000, 70.46768000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65692', 'dr5hn-2026-07-29'),
  (65696, 'Khantaū', 112, 147, 44.22744000, 73.79555000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65696', 'dr5hn-2026-07-29'),
  (65717, 'Lugovoy', 112, 147, 42.94197000, 72.76098000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65717', 'dr5hn-2026-07-29'),
  (65718, 'Lugovoye', 112, 147, 42.91010000, 72.72066000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65718', 'dr5hn-2026-07-29'),
  (65728, 'Merke', 112, 147, 42.86976000, 73.18463000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65728', 'dr5hn-2026-07-29'),
  (65730, 'Moyynkum', 112, 147, 44.28461000, 72.93920000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65730', 'dr5hn-2026-07-29'),
  (65733, 'Mynaral', 112, 147, 45.41611000, 73.68444000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65733', 'dr5hn-2026-07-29'),
  (65743, 'Oytal', 112, 147, 42.90573000, 73.26972000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65743', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65766, 'Sarykemer', 112, 147, 43.00000000, 71.50000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65766', 'dr5hn-2026-07-29'),
  (65791, 'Shyghanaq', 112, 147, 44.83056000, 70.00194000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65791', 'dr5hn-2026-07-29'),
  (65803, 'Taraz', 112, 147, 42.90000000, 71.36667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65803', 'dr5hn-2026-07-29'),
  (65839, 'Zhangatas', 112, 147, 43.56222000, 69.73428000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65839', 'dr5hn-2026-07-29'),
  (65594, 'Abay', 112, 150, 49.63575000, 72.86164000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65594', 'dr5hn-2026-07-29'),
  (65595, 'Abay Qalasy', 112, 150, 49.63333000, 72.88333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65595', 'dr5hn-2026-07-29'),
  (65601, 'Aksu-Ayuly', 112, 150, 48.76788000, 73.67272000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65601', 'dr5hn-2026-07-29'),
  (65602, 'Aktas', 112, 150, 49.77952000, 72.96128000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65602', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65603, 'Aktau', 112, 150, 48.03333000, 72.83333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65603', 'dr5hn-2026-07-29'),
  (65606, 'Aktogay', 112, 150, 48.16667000, 75.30000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65606', 'dr5hn-2026-07-29'),
  (65609, 'Aqadyr', 112, 150, 48.26014000, 72.85851000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65609', 'dr5hn-2026-07-29'),
  (65612, 'Aqshataū', 112, 150, 47.98917000, 74.05750000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65612', 'dr5hn-2026-07-29'),
  (65614, 'Aqtoghay Aūdany', 112, 150, 48.50000000, 74.75000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65614', 'dr5hn-2026-07-29'),
  (65623, 'Atasū', 112, 150, 48.68659000, 71.64469000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65623', 'dr5hn-2026-07-29'),
  (65634, 'Balqash', 112, 150, 46.84806000, 74.99500000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65634', 'dr5hn-2026-07-29'),
  (65653, 'Bukhar-Zhyrau', 112, 150, 49.85658000, 73.68118000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65653', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65666, 'Dolinka', 112, 150, 49.67685000, 72.67822000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65666', 'dr5hn-2026-07-29'),
  (65690, 'Karagandy', 112, 150, 49.80187000, 73.10211000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65690', 'dr5hn-2026-07-29'),
  (65711, 'Kīevka', 112, 150, 50.26212000, 71.54839000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65711', 'dr5hn-2026-07-29'),
  (65699, 'Koktal', 112, 150, 49.65000000, 73.51667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65699', 'dr5hn-2026-07-29'),
  (65707, 'Kushoky', 112, 150, 50.23091000, 73.40146000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65707', 'dr5hn-2026-07-29'),
  (65709, 'Kyzylzhar', 112, 150, 49.98197000, 72.60761000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65709', 'dr5hn-2026-07-29'),
  (65731, 'Moyynty', 112, 150, 47.22111000, 73.36694000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65731', 'dr5hn-2026-07-29'),
  (65735, 'Novodolinskiy', 112, 150, 49.70650000, 72.70807000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65735', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65741, 'Osakarovka', 112, 150, 50.56219000, 72.57089000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65741', 'dr5hn-2026-07-29'),
  (65748, 'Prigorodnoye', 112, 150, 49.69244000, 75.58438000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65748', 'dr5hn-2026-07-29'),
  (65750, 'Priozersk', 112, 150, 46.03106000, 73.70247000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65750', 'dr5hn-2026-07-29'),
  (65752, 'Qarazhal', 112, 150, 48.00627000, 70.79607000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65752', 'dr5hn-2026-07-29'),
  (65754, 'Qarqaraly', 112, 150, 49.41287000, 75.47286000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65754', 'dr5hn-2026-07-29'),
  (65768, 'Saryshaghan', 112, 150, 46.11917000, 73.61917000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65768', 'dr5hn-2026-07-29'),
  (65770, 'Sayaq', 112, 150, 47.00000000, 77.26667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65770', 'dr5hn-2026-07-29'),
  (65776, 'Shakhan', 112, 150, 49.81958000, 72.65407000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65776', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65777, 'Shakhtinsk', 112, 150, 49.70885000, 72.59212000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65777', 'dr5hn-2026-07-29'),
  (65783, 'Shashūbay', 112, 150, 46.81694000, 75.04028000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65783', 'dr5hn-2026-07-29'),
  (65789, 'Shubarköl', 112, 150, 48.88222000, 68.80722000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65789', 'dr5hn-2026-07-29'),
  (65794, 'Soran', 112, 150, 49.79080000, 72.83744000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65794', 'dr5hn-2026-07-29'),
  (65810, 'Temirtau', 112, 150, 50.05494000, 72.96464000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65810', 'dr5hn-2026-07-29'),
  (65814, 'Tokarevka', 112, 150, 50.11573000, 73.16034000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65814', 'dr5hn-2026-07-29'),
  (65825, 'Verkhniye Kayrakty', 112, 150, 48.68333000, 73.28333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65825', 'dr5hn-2026-07-29'),
  (65836, 'Zhambyl', 112, 150, 47.20694000, 71.39694000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65836', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65842, 'Zharyk', 112, 150, 48.85692000, 72.83598000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65842', 'dr5hn-2026-07-29'),
  (65846, 'Zhezqazghan', 112, 150, 47.78333000, 67.76667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65846', 'dr5hn-2026-07-29'),
  (65616, 'Arkalyk', 112, 157, 50.24915000, 66.92027000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65616', 'dr5hn-2026-07-29'),
  (65628, 'Ayat', 112, 157, 52.83554000, 62.52078000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65628', 'dr5hn-2026-07-29'),
  (65652, 'Borovskoy', 112, 157, 53.79270000, 64.18268000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65652', 'dr5hn-2026-07-29'),
  (65671, 'Dzhetygara', 112, 157, 52.19019000, 61.19894000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65671', 'dr5hn-2026-07-29'),
  (65679, 'Fyodorovka', 112, 157, 53.63809000, 62.69653000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65679', 'dr5hn-2026-07-29'),
  (65691, 'Karasu', 112, 157, 52.65995000, 65.48421000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65691', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65701, 'Komsomolets', 112, 157, 53.75019000, 62.05840000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65701', 'dr5hn-2026-07-29'),
  (65702, 'Kostanay', 112, 157, 53.21435000, 63.62463000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65702', 'dr5hn-2026-07-29'),
  (65716, 'Lisakovsk', 112, 157, 52.54707000, 62.49987000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65716', 'dr5hn-2026-07-29'),
  (65740, 'Ordzhonikidze', 112, 157, 52.44772000, 61.74942000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65740', 'dr5hn-2026-07-29'),
  (65755, 'Qashar', 112, 157, 53.36799000, 62.86839000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65755', 'dr5hn-2026-07-29'),
  (65760, 'Qusmuryn', 112, 157, 52.45107000, 64.61977000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65760', 'dr5hn-2026-07-29'),
  (65762, 'Rudnyy', 112, 157, 52.97290000, 63.11677000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65762', 'dr5hn-2026-07-29'),
  (65813, 'Tobol', 112, 157, 52.69366000, 62.59140000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65813', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65815, 'Torghay', 112, 157, 49.63389000, 63.49806000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65815', 'dr5hn-2026-07-29'),
  (65816, 'Troyebratskiy', 112, 157, 54.44306000, 66.07982000, 'Asia/Qostanay', NULL, NULL, 'city', 'dr5hn:65816', 'dr5hn-2026-07-29'),
  (65615, 'Aral', 112, 142, 46.80000000, 61.66667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65615', 'dr5hn-2026-07-29'),
  (65629, 'Ayteke Bi', 112, 142, 45.84607000, 62.15264000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65629', 'dr5hn-2026-07-29'),
  (65642, 'Belköl', 112, 142, 44.81162000, 65.58796000, 'Asia/Qyzylorda', NULL, NULL, 'city', 'dr5hn:65642', 'dr5hn-2026-07-29'),
  (65669, 'Dzhalagash', 112, 142, 45.08333000, 64.66667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65669', 'dr5hn-2026-07-29'),
  (65708, 'Kyzylorda', 112, 142, 44.85278000, 65.50917000, 'Asia/Qyzylorda', NULL, NULL, 'city', 'dr5hn:65708', 'dr5hn-2026-07-29'),
  (65757, 'Qazaly', 112, 142, 45.76278000, 62.10750000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65757', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65773, 'Sekseūil', 112, 142, 47.09000000, 61.15194000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65773', 'dr5hn-2026-07-29'),
  (65780, 'Shalqīya', 112, 142, 44.00947000, 67.41062000, 'Asia/Qyzylorda', NULL, NULL, 'city', 'dr5hn:65780', 'dr5hn-2026-07-29'),
  (65792, 'Shīeli', 112, 142, 44.16882000, 66.73887000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65792', 'dr5hn-2026-07-29'),
  (65804, 'Tasböget', 112, 142, 44.77384000, 65.55227000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65804', 'dr5hn-2026-07-29'),
  (65811, 'Terenozek', 112, 142, 45.05053000, 64.98395000, 'Asia/Qyzylorda', NULL, NULL, 'city', 'dr5hn:65811', 'dr5hn-2026-07-29'),
  (65827, 'Yanykurgan', 112, 142, 43.90652000, 67.24637000, 'Asia/Qyzylorda', NULL, NULL, 'city', 'dr5hn:65827', 'dr5hn-2026-07-29'),
  (65848, 'Zhosaly', 112, 142, 45.48778000, 64.07806000, 'Asia/Qyzylorda', NULL, NULL, 'city', 'dr5hn:65848', 'dr5hn-2026-07-29'),
  (65604, 'Aktau', 112, 141, 43.65000000, 51.16667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65604', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65641, 'Baūtīno', 112, 141, 44.54479000, 50.24629000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65641', 'dr5hn-2026-07-29'),
  (65648, 'Beyneu', 112, 141, 45.31667000, 55.20000000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65648', 'dr5hn-2026-07-29'),
  (65678, 'Fort-Shevchenko', 112, 141, 44.50654000, 50.26388000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65678', 'dr5hn-2026-07-29'),
  (65732, 'Munayshy', 112, 141, 43.49111000, 52.10861000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65732', 'dr5hn-2026-07-29'),
  (65851, 'Ömirzaq', 112, 141, 43.59786000, 51.24171000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65851', 'dr5hn-2026-07-29'),
  (65772, 'Sayötesh', 112, 141, 44.32781000, 53.53246000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65772', 'dr5hn-2026-07-29'),
  (65786, 'Shetpe', 112, 141, 44.16667000, 52.11667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65786', 'dr5hn-2026-07-29'),
  (65806, 'Taūshyq', 112, 141, 44.34678000, 51.34932000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65806', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65829, 'Yeraliyev', 112, 141, 43.18032000, 51.68116000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65829', 'dr5hn-2026-07-29'),
  (65837, 'Zhanaozen', 112, 141, 43.34116000, 52.86192000, 'Asia/Aqtau', NULL, NULL, 'city', 'dr5hn:65837', 'dr5hn-2026-07-29'),
  (65844, 'Zhetibay', 112, 141, 43.59417000, 52.07889000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65844', 'dr5hn-2026-07-29'),
  (65649, 'Birlestik', 112, 144, 53.58414000, 68.35382000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65649', 'dr5hn-2026-07-29'),
  (65650, 'Bishkul', 112, 144, 54.77763000, 69.09951000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65650', 'dr5hn-2026-07-29'),
  (65654, 'Bulayevo', 112, 144, 54.90596000, 70.44155000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65654', 'dr5hn-2026-07-29'),
  (65657, 'Būrabay', 112, 144, 53.08382000, 70.31379000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65657', 'dr5hn-2026-07-29'),
  (65710, 'Kzyltu', 112, 144, 53.63589000, 72.34079000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65710', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65736, 'Novoishimskiy', 112, 144, 53.19806000, 66.76944000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65736', 'dr5hn-2026-07-29'),
  (65747, 'Petropavl', 112, 144, 54.86667000, 69.15000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65747', 'dr5hn-2026-07-29'),
  (65775, 'Sergeyevka', 112, 144, 53.88139000, 67.40882000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65775', 'dr5hn-2026-07-29'),
  (65793, 'Smirnovo', 112, 144, 54.51480000, 69.42732000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65793', 'dr5hn-2026-07-29'),
  (65799, 'Taiynsha', 112, 144, 53.84796000, 69.76773000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65799', 'dr5hn-2026-07-29'),
  (65802, 'Talshik', 112, 144, 53.63736000, 71.87404000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65802', 'dr5hn-2026-07-29'),
  (65812, 'Timiryazevo', 112, 144, 53.74947000, 66.48852000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65812', 'dr5hn-2026-07-29'),
  (65826, 'Volodarskoye', 112, 144, 53.29270000, 68.10500000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65826', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65828, 'Yavlenka', 112, 144, 54.34525000, 68.45740000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65828', 'dr5hn-2026-07-29'),
  (65599, 'Aksu', 112, 146, 52.04023000, 76.92748000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65599', 'dr5hn-2026-07-29'),
  (65637, 'Bayanaul', 112, 146, 50.79304000, 75.70123000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65637', 'dr5hn-2026-07-29'),
  (65644, 'Belogor’ye', 112, 146, 51.52983000, 77.47146000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65644', 'dr5hn-2026-07-29'),
  (65673, 'Ekibastuz', 112, 146, 51.72371000, 75.32287000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65673', 'dr5hn-2026-07-29'),
  (65685, 'Irtyshsk', 112, 146, 53.33365000, 75.45775000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65685', 'dr5hn-2026-07-29'),
  (65686, 'Kalkaman', 112, 146, 51.95349000, 76.02723000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65686', 'dr5hn-2026-07-29'),
  (65713, 'Leninskiy', 112, 146, 52.25346000, 76.78211000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65713', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65727, 'Mayqayyng', 112, 146, 51.45981000, 75.80232000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65727', 'dr5hn-2026-07-29'),
  (65744, 'Pavlodar', 112, 146, 52.28333000, 76.96667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65744', 'dr5hn-2026-07-29'),
  (65756, 'Qashyr', 112, 146, 53.06649000, 76.10489000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65756', 'dr5hn-2026-07-29'),
  (65843, 'Zhelezinka', 112, 146, 53.53880000, 75.31326000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65843', 'dr5hn-2026-07-29'),
  (65617, 'Arys', 112, 149, 42.43015000, 68.80870000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65617', 'dr5hn-2026-07-29'),
  (65618, 'Ashchysay', 112, 149, 43.55370000, 68.89792000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65618', 'dr5hn-2026-07-29'),
  (65620, 'Asyqata', 112, 149, 40.89460000, 68.36430000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65620', 'dr5hn-2026-07-29'),
  (65622, 'Atakent', 112, 149, 40.84782000, 68.50643000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65622', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65640, 'Bayzhansay', 112, 149, 43.16708000, 69.91459000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65640', 'dr5hn-2026-07-29'),
  (65646, 'Belyye Vody', 112, 149, 42.42193000, 69.82709000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65646', 'dr5hn-2026-07-29'),
  (65659, 'Chardara', 112, 149, 41.25832000, 67.96991000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65659', 'dr5hn-2026-07-29'),
  (65660, 'Chayan', 112, 149, 43.03399000, 69.38048000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65660', 'dr5hn-2026-07-29'),
  (65664, 'Chulakkurgan', 112, 149, 43.76453000, 69.17856000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65664', 'dr5hn-2026-07-29'),
  (65688, 'Kantagi', 112, 149, 43.52786000, 68.58287000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65688', 'dr5hn-2026-07-29'),
  (65695, 'Kentau', 112, 149, 43.51672000, 68.50463000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65695', 'dr5hn-2026-07-29'),
  (65700, 'Kokterek', 112, 149, 42.49442000, 70.25478000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65700', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65712, 'Lenger', 112, 149, 42.18152000, 69.88582000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65712', 'dr5hn-2026-07-29'),
  (65714, 'Leninskoye', 112, 149, 41.75640000, 69.38390000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65714', 'dr5hn-2026-07-29'),
  (65724, 'Maqtaaral Aūdany', 112, 149, 40.75000000, 68.58333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65724', 'dr5hn-2026-07-29'),
  (65734, 'Myrzakent', 112, 149, 40.66338000, 68.54510000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65734', 'dr5hn-2026-07-29'),
  (65758, 'Qogham', 112, 149, 42.82774000, 68.28074000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65758', 'dr5hn-2026-07-29'),
  (65764, 'Saryaghash', 112, 149, 41.46042000, 69.16791000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65764', 'dr5hn-2026-07-29'),
  (65765, 'Saryaghash Aūdany', 112, 149, 41.66667000, 68.83333000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65765', 'dr5hn-2026-07-29'),
  (65769, 'Sastobe', 112, 149, 42.55330000, 69.99835000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65769', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65795, 'Sozaq Aūdany', 112, 149, 44.83333000, 68.50000000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65795', 'dr5hn-2026-07-29'),
  (65809, 'Temirlanovka', 112, 149, 42.59998000, 69.25836000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65809', 'dr5hn-2026-07-29'),
  (65817, 'Turar Ryskulov', 112, 149, 42.53340000, 70.34960000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65817', 'dr5hn-2026-07-29'),
  (65819, 'Turkestan', 112, 149, 43.29733000, 68.25175000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65819', 'dr5hn-2026-07-29'),
  (65820, 'Tyul’kubas', 112, 149, 42.48578000, 70.29601000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65820', 'dr5hn-2026-07-29'),
  (65834, 'Zhabagly', 112, 149, 42.43781000, 70.47841000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65834', 'dr5hn-2026-07-29'),
  (65611, 'Aqsay', 112, 148, 51.16810000, 52.99782000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65611', 'dr5hn-2026-07-29'),
  (65655, 'Burlin', 112, 148, 51.42724000, 52.71392000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65655', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65658, 'Chapaev', 112, 148, 50.20000000, 51.16667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65658', 'dr5hn-2026-07-29'),
  (65662, 'Chingirlau', 112, 148, 51.09878000, 54.08426000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65662', 'dr5hn-2026-07-29'),
  (65670, 'Dzhambeyty', 112, 148, 50.25676000, 52.59895000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65670', 'dr5hn-2026-07-29'),
  (65677, 'Fedorovka', 112, 148, 51.22102000, 51.95723000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65677', 'dr5hn-2026-07-29'),
  (65693, 'Kaztalovka', 112, 148, 49.76612000, 48.68903000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65693', 'dr5hn-2026-07-29'),
  (65704, 'Krūgloozernoe', 112, 148, 51.07854000, 51.28992000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65704', 'dr5hn-2026-07-29'),
  (65739, 'Oral', 112, 148, 51.23333000, 51.36667000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65739', 'dr5hn-2026-07-29'),
  (65745, 'Peremetnoe', 112, 148, 51.19925000, 50.85544000, 'Asia/Almaty', NULL, NULL, 'city', 'dr5hn:65745', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (65771, 'Saykhin', 112, 148, 48.85611000, 46.83361000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65771', 'dr5hn-2026-07-29'),
  (65805, 'Tasqala', 112, 148, 51.11073000, 50.29454000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65805', 'dr5hn-2026-07-29'),
  (65849, 'Zhänibek', 112, 148, 49.42207000, 46.84705000, 'Asia/Oral', NULL, NULL, 'city', 'dr5hn:65849', 'dr5hn-2026-07-29');
