-- Cities for MG (Madagascar): 9 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67377, 'Ampasimanolotra', 130, 2950, -18.81667000, 49.06667000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67377', 'dr5hn-2026-07-29'),
  (67378, 'Andovoranto', 130, 2950, -18.95443000, 49.10940000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67378', 'dr5hn-2026-07-29'),
  (67379, 'Mahanoro', 130, 2950, -19.90000000, 48.80000000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67379', 'dr5hn-2026-07-29'),
  (67380, 'Mahavelona', 130, 2950, -17.68475000, 49.50869000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67380', 'dr5hn-2026-07-29'),
  (67381, 'Marolambo', 130, 2950, -20.05000000, 48.11667000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67381', 'dr5hn-2026-07-29'),
  (67382, 'Toamasina', 130, 2950, -18.14920000, 49.40234000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67382', 'dr5hn-2026-07-29'),
  (67383, 'Toamasina I', 130, 2950, -18.13863000, 49.39203000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67383', 'dr5hn-2026-07-29'),
  (67384, 'Toamasina II', 130, 2950, -17.94053000, 49.14608000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67384', 'dr5hn-2026-07-29');
  (67385, 'Vohibinany', 130, 2950, -17.35000000, 49.03333000, 'Indian/Antananarivo', NULL, NULL, 'city', 'dr5hn:67385', 'dr5hn-2026-07-29');
