-- Cities for MM (Myanmar): 74 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 10 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67633, 'Bogale', 151, 2142, 16.29415000, 95.39742000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67633', 'dr5hn-2026-07-29'),
  (67639, 'Hinthada', 151, 2142, 17.64944000, 95.45705000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67639', 'dr5hn-2026-07-29'),
  (67646, 'Kyaiklat', 151, 2142, 16.44502000, 95.72373000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67646', 'dr5hn-2026-07-29'),
  (67656, 'Maubin', 151, 2142, 16.73148000, 95.65441000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67656', 'dr5hn-2026-07-29'),
  (67659, 'Mawlamyinegyunn', 151, 2142, 16.37720000, 95.26488000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67659', 'dr5hn-2026-07-29'),
  (67666, 'Myanaung', 151, 2142, 18.28651000, 95.32014000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67666', 'dr5hn-2026-07-29'),
  (67673, 'Nyaungdon', 151, 2142, 17.04459000, 95.63957000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67673', 'dr5hn-2026-07-29'),
  (67677, 'Pathein', 151, 2142, 16.77919000, 94.73212000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67677', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67680, 'Pyapon', 151, 2142, 16.28543000, 95.67882000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67680', 'dr5hn-2026-07-29'),
  (67701, 'Wakema', 151, 2142, 16.60333000, 95.18278000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67701', 'dr5hn-2026-07-29'),
  (67631, 'Bago', 151, 2141, 17.33521000, 96.48135000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67631', 'dr5hn-2026-07-29'),
  (67651, 'Letpandan', 151, 2141, 17.78664000, 95.75076000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67651', 'dr5hn-2026-07-29'),
  (67674, 'Nyaunglebin', 151, 2141, 17.95363000, 96.72247000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67674', 'dr5hn-2026-07-29'),
  (67678, 'Paungde', 151, 2141, 18.49167000, 95.50591000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67678', 'dr5hn-2026-07-29'),
  (67681, 'Pyay', 151, 2141, 18.82464000, 95.22216000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67681', 'dr5hn-2026-07-29'),
  (67684, 'Pyu', 151, 2141, 18.48130000, 96.43742000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67684', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67694, 'Taungoo', 151, 2141, 18.94291000, 96.43408000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67694', 'dr5hn-2026-07-29'),
  (67695, 'Thanatpin', 151, 2141, 17.29136000, 96.57523000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67695', 'dr5hn-2026-07-29'),
  (67696, 'Tharyarwady', 151, 2141, 17.65399000, 95.78813000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67696', 'dr5hn-2026-07-29'),
  (67637, 'Falam', 151, 2137, 22.91335000, 93.67779000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67637', 'dr5hn-2026-07-29'),
  (67638, 'Hakha', 151, 2137, 22.64452000, 93.61076000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67638', 'dr5hn-2026-07-29'),
  (67632, 'Bhamo', 151, 2143, 24.25256000, 97.23357000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67632', 'dr5hn-2026-07-29'),
  (67671, 'Myitkyina', 151, 2143, 25.38327000, 97.39637000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67671', 'dr5hn-2026-07-29'),
  (67652, 'Loikaw', 151, 2144, 19.67798000, 97.20975000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67652', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67636, 'Dellok', 151, 2133, 16.04072000, 97.91773000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67636', 'dr5hn-2026-07-29'),
  (67640, 'Hpa-An', 151, 2133, 16.88953000, 97.63482000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67640', 'dr5hn-2026-07-29'),
  (67644, 'Klonhtoug', 151, 2133, 15.95411000, 98.43250000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67644', 'dr5hn-2026-07-29'),
  (67648, 'Kyain Seikgyi Township', 151, 2133, 15.82288000, 98.25257000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67648', 'dr5hn-2026-07-29'),
  (67661, 'Mikenaungea', 151, 2133, 15.95846000, 98.42721000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67661', 'dr5hn-2026-07-29'),
  (67667, 'Myawadi', 151, 2133, 16.68911000, 98.50893000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67667', 'dr5hn-2026-07-29'),
  (67679, 'Pulei', 151, 2133, 16.06243000, 97.88280000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67679', 'dr5hn-2026-07-29'),
  (67690, 'Tagondaing', 151, 2133, 16.06750000, 97.90694000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67690', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67691, 'Tamoowoug', 151, 2133, 16.03447000, 97.91458000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67691', 'dr5hn-2026-07-29'),
  (67634, 'Chauk', 151, 2136, 20.89921000, 94.81784000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67634', 'dr5hn-2026-07-29'),
  (67653, 'Magway', 151, 2136, 20.14956000, 94.93246000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67653', 'dr5hn-2026-07-29'),
  (67662, 'Minbu', 151, 2136, 20.18059000, 94.87595000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67662', 'dr5hn-2026-07-29'),
  (67668, 'Myaydo', 151, 2136, 19.36838000, 95.21512000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67668', 'dr5hn-2026-07-29'),
  (67676, 'Pakokku', 151, 2136, 21.33489000, 95.08438000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67676', 'dr5hn-2026-07-29'),
  (67692, 'Taungdwingyi', 151, 2136, 20.00650000, 95.54531000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67692', 'dr5hn-2026-07-29'),
  (67698, 'Thayetmyo', 151, 2136, 19.32076000, 95.18272000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67698', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67704, 'Yenangyaung', 151, 2136, 20.46504000, 94.87120000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67704', 'dr5hn-2026-07-29'),
  (67649, 'Kyaukse', 151, 2134, 21.60560000, 96.13508000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67649', 'dr5hn-2026-07-29'),
  (67654, 'Mandalay', 151, 2134, 21.97473000, 96.08359000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67654', 'dr5hn-2026-07-29'),
  (67660, 'Meiktila', 151, 2134, 20.87776000, 95.85844000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67660', 'dr5hn-2026-07-29'),
  (67663, 'Mogok', 151, 2134, 22.91766000, 96.50982000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67663', 'dr5hn-2026-07-29'),
  (67670, 'Myingyan', 151, 2134, 21.46002000, 95.38840000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67670', 'dr5hn-2026-07-29'),
  (67675, 'Nyaungshwe', 151, 2134, 20.66084000, 96.93405000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67675', 'dr5hn-2026-07-29'),
  (67682, 'Pyin Oo Lwin', 151, 2134, 22.03501000, 96.45683000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67682', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67702, 'Yamethin', 151, 2134, 20.43189000, 96.13875000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67702', 'dr5hn-2026-07-29'),
  (67645, 'Kyaikkami', 151, 2147, 16.07686000, 97.56388000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67645', 'dr5hn-2026-07-29'),
  (67647, 'Kyaikto', 151, 2147, 17.30858000, 97.01124000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67647', 'dr5hn-2026-07-29'),
  (67655, 'Martaban', 151, 2147, 16.52834000, 97.61570000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67655', 'dr5hn-2026-07-29'),
  (67658, 'Mawlamyine', 151, 2147, 16.49051000, 97.62825000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67658', 'dr5hn-2026-07-29'),
  (67665, 'Mudon', 151, 2147, 16.25624000, 97.72460000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67665', 'dr5hn-2026-07-29'),
  (67697, 'Thaton', 151, 2147, 16.91867000, 97.37001000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67697', 'dr5hn-2026-07-29'),
  (67672, 'Nay Pyi Taw', 151, 2146, 19.74500000, 96.12972000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67672', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67683, 'Pyinmana', 151, 2146, 19.73810000, 96.20742000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67683', 'dr5hn-2026-07-29'),
  (67687, 'Sittwe', 151, 2138, 20.14624000, 92.89835000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67687', 'dr5hn-2026-07-29'),
  (67657, 'Mawlaik', 151, 2145, 23.64254000, 94.40478000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67657', 'dr5hn-2026-07-29'),
  (67664, 'Monywa', 151, 2145, 22.10856000, 95.13583000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67664', 'dr5hn-2026-07-29'),
  (67685, 'Sagaing', 151, 2145, 21.87870000, 95.97965000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67685', 'dr5hn-2026-07-29'),
  (67686, 'Shwebo', 151, 2145, 22.56925000, 95.69818000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67686', 'dr5hn-2026-07-29'),
  (67650, 'Lashio', 151, 2139, 22.93590000, 97.74980000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67650', 'dr5hn-2026-07-29'),
  (67689, 'Tachilek', 151, 2139, 20.44750000, 99.88083000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67689', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67693, 'Taunggyi', 151, 2139, 20.78919000, 97.03776000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67693', 'dr5hn-2026-07-29'),
  (67635, 'Dawei', 151, 2140, 14.08230000, 98.19151000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67635', 'dr5hn-2026-07-29'),
  (67642, 'Kawthoung', 151, 2140, 9.98238000, 98.55034000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67642', 'dr5hn-2026-07-29'),
  (67669, 'Myeik', 151, 2140, 12.43954000, 98.60028000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67669', 'dr5hn-2026-07-29'),
  (67641, 'Kanbe', 151, 2135, 16.70728000, 96.00168000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67641', 'dr5hn-2026-07-29'),
  (67643, 'Kayan', 151, 2135, 16.90802000, 96.56037000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67643', 'dr5hn-2026-07-29'),
  (67688, 'Syriam', 151, 2135, 16.76887000, 96.24503000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67688', 'dr5hn-2026-07-29'),
  (67699, 'Thongwa', 151, 2135, 16.75998000, 96.52498000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67699', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67700, 'Twante', 151, 2135, 16.71047000, 95.92866000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67700', 'dr5hn-2026-07-29'),
  (67703, 'Yangon', 151, 2135, 16.80528000, 96.15611000, 'Asia/Yangon', NULL, NULL, 'city', 'dr5hn:67703', 'dr5hn-2026-07-29');
