-- Cities for MU (Mauritius): 168 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 21 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67922, 'Vingt Cinq', 140, 3248, -10.38803000, 56.61795000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67922', 'dr5hn-2026-07-29'),
  (67826, 'Albion', 140, 3259, -20.20814000, 57.40766000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67826', 'dr5hn-2026-07-29'),
  (67830, 'Bambous', 140, 3259, -20.25667000, 57.40611000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67830', 'dr5hn-2026-07-29'),
  (153385, 'Black River', 140, 3259, -20.32047900, 57.40372500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153385', 'dr5hn-2026-07-29'),
  (67845, 'Cascavelle', 140, 3259, -20.28694000, 57.40722000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67845', 'dr5hn-2026-07-29'),
  (153383, 'Case Noyale', 140, 3259, -20.41370400, 57.36906500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153383', 'dr5hn-2026-07-29'),
  (153384, 'Chamarel', 140, 3259, -20.42523600, 57.39116500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153384', 'dr5hn-2026-07-29'),
  (67860, 'Flic en Flac', 140, 3259, -20.27417000, 57.36306000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67860', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67867, 'Grande Rivière Noire', 140, 3259, -20.36028000, 57.36611000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67867', 'dr5hn-2026-07-29'),
  (67869, 'Gros Cailloux', 140, 3259, -20.20722000, 57.43000000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67869', 'dr5hn-2026-07-29'),
  (153387, 'La Gaulette', 140, 3259, -20.42938800, 57.35884100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153387', 'dr5hn-2026-07-29'),
  (153388, 'Le Morne', 140, 3259, -20.44417400, 57.33031500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153388', 'dr5hn-2026-07-29'),
  (67888, 'Petite Case Noyale', 140, 3259, -20.39306000, 57.36500000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67888', 'dr5hn-2026-07-29'),
  (67889, 'Petite Rivière', 140, 3259, -20.19551000, 57.44592000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67889', 'dr5hn-2026-07-29'),
  (153389, 'Richelieu', 140, 3259, -20.19084900, 57.46129900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153389', 'dr5hn-2026-07-29'),
  (67916, 'Tamarin', 140, 3259, -20.32556000, 57.37056000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67916', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153436, 'Bel Air', 140, 3254, -20.25849300, 57.75498700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153436', 'dr5hn-2026-07-29'),
  (67834, 'Bel Air Rivière Sèche', 140, 3254, -20.25777000, 57.74976000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67834', 'dr5hn-2026-07-29'),
  (67836, 'Bon Accueil', 140, 3254, -20.17083000, 57.65639000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67836', 'dr5hn-2026-07-29'),
  (153443, 'Bramsthan', 140, 3254, -20.21297900, 57.73768000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153443', 'dr5hn-2026-07-29'),
  (67837, 'Brisée Verdière', 140, 3254, -20.16389000, 57.64667000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67837', 'dr5hn-2026-07-29'),
  (67842, 'Camp de Masque', 140, 3254, -20.23694000, 57.66333000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67842', 'dr5hn-2026-07-29'),
  (153437, 'Camp De Masque Pave', 140, 3254, -20.25006300, 57.67997000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153437', 'dr5hn-2026-07-29'),
  (67840, 'Camp Ithier', 140, 3254, -20.21583000, 57.74556000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67840', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67846, 'Centre de Flacq', 140, 3254, -20.18972000, 57.71444000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67846', 'dr5hn-2026-07-29'),
  (67850, 'Clémencia', 140, 3254, -20.26389000, 57.70611000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67850', 'dr5hn-2026-07-29'),
  (67858, 'Ecroignard', 140, 3254, -20.22611000, 57.73611000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67858', 'dr5hn-2026-07-29'),
  (153444, 'Grande Retraite', 140, 3254, -20.16507700, 57.69461600, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153444', 'dr5hn-2026-07-29'),
  (67868, 'Grande Rivière Sud Est', 140, 3254, -20.28611000, 57.77583000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67868', 'dr5hn-2026-07-29'),
  (67870, 'Lalmatie', 140, 3254, -20.18972000, 57.66111000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67870', 'dr5hn-2026-07-29'),
  (67871, 'Laventure', 140, 3254, -20.14583000, 57.67667000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67871', 'dr5hn-2026-07-29'),
  (67876, 'Mare La Chaux', 140, 3254, -20.19806000, 57.74944000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67876', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153441, 'Medine Camp De Masque', 140, 3254, -20.24395800, 57.64703500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153441', 'dr5hn-2026-07-29'),
  (67884, 'Olivia', 140, 3254, -20.28778000, 57.73097000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67884', 'dr5hn-2026-07-29'),
  (67897, 'Poste de Flacq', 140, 3254, -20.16306000, 57.73056000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67897', 'dr5hn-2026-07-29'),
  (67901, 'Quatre Cocos', 140, 3254, -20.20151000, 57.77448000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67901', 'dr5hn-2026-07-29'),
  (67902, 'Quatre Soeurs', 140, 3254, -20.29917000, 57.77056000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67902', 'dr5hn-2026-07-29'),
  (67903, 'Queen Victoria', 140, 3254, -20.22000000, 57.70750000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67903', 'dr5hn-2026-07-29'),
  (67911, 'Saint Julien', 140, 3254, -20.22639000, 57.63639000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67911', 'dr5hn-2026-07-29'),
  (67913, 'Sebastopol', 140, 3254, -20.29070000, 57.68779000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67913', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153442, 'Trou D''Eau Douce', 140, 3254, -20.23458600, 57.79486100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153442', 'dr5hn-2026-07-29'),
  (67831, 'Bambous Virieux', 140, 3264, -20.34278000, 57.75750000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67831', 'dr5hn-2026-07-29'),
  (67833, 'Beau Vallon', 140, 3264, -20.41889000, 57.69528000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67833', 'dr5hn-2026-07-29'),
  (67835, 'Bois des Amourettes', 140, 3264, -20.36306000, 57.73111000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67835', 'dr5hn-2026-07-29'),
  (153399, 'Camp Carol', 140, 3264, -20.46178500, 57.67845600, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153399', 'dr5hn-2026-07-29'),
  (67849, 'Cluny', 140, 3264, -20.36694000, 57.60389000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67849', 'dr5hn-2026-07-29'),
  (153400, 'Grand Bel Air', 140, 3264, -20.40912400, 57.68174200, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153400', 'dr5hn-2026-07-29'),
  (67866, 'Grand Sable', 140, 3264, -20.31417000, 57.76444000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67866', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67874, 'Mahébourg', 140, 3264, -20.40806000, 57.70000000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67874', 'dr5hn-2026-07-29'),
  (153391, 'Mare D''Albert', 140, 3264, -20.42019500, 57.62728800, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153391', 'dr5hn-2026-07-29'),
  (153392, 'Mare Tabac', 140, 3264, -20.44035800, 57.59421500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153392', 'dr5hn-2026-07-29'),
  (67881, 'New Grove', 140, 3264, -20.40861000, 57.61361000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67881', 'dr5hn-2026-07-29'),
  (67883, 'Nouvelle France', 140, 3264, -20.37056000, 57.56111000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67883', 'dr5hn-2026-07-29'),
  (153398, 'Petit Bel Air', 140, 3264, -20.39941200, 57.69295900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153398', 'dr5hn-2026-07-29'),
  (67891, 'Plaine Magnien', 140, 3264, -20.42967000, 57.66968000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67891', 'dr5hn-2026-07-29'),
  (153394, 'Riviere Des Creoles', 140, 3264, -20.39084000, 57.69696000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153394', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67908, 'Rose Belle', 140, 3264, -20.40028000, 57.59667000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67908', 'dr5hn-2026-07-29'),
  (67910, 'Saint Hubert', 140, 3264, -20.36417000, 57.63833000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67910', 'dr5hn-2026-07-29'),
  (153401, 'Seizieme Mille', 140, 3264, -20.34211100, 57.54924400, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153401', 'dr5hn-2026-07-29'),
  (153396, 'Trois Boutiques', 140, 3264, -20.45046100, 57.64682900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153396', 'dr5hn-2026-07-29'),
  (153397, 'Union Park', 140, 3264, -20.38629400, 57.58068000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153397', 'dr5hn-2026-07-29'),
  (153393, 'Vieux Grand Port', 140, 3264, -20.37406600, 57.71607700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153393', 'dr5hn-2026-07-29'),
  (67841, 'Camp Thorel', 140, 3253, -20.21472000, 57.61611000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67841', 'dr5hn-2026-07-29'),
  (67855, 'Dagotière', 140, 3253, -20.24476000, 57.56188000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67855', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67856, 'Dubreuil', 140, 3253, -20.30132000, 57.59861000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67856', 'dr5hn-2026-07-29'),
  (153448, 'L''Avenir', 140, 3253, -20.21714200, 57.55048200, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153448', 'dr5hn-2026-07-29'),
  (153447, 'L''Esperance', 140, 3253, -20.23041300, 57.59526800, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153447', 'dr5hn-2026-07-29'),
  (153449, 'La Laura-Malenga', 140, 3253, -20.20386100, 57.54991500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153449', 'dr5hn-2026-07-29'),
  (67877, 'Melrose', 140, 3253, -20.26972000, 57.63194000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67877', 'dr5hn-2026-07-29'),
  (67879, 'Moka', 140, 3253, -20.21889000, 57.49583000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67879', 'dr5hn-2026-07-29'),
  (153450, 'Montagne Blanche', 140, 3253, -20.28592000, 57.65774600, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153450', 'dr5hn-2026-07-29'),
  (153451, 'Nouvelle Découverte', 140, 3253, -20.18600000, 57.59079700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153451', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67885, 'Pailles', 140, 3253, -20.19271000, 57.48826000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67885', 'dr5hn-2026-07-29'),
  (67898, 'Providence', 140, 3253, -20.24472000, 57.61222000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67898', 'dr5hn-2026-07-29'),
  (67899, 'Quartier Militaire', 140, 3253, -20.24790000, 57.59737000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67899', 'dr5hn-2026-07-29'),
  (153452, 'Ripailles', 140, 3253, -20.19472500, 57.58059600, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153452', 'dr5hn-2026-07-29'),
  (153445, 'Saint Julien D''Hotman', 140, 3253, -20.23067000, 57.64037800, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153445', 'dr5hn-2026-07-29'),
  (67912, 'Saint Pierre', 140, 3253, -20.21750000, 57.52083000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67912', 'dr5hn-2026-07-29'),
  (67921, 'Verdun', 140, 3253, -20.23417000, 57.55476000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67921', 'dr5hn-2026-07-29'),
  (67828, 'Arsenal', 140, 3250, -20.10556000, 57.53528000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67828', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67838, 'Calebasses', 140, 3250, -20.11167000, 57.55389000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67838', 'dr5hn-2026-07-29'),
  (67851, 'Congomah', 140, 3250, -20.14889000, 57.59083000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67851', 'dr5hn-2026-07-29'),
  (67853, 'Crève Coeur', 140, 3250, -20.19111000, 57.55722000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67853', 'dr5hn-2026-07-29'),
  (153413, 'D''Epinay', 140, 3250, -20.13021100, 57.59583800, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153413', 'dr5hn-2026-07-29'),
  (67861, 'Fond du Sac', 140, 3250, -20.04732000, 57.58400000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67861', 'dr5hn-2026-07-29'),
  (67872, 'Le Hochet', 140, 3250, -20.13500000, 57.52111000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67872', 'dr5hn-2026-07-29'),
  (67873, 'Long Mountain', 140, 3250, -20.14306000, 57.56222000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67873', 'dr5hn-2026-07-29'),
  (67880, 'Morcellement Saint André', 140, 3250, -20.07199000, 57.56833000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67880', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67882, 'Notre Dame', 140, 3250, -20.14056000, 57.55306000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67882', 'dr5hn-2026-07-29'),
  (67886, 'Pamplemousses', 140, 3250, -20.10389000, 57.57028000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67886', 'dr5hn-2026-07-29'),
  (67892, 'Plaine des Papayes', 140, 3250, -20.06500000, 57.57250000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67892', 'dr5hn-2026-07-29'),
  (67894, 'Pointe aux Piments', 140, 3250, -20.06494000, 57.52347000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67894', 'dr5hn-2026-07-29'),
  (67917, 'Terre Rouge', 140, 3250, -20.12611000, 57.52444000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67917', 'dr5hn-2026-07-29'),
  (153416, 'Tombeau Bay', 140, 3250, -20.12345100, 57.50218400, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153416', 'dr5hn-2026-07-29'),
  (67919, 'Triolet', 140, 3250, -20.05760000, 57.55025000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67919', 'dr5hn-2026-07-29'),
  (153417, 'Trou Aux Biches', 140, 3250, -20.03123500, 57.55189700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153417', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153415, 'Ville Bague', 140, 3250, -20.14604500, 57.62414900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153415', 'dr5hn-2026-07-29'),
  (153454, 'Beau Bassin', 140, 3263, -20.22538700, 57.47145500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153454', 'dr5hn-2026-07-29'),
  (67832, 'Beau Bassin-Rose Hill', 140, 3263, -20.23325000, 57.46609000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67832', 'dr5hn-2026-07-29'),
  (153916, 'Belle Terre', 140, 3263, -20.26948370, 57.51655530, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153916', 'dr5hn-2026-07-29'),
  (153911, 'Camp Fouqueraux', 140, 3263, -20.28568630, 57.51718270, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153911', 'dr5hn-2026-07-29'),
  (153914, 'Chebel', 140, 3263, -20.21373190, 57.46075450, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153914', 'dr5hn-2026-07-29'),
  (153913, 'Coromandel', 140, 3263, -20.19522920, 57.44565340, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153913', 'dr5hn-2026-07-29'),
  (67854, 'Curepipe', 140, 3263, -20.31628000, 57.52594000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67854', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153456, 'Eau Coulee', 140, 3263, -20.30336600, 57.52778800, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153456', 'dr5hn-2026-07-29'),
  (67857, 'Ebene', 140, 3263, -20.24494000, 57.49163000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67857', 'dr5hn-2026-07-29'),
  (153455, 'Floreal', 140, 3263, -20.31121400, 57.50726300, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153455', 'dr5hn-2026-07-29'),
  (153457, 'Forest Side', 140, 3263, -20.32952100, 57.53898100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153457', 'dr5hn-2026-07-29'),
  (153912, 'Glen Park', 140, 3263, -20.32440680, 57.47531880, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153912', 'dr5hn-2026-07-29'),
  (153915, 'Henrietta', 140, 3263, -20.27200480, 57.52898870, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153915', 'dr5hn-2026-07-29'),
  (153918, 'Hermitage', 140, 3263, -20.27685080, 57.53471370, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153918', 'dr5hn-2026-07-29'),
  (153917, 'Highlands', 140, 3263, -20.27827480, 57.51350410, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153917', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67878, 'Midlands', 140, 3263, -20.31907000, 57.57016000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67878', 'dr5hn-2026-07-29'),
  (153910, 'Phoenix', 140, 3263, -20.28584460, 57.50291860, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153910', 'dr5hn-2026-07-29'),
  (67900, 'Quatre Bornes', 140, 3263, -20.26381000, 57.47910000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67900', 'dr5hn-2026-07-29'),
  (153453, 'Rose Hill', 140, 3263, -20.24347800, 57.46985500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153453', 'dr5hn-2026-07-29'),
  (67920, 'Vacoas', 140, 3263, -20.29806000, 57.47833000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67920', 'dr5hn-2026-07-29'),
  (153419, 'Bell Village', 140, 3260, -20.17049700, 57.48618400, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153419', 'dr5hn-2026-07-29'),
  (153423, 'Caudan Waterfront', 140, 3260, -20.16089880, 57.49772560, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153423', 'dr5hn-2026-07-29'),
  (153428, 'China Town', 140, 3260, -20.15879700, 57.50678900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153428', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153420, 'Les Pailles', 140, 3260, -20.19352700, 57.48962900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153420', 'dr5hn-2026-07-29'),
  (153424, 'Les Salines', 140, 3260, -20.16016800, 57.48904100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153424', 'dr5hn-2026-07-29'),
  (153426, 'Plaine Verte', 140, 3260, -20.15841000, 57.51421500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153426', 'dr5hn-2026-07-29'),
  (153418, 'Pointe aux Sables', 140, 3260, -20.17168700, 57.45389300, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153418', 'dr5hn-2026-07-29'),
  (67895, 'Port Louis', 140, 3260, -20.16194000, 57.49889000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67895', 'dr5hn-2026-07-29'),
  (153422, 'Soreze', 140, 3260, -20.20856100, 57.48638200, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153422', 'dr5hn-2026-07-29'),
  (153421, 'Tour Koenig', 140, 3260, -20.17864600, 57.46872100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153421', 'dr5hn-2026-07-29'),
  (153425, 'Tranquebar', 140, 3260, -20.17681600, 57.51132900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153425', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153429, 'Vallée des Prêtres', 140, 3260, -20.16514700, 57.53403900, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153429', 'dr5hn-2026-07-29'),
  (153427, 'Vallee Pitot', 140, 3260, -20.16920000, 57.51997000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153427', 'dr5hn-2026-07-29'),
  (67827, 'Amaury', 140, 3261, -20.13083000, 57.65917000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67827', 'dr5hn-2026-07-29'),
  (153434, 'Amitié Gokoola', 140, 3261, -20.10688300, 57.65472800, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153434', 'dr5hn-2026-07-29'),
  (67843, 'Cap Malheureux', 140, 3261, -19.98417000, 57.61417000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67843', 'dr5hn-2026-07-29'),
  (67852, 'Cottage', 140, 3261, -20.05972000, 57.62917000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67852', 'dr5hn-2026-07-29'),
  (67859, 'Espérance Trébuchet', 140, 3261, -20.06972000, 57.64194000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67859', 'dr5hn-2026-07-29'),
  (67862, 'Goodlands', 140, 3261, -20.03841000, 57.65055000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67862', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67863, 'Grand Baie', 140, 3261, -20.01816000, 57.58015000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67863', 'dr5hn-2026-07-29'),
  (67865, 'Grand Gaube', 140, 3261, -20.00639000, 57.66083000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67865', 'dr5hn-2026-07-29'),
  (67875, 'Mapou', 140, 3261, -20.07583000, 57.60139000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67875', 'dr5hn-2026-07-29'),
  (67887, 'Petit Raffray', 140, 3261, -20.02022000, 57.62296000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67887', 'dr5hn-2026-07-29'),
  (67890, 'Piton', 140, 3261, -20.09028000, 57.63028000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67890', 'dr5hn-2026-07-29'),
  (67893, 'Plaines des Roches', 140, 3261, -20.11167000, 57.69083000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67893', 'dr5hn-2026-07-29'),
  (153431, 'Poudre D''Or', 140, 3261, -20.06162700, 57.68297100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153431', 'dr5hn-2026-07-29'),
  (153432, 'Poudre D''Or Hamlet', 140, 3261, -20.08102400, 57.65272600, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153432', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67905, 'Rivière du Rempart', 140, 3261, -20.10306000, 57.68472000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67905', 'dr5hn-2026-07-29'),
  (67906, 'Roche Terre', 140, 3261, -20.01861000, 57.64472000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67906', 'dr5hn-2026-07-29'),
  (67907, 'Roches Noire', 140, 3261, -20.11111000, 57.71222000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67907', 'dr5hn-2026-07-29'),
  (67918, 'The Vale', 140, 3261, -20.03018000, 57.60219000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67918', 'dr5hn-2026-07-29'),
  (67829, 'Baie aux Huîtres', 140, 3249, -19.69444000, 63.40833000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67829', 'dr5hn-2026-07-29'),
  (67896, 'Port Mathurin', 140, 3249, -19.68333000, 63.41667000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67896', 'dr5hn-2026-07-29'),
  (67844, 'Cargados Carajos', 140, 3251, -16.60329000, 59.65851000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67844', 'dr5hn-2026-07-29'),
  (153402, 'Baie Du Cap', 140, 3257, -20.48664400, 57.37881500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153402', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153406, 'Bel Ombre', 140, 3257, -20.50191900, 57.42550700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153406', 'dr5hn-2026-07-29'),
  (153407, 'Benares', 140, 3257, -20.48440700, 57.58871700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153407', 'dr5hn-2026-07-29'),
  (153403, 'Bois Cheri', 140, 3257, -20.42667100, 57.53425200, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153403', 'dr5hn-2026-07-29'),
  (153408, 'Britannia', 140, 3257, -20.44865500, 57.56340700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153408', 'dr5hn-2026-07-29'),
  (67839, 'Camp Diable', 140, 3257, -20.46278000, 57.57889000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67839', 'dr5hn-2026-07-29'),
  (67847, 'Chamouny', 140, 3257, -20.48222000, 57.46611000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67847', 'dr5hn-2026-07-29'),
  (67848, 'Chemin Grenier', 140, 3257, -20.48722000, 57.46556000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67848', 'dr5hn-2026-07-29'),
  (67864, 'Grand Bois', 140, 3257, -20.41889000, 57.54417000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67864', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153409, 'L''Escalier', 140, 3257, -20.47333500, 57.61867600, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153409', 'dr5hn-2026-07-29'),
  (153411, 'La Flora', 140, 3257, -20.41000500, 57.56048700, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153411', 'dr5hn-2026-07-29'),
  (67904, 'Rivière des Anguilles', 140, 3257, -20.48528000, 57.55083000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67904', 'dr5hn-2026-07-29'),
  (153405, 'Rivière Du Poste', 140, 3257, -20.42866200, 57.57368100, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153405', 'dr5hn-2026-07-29'),
  (67909, 'Saint Aubin', 140, 3257, -20.49600000, 57.55000000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67909', 'dr5hn-2026-07-29'),
  (67914, 'Souillac', 140, 3257, -20.51667000, 57.51667000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67914', 'dr5hn-2026-07-29'),
  (153410, 'St Aubin', 140, 3257, -20.49444600, 57.55033500, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:153410', 'dr5hn-2026-07-29'),
  (67915, 'Surinam', 140, 3257, -20.50972000, 57.50528000, 'Indian/Mauritius', NULL, NULL, 'city', 'dr5hn:67915', 'dr5hn-2026-07-29');
