-- Cities for MV (Maldives): 21 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 3 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67929, 'Hithadhoo', 133, 2594, -0.60000000, 73.08333000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67929', 'dr5hn-2026-07-29'),
  (67937, 'Meedhoo', 133, 2594, -0.58333000, 73.23333000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67937', 'dr5hn-2026-07-29'),
  (67934, 'Mahibadhoo', 133, 2600, 3.75713000, 72.96893000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67934', 'dr5hn-2026-07-29'),
  (67931, 'Kudahuvadhoo', 133, 2590, 2.67075000, 72.89437000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67931', 'dr5hn-2026-07-29'),
  (67943, 'Viligili', 133, 2598, 0.75906000, 73.43296000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67943', 'dr5hn-2026-07-29'),
  (67940, 'Thinadhoo', 133, 2603, 0.53060000, 72.99969000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67940', 'dr5hn-2026-07-29'),
  (67927, 'Fuvahmulah', 133, 2595, -0.29878000, 73.42403000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67927', 'dr5hn-2026-07-29'),
  (67923, 'Dhidhdhoo', 133, 2586, 6.88744000, 73.11402000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67923', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67932, 'Kulhudhuffushi', 133, 2597, 6.62207000, 73.06998000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67932', 'dr5hn-2026-07-29'),
  (67928, 'Guraidhoo', 133, 2596, 3.90045000, 73.46623000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67928', 'dr5hn-2026-07-29'),
  (67930, 'Hulhumale', 133, 2596, 4.21169000, 73.54008000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67930', 'dr5hn-2026-07-29'),
  (67933, 'Maafushi', 133, 2596, 3.94231000, 73.49070000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67933', 'dr5hn-2026-07-29'),
  (67935, 'Male', 133, 2596, 4.17521000, 73.50916000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67935', 'dr5hn-2026-07-29'),
  (67925, 'Fonadhoo', 133, 2601, 1.83243000, 73.50257000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67925', 'dr5hn-2026-07-29'),
  (67939, 'Naifaru', 133, 2607, 5.44438000, 73.36571000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67939', 'dr5hn-2026-07-29'),
  (67938, 'Muli', 133, 2608, 2.91667000, 73.56667000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67938', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67936, 'Manadhoo', 133, 2592, 5.76687000, 73.41360000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67936', 'dr5hn-2026-07-29'),
  (67941, 'Ugoofaaru', 133, 2602, 5.66812000, 73.03017000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67941', 'dr5hn-2026-07-29'),
  (67926, 'Funadhoo', 133, 2585, 6.15091000, 73.29013000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67926', 'dr5hn-2026-07-29'),
  (67942, 'Veymandoo', 133, 2591, 2.18772000, 73.09556000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67942', 'dr5hn-2026-07-29'),
  (67924, 'Felidhoo', 133, 2584, 3.47182000, 73.54699000, 'Indian/Maldives', NULL, NULL, 'city', 'dr5hn:67924', 'dr5hn-2026-07-29');
