-- Cities for MW (Malawi): 61 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 8 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67950, 'Chipoka', 131, 3092, -13.99329000, 34.51566000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67950', 'dr5hn-2026-07-29'),
  (67955, 'Dedza', 131, 3092, -14.37790000, 34.33322000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67955', 'dr5hn-2026-07-29'),
  (67956, 'Dedza District', 131, 3092, -14.26273000, 34.18559000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67956', 'dr5hn-2026-07-29'),
  (67957, 'Dowa', 131, 3092, -13.65399000, 33.93754000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67957', 'dr5hn-2026-07-29'),
  (67958, 'Dowa District', 131, 3092, -13.60098000, 33.82378000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67958', 'dr5hn-2026-07-29'),
  (67961, 'Kasungu', 131, 3092, -13.03333000, 33.48333000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67961', 'dr5hn-2026-07-29'),
  (67962, 'Kasungu District', 131, 3092, -13.00000000, 33.41667000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67962', 'dr5hn-2026-07-29'),
  (67964, 'Lilongwe', 131, 3092, -13.96692000, 33.78725000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67964', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67965, 'Lilongwe District', 131, 3092, -14.01962000, 33.68407000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67965', 'dr5hn-2026-07-29'),
  (67973, 'Mchinji', 131, 3092, -13.79841000, 32.88019000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67973', 'dr5hn-2026-07-29'),
  (67974, 'Mchinji District', 131, 3092, -13.76230000, 33.07998000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67974', 'dr5hn-2026-07-29'),
  (67976, 'Mponela', 131, 3092, -13.53194000, 33.74008000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67976', 'dr5hn-2026-07-29'),
  (67987, 'Nkhotakota', 131, 3092, -12.92744000, 34.29614000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67987', 'dr5hn-2026-07-29'),
  (67988, 'Nkhotakota District', 131, 3092, -12.80417000, 34.08298000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67988', 'dr5hn-2026-07-29'),
  (67991, 'Ntcheu', 131, 3092, -14.82027000, 34.63586000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67991', 'dr5hn-2026-07-29'),
  (67992, 'Ntcheu District', 131, 3092, -14.75000000, 34.75000000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67992', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67993, 'Ntchisi', 131, 3092, -13.52775000, 33.91490000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67993', 'dr5hn-2026-07-29'),
  (67994, 'Ntchisi District', 131, 3092, -13.29574000, 33.90798000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67994', 'dr5hn-2026-07-29'),
  (67999, 'Salima', 131, 3092, -13.78040000, 34.45870000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67999', 'dr5hn-2026-07-29'),
  (68000, 'Salima District', 131, 3092, -13.71959000, 34.40184000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:68000', 'dr5hn-2026-07-29'),
  (67953, 'Chitipa', 131, 3105, -9.70237000, 33.26969000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67953', 'dr5hn-2026-07-29'),
  (67954, 'Chitipa District', 131, 3105, -9.92727000, 33.42541000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67954', 'dr5hn-2026-07-29'),
  (67959, 'Karonga', 131, 3105, -9.93333000, 33.93333000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67959', 'dr5hn-2026-07-29'),
  (67960, 'Karonga District', 131, 3105, -10.11153000, 33.88151000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67960', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67963, 'Likoma', 131, 3105, -12.06065000, 34.73608000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67963', 'dr5hn-2026-07-29'),
  (67966, 'Livingstonia', 131, 3105, -10.60602000, 34.10628000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67966', 'dr5hn-2026-07-29'),
  (67981, 'Mzimba', 131, 3105, -11.90000000, 33.60000000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67981', 'dr5hn-2026-07-29'),
  (67982, 'Mzimba District', 131, 3105, -11.85428000, 33.60778000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67982', 'dr5hn-2026-07-29'),
  (67983, 'Mzuzu', 131, 3105, -11.46556000, 34.02071000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67983', 'dr5hn-2026-07-29'),
  (67985, 'Nkhata Bay', 131, 3105, -11.60659000, 34.29073000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67985', 'dr5hn-2026-07-29'),
  (67986, 'Nkhata Bay District', 131, 3105, -11.65304000, 34.05322000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67986', 'dr5hn-2026-07-29'),
  (67997, 'Rumphi', 131, 3105, -11.01863000, 33.85746000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67997', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67998, 'Rumphi District', 131, 3105, -10.80292000, 33.80524000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67998', 'dr5hn-2026-07-29'),
  (67944, 'Balaka', 131, 3106, -14.97928000, 34.95575000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67944', 'dr5hn-2026-07-29'),
  (67945, 'Balaka District', 131, 3106, -15.04839000, 35.05910000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67945', 'dr5hn-2026-07-29'),
  (67946, 'Blantyre', 131, 3106, -15.78499000, 35.00854000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67946', 'dr5hn-2026-07-29'),
  (67947, 'Blantyre District', 131, 3106, -15.64732000, 34.93956000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67947', 'dr5hn-2026-07-29'),
  (67948, 'Chikwawa', 131, 3106, -16.03352000, 34.80091000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67948', 'dr5hn-2026-07-29'),
  (67949, 'Chikwawa District', 131, 3106, -16.16667000, 34.75000000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67949', 'dr5hn-2026-07-29'),
  (67951, 'Chiradzulu', 131, 3106, -15.67461000, 35.14071000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67951', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67952, 'Chiradzulu District', 131, 3106, -15.75268000, 35.21576000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67952', 'dr5hn-2026-07-29'),
  (67967, 'Liwonde', 131, 3106, -15.06665000, 35.22543000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67967', 'dr5hn-2026-07-29'),
  (67968, 'Luchenza', 131, 3106, -16.00693000, 35.30947000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67968', 'dr5hn-2026-07-29'),
  (67969, 'Machinga', 131, 3106, -15.16849000, 35.30002000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67969', 'dr5hn-2026-07-29'),
  (67970, 'Machinga District', 131, 3106, -14.94583000, 35.57367000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67970', 'dr5hn-2026-07-29'),
  (67971, 'Mangochi', 131, 3106, -14.47815000, 35.26448000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67971', 'dr5hn-2026-07-29'),
  (67972, 'Mangochi District', 131, 3106, -14.39296000, 35.34658000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67972', 'dr5hn-2026-07-29'),
  (67975, 'Monkey Bay', 131, 3106, -14.08239000, 34.91652000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67975', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67977, 'Mulanje', 131, 3106, -16.03163000, 35.50000000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67977', 'dr5hn-2026-07-29'),
  (67978, 'Mulanje District', 131, 3106, -15.93440000, 35.49990000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67978', 'dr5hn-2026-07-29'),
  (67979, 'Mwanza', 131, 3106, -15.60262000, 34.52479000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67979', 'dr5hn-2026-07-29'),
  (67980, 'Mwanza District', 131, 3106, -15.63337000, 34.51682000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67980', 'dr5hn-2026-07-29'),
  (67984, 'Neno', 131, 3106, -15.45051000, 34.70034000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67984', 'dr5hn-2026-07-29'),
  (67989, 'Nsanje', 131, 3106, -16.91995000, 35.26199000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67989', 'dr5hn-2026-07-29'),
  (67990, 'Nsanje District', 131, 3106, -16.75000000, 35.16667000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67990', 'dr5hn-2026-07-29'),
  (67995, 'Phalombe', 131, 3106, -15.80635000, 35.65067000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67995', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (67996, 'Phalombe District', 131, 3106, -15.66667000, 35.66667000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:67996', 'dr5hn-2026-07-29'),
  (68001, 'Thyolo', 131, 3106, -16.06775000, 35.14046000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:68001', 'dr5hn-2026-07-29'),
  (68002, 'Thyolo District', 131, 3106, -16.10583000, 35.15060000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:68002', 'dr5hn-2026-07-29'),
  (68003, 'Zomba', 131, 3106, -15.38596000, 35.31880000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:68003', 'dr5hn-2026-07-29'),
  (68004, 'Zomba District', 131, 3106, -15.43007000, 35.41829000, 'Africa/Blantyre', NULL, NULL, 'city', 'dr5hn:68004', 'dr5hn-2026-07-29');
