-- Cities for MY (Malaysia): 223 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 28 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76416, 'Bakri', 132, 1950, 2.04410000, 102.65270000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76416', 'dr5hn-2026-07-29'),
  (76424, 'Batu Pahat', 132, 1950, 1.85480000, 102.93250000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76424', 'dr5hn-2026-07-29'),
  (76433, 'Buloh Kasap', 132, 1950, 2.55360000, 102.76400000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76433', 'dr5hn-2026-07-29'),
  (76435, 'Chaah', 132, 1950, 2.24900000, 103.04800000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76435', 'dr5hn-2026-07-29'),
  (76437, 'Daerah Batu Pahat', 132, 1950, 1.93333000, 103.00000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76437', 'dr5hn-2026-07-29'),
  (76438, 'Daerah Johor Baharu', 132, 1950, 1.65000000, 103.60000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76438', 'dr5hn-2026-07-29'),
  (76439, 'Daerah Keluang', 132, 1950, 2.20000000, 103.33333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76439', 'dr5hn-2026-07-29'),
  (76440, 'Daerah Kota Tinggi', 132, 1950, 1.81667000, 103.96667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76440', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76441, 'Daerah Mersing', 132, 1950, 2.31667000, 103.71667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76441', 'dr5hn-2026-07-29'),
  (76442, 'Daerah Muar', 132, 1950, 2.25000000, 102.75000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76442', 'dr5hn-2026-07-29'),
  (76443, 'Daerah Pontian', 132, 1950, 1.50000000, 103.50000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76443', 'dr5hn-2026-07-29'),
  (76444, 'Daerah Segamat', 132, 1950, 2.60000000, 102.81667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76444', 'dr5hn-2026-07-29'),
  (76455, 'Johor Bahru', 132, 1950, 1.46550000, 103.75780000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76455', 'dr5hn-2026-07-29'),
  (76473, 'Kampung Pasir Gudang Baru', 132, 1950, 1.47260000, 103.87800000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76473', 'dr5hn-2026-07-29'),
  (76474, 'Kampung Simpang Renggam', 132, 1950, 1.82780000, 103.30000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76474', 'dr5hn-2026-07-29'),
  (76480, 'Kelapa Sawit', 132, 1950, 1.66980000, 103.53270000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76480', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76487, 'Kluang', 132, 1950, 2.03046000, 103.31689000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76487', 'dr5hn-2026-07-29'),
  (76491, 'Kota Tinggi', 132, 1950, 1.73810000, 103.89990000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76491', 'dr5hn-2026-07-29'),
  (76508, 'Kulai', 132, 1950, 1.65610000, 103.60320000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76508', 'dr5hn-2026-07-29'),
  (76510, 'Labis', 132, 1950, 2.38500000, 103.02100000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76510', 'dr5hn-2026-07-29'),
  (76524, 'Mersing', 132, 1950, 2.43120000, 103.84050000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76524', 'dr5hn-2026-07-29'),
  (76526, 'Muar', 132, 1950, 2.04420000, 102.56890000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76526', 'dr5hn-2026-07-29'),
  (76535, 'Parit Raja', 132, 1950, 1.86810000, 103.11240000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76535', 'dr5hn-2026-07-29'),
  (76538, 'Pekan Nenas', 132, 1950, 1.51000000, 103.51410000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76538', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76544, 'Pontian Kechil', 132, 1950, 1.48660000, 103.38960000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76544', 'dr5hn-2026-07-29'),
  (76556, 'Segamat', 132, 1950, 2.51480000, 102.81580000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76556', 'dr5hn-2026-07-29'),
  (76565, 'Skudai', 132, 1950, 1.53741000, 103.65779000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76565', 'dr5hn-2026-07-29'),
  (76573, 'Taman Senai', 132, 1950, 1.60060000, 103.64190000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76573', 'dr5hn-2026-07-29'),
  (76576, 'Tangkak', 132, 1950, 2.26730000, 102.54530000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76576', 'dr5hn-2026-07-29'),
  (76586, 'Ulu Tiram', 132, 1950, 1.60000000, 103.81667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76586', 'dr5hn-2026-07-29'),
  (76587, 'Yong Peng', 132, 1950, 2.01360000, 103.06590000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76587', 'dr5hn-2026-07-29'),
  (76410, 'Alor Setar', 132, 1947, 6.12104000, 100.36014000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76410', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76412, 'Ayer Hangat', 132, 1947, 6.42062000, 99.82199000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76412', 'dr5hn-2026-07-29'),
  (76426, 'Bedong', 132, 1947, 5.72743000, 100.50876000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76426', 'dr5hn-2026-07-29'),
  (76449, 'Gurun', 132, 1947, 5.81717000, 100.47381000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76449', 'dr5hn-2026-07-29'),
  (76454, 'Jitra', 132, 1947, 6.26812000, 100.42167000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76454', 'dr5hn-2026-07-29'),
  (76470, 'Kampung Kilim', 132, 1947, 6.40550000, 99.85020000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76470', 'dr5hn-2026-07-29'),
  (76471, 'Kampung Kok', 132, 1947, 6.36759000, 99.68252000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76471', 'dr5hn-2026-07-29'),
  (76492, 'Kuah', 132, 1947, 6.32649000, 99.84320000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76492', 'dr5hn-2026-07-29'),
  (76495, 'Kuala Kedah', 132, 1947, 6.10000000, 100.30000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76495', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76503, 'Kuala Teriang', 132, 1947, 6.36377000, 99.71532000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76503', 'dr5hn-2026-07-29'),
  (76509, 'Kulim', 132, 1947, 5.36499000, 100.56177000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76509', 'dr5hn-2026-07-29'),
  (76514, 'Langkawi', 132, 1947, 6.35608000, 99.78375000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76514', 'dr5hn-2026-07-29'),
  (76529, 'Padang Mat Sirat', 132, 1947, 6.35423000, 99.73404000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76529', 'dr5hn-2026-07-29'),
  (76569, 'Sungai Petani', 132, 1947, 5.64700000, 100.48772000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76569', 'dr5hn-2026-07-29'),
  (76448, 'Gua Musang', 132, 1946, 4.88441000, 101.96857000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76448', 'dr5hn-2026-07-29'),
  (76460, 'Kampong Kadok', 132, 1946, 6.00000000, 102.25000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76460', 'dr5hn-2026-07-29'),
  (76462, 'Kampong Pangkal Kalong', 132, 1946, 5.91667000, 102.21667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76462', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76489, 'Kota Bharu', 132, 1946, 6.12361000, 102.24333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76489', 'dr5hn-2026-07-29'),
  (76536, 'Pasir Mas', 132, 1946, 6.04934000, 102.13987000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76536', 'dr5hn-2026-07-29'),
  (76541, 'Peringat', 132, 1946, 6.03333000, 102.28333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76541', 'dr5hn-2026-07-29'),
  (76585, 'Tumpat', 132, 1946, 6.19775000, 102.17098000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76585', 'dr5hn-2026-07-29'),
  (76497, 'Kuala Lumpur', 132, 1949, 3.14120000, 101.68653000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76497', 'dr5hn-2026-07-29'),
  (76511, 'Labuan', 132, 1935, 5.28028000, 115.24750000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76511', 'dr5hn-2026-07-29'),
  (76409, 'Alor Gajah', 132, 1941, 2.38040000, 102.20890000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76409', 'dr5hn-2026-07-29'),
  (76421, 'Batu Berendam', 132, 1941, 2.24870000, 102.24600000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76421', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76427, 'Bemban', 132, 1941, 2.26840000, 102.37460000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76427', 'dr5hn-2026-07-29'),
  (76432, 'Bukit Rambai', 132, 1941, 2.25940000, 102.18380000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76432', 'dr5hn-2026-07-29'),
  (76461, 'Kampong Masjid Tanah', 132, 1941, 2.35000000, 102.11667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76461', 'dr5hn-2026-07-29'),
  (76463, 'Kampung Ayer Keroh', 132, 1941, 2.26540000, 102.28010000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76463', 'dr5hn-2026-07-29'),
  (76464, 'Kampung Ayer Molek', 132, 1941, 2.21390000, 102.32780000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76464', 'dr5hn-2026-07-29'),
  (76468, 'Kampung Bukit Baharu', 132, 1941, 2.21520000, 102.28510000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76468', 'dr5hn-2026-07-29'),
  (76486, 'Klebang Besar', 132, 1941, 2.21860000, 102.19950000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76486', 'dr5hn-2026-07-29'),
  (76501, 'Kuala Sungai Baru', 132, 1941, 2.35940000, 102.03530000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76501', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76520, 'Malacca', 132, 1941, 2.19600000, 102.24050000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76520', 'dr5hn-2026-07-29'),
  (76546, 'Pulau Sebang', 132, 1941, 2.45500000, 102.23290000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76546', 'dr5hn-2026-07-29'),
  (76570, 'Sungai Udang', 132, 1941, 2.26900000, 102.14270000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76570', 'dr5hn-2026-07-29'),
  (76415, 'Bahau', 132, 1948, 2.80790000, 102.40490000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76415', 'dr5hn-2026-07-29'),
  (76465, 'Kampung Baharu Nilai', 132, 1948, 2.80330000, 101.79720000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76465', 'dr5hn-2026-07-29'),
  (76499, 'Kuala Pilah', 132, 1948, 2.73890000, 102.24870000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76499', 'dr5hn-2026-07-29'),
  (76545, 'Port Dickson', 132, 1948, 2.53718000, 101.80571000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76545', 'dr5hn-2026-07-29'),
  (76559, 'Seremban', 132, 1948, 2.72970000, 101.93810000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76559', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76574, 'Tampin', 132, 1948, 2.47010000, 102.23020000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76574', 'dr5hn-2026-07-29'),
  (76428, 'Bentong Town', 132, 1940, 3.52229000, 101.90866000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76428', 'dr5hn-2026-07-29'),
  (76452, 'Jerantut', 132, 1940, 3.93600000, 102.36260000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76452', 'dr5hn-2026-07-29'),
  (76469, 'Kampung Bukit Tinggi Bentong', 132, 1940, 3.34944000, 101.82631000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76469', 'dr5hn-2026-07-29'),
  (76477, 'Kampung Tekek', 132, 1940, 2.81470000, 104.15920000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76477', 'dr5hn-2026-07-29'),
  (76496, 'Kuala Lipis', 132, 1940, 4.18420000, 102.04680000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76496', 'dr5hn-2026-07-29'),
  (76505, 'Kuantan', 132, 1940, 3.80770000, 103.32600000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76505', 'dr5hn-2026-07-29'),
  (76523, 'Mentekab', 132, 1940, 3.48540000, 102.34840000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76523', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76537, 'Pekan', 132, 1940, 3.48360000, 103.39960000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76537', 'dr5hn-2026-07-29'),
  (76551, 'Raub', 132, 1940, 3.78990000, 101.85700000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76551', 'dr5hn-2026-07-29'),
  (76575, 'Tanah Rata', 132, 1940, 4.46361000, 101.37630000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76575', 'dr5hn-2026-07-29'),
  (76584, 'Temerluh', 132, 1940, 3.45060000, 102.41760000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76584', 'dr5hn-2026-07-29'),
  (76422, 'Batu Feringgi', 132, 1939, 5.47090000, 100.24529000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76422', 'dr5hn-2026-07-29'),
  (76431, 'Bukit Mertajam', 132, 1939, 5.36301000, 100.46670000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76431', 'dr5hn-2026-07-29'),
  (76434, 'Butterworth', 132, 1939, 5.39910000, 100.36382000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76434', 'dr5hn-2026-07-29'),
  (76447, 'George Town', 132, 1939, 5.41123000, 100.33543000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76447', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76456, 'Juru', 132, 1939, 5.31201000, 100.44229000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76456', 'dr5hn-2026-07-29'),
  (76467, 'Kampung Batu Feringgi', 132, 1939, 5.46948000, 100.24449000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76467', 'dr5hn-2026-07-29'),
  (76475, 'Kampung Sungai Ara', 132, 1939, 5.32699000, 100.27348000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76475', 'dr5hn-2026-07-29'),
  (76482, 'Kepala Batas', 132, 1939, 5.51707000, 100.42650000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76482', 'dr5hn-2026-07-29'),
  (76528, 'Nibong Tebal', 132, 1939, 5.16586000, 100.47793000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76528', 'dr5hn-2026-07-29'),
  (76540, 'Perai', 132, 1939, 5.38333000, 100.38333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76540', 'dr5hn-2026-07-29'),
  (76542, 'Permatang Kuching', 132, 1939, 5.46339000, 100.38144000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76542', 'dr5hn-2026-07-29'),
  (76555, 'Seberang Perai', 132, 1939, 5.38770000, 100.42603000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76555', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76578, 'Tanjung Tokong', 132, 1939, 5.46061000, 100.30742000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76578', 'dr5hn-2026-07-29'),
  (76580, 'Tasek Glugor', 132, 1939, 5.48032000, 100.49849000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76580', 'dr5hn-2026-07-29'),
  (76582, 'Telaga Batu', 132, 1939, 5.46667000, 100.23333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76582', 'dr5hn-2026-07-29'),
  (76414, 'Bagan Serai', 132, 1943, 5.01080000, 100.54101000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76414', 'dr5hn-2026-07-29'),
  (76423, 'Batu Gajah', 132, 1943, 4.46916000, 101.04107000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76423', 'dr5hn-2026-07-29'),
  (76429, 'Bidur', 132, 1943, 4.11667000, 101.28333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76429', 'dr5hn-2026-07-29'),
  (76450, 'Ipoh', 132, 1943, 4.58410000, 101.08290000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76450', 'dr5hn-2026-07-29'),
  (76457, 'Kampar', 132, 1943, 4.30000000, 101.15000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76457', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76459, 'Kampong Dungun', 132, 1943, 3.21667000, 101.31667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76459', 'dr5hn-2026-07-29'),
  (76494, 'Kuala Kangsar', 132, 1943, 4.76667000, 100.93333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76494', 'dr5hn-2026-07-29'),
  (76519, 'Lumut', 132, 1943, 4.23230000, 100.62980000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76519', 'dr5hn-2026-07-29'),
  (76532, 'Pantai Remis', 132, 1943, 4.45570000, 100.62880000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76532', 'dr5hn-2026-07-29'),
  (76534, 'Parit Buntar', 132, 1943, 5.12671000, 100.49316000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76534', 'dr5hn-2026-07-29'),
  (76564, 'Simpang Empat', 132, 1943, 4.95000000, 100.63333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76564', 'dr5hn-2026-07-29'),
  (76571, 'Taiping', 132, 1943, 4.85000000, 100.73333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76571', 'dr5hn-2026-07-29'),
  (76579, 'Tapah Road', 132, 1943, 4.16667000, 101.20000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76579', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76583, 'Teluk Intan', 132, 1943, 4.02219000, 101.02083000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76583', 'dr5hn-2026-07-29'),
  (76478, 'Kangar', 132, 1938, 6.44140000, 100.19862000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76478', 'dr5hn-2026-07-29'),
  (76498, 'Kuala Perlis', 132, 1938, 6.40000000, 100.13333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76498', 'dr5hn-2026-07-29'),
  (76531, 'Pantai Cenang', 132, 1938, 6.29369000, 99.72786000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76531', 'dr5hn-2026-07-29'),
  (76549, 'Putrajaya', 132, 1945, 2.93527000, 101.69112000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76549', 'dr5hn-2026-07-29'),
  (76417, 'Bandar Labuan', 132, 1936, 5.28883000, 115.26924000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76417', 'dr5hn-2026-07-29'),
  (76425, 'Beaufort', 132, 1936, 5.34730000, 115.74550000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76425', 'dr5hn-2026-07-29'),
  (76446, 'Donggongon', 132, 1936, 5.90702000, 116.10146000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76446', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76481, 'Keningau', 132, 1936, 5.33780000, 116.16020000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76481', 'dr5hn-2026-07-29'),
  (76484, 'Kinarut', 132, 1936, 5.82310000, 116.04660000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76484', 'dr5hn-2026-07-29'),
  (76488, 'Kota Belud', 132, 1936, 6.35100000, 116.43050000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76488', 'dr5hn-2026-07-29'),
  (76490, 'Kota Kinabalu', 132, 1936, 5.97490000, 116.07240000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76490', 'dr5hn-2026-07-29'),
  (76507, 'Kudat', 132, 1936, 6.88732000, 116.82364000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76507', 'dr5hn-2026-07-29'),
  (76513, 'Lahad Datu', 132, 1936, 5.02298000, 118.32897000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76513', 'dr5hn-2026-07-29'),
  (76533, 'Papar', 132, 1936, 5.73333000, 115.93333000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76533', 'dr5hn-2026-07-29'),
  (76547, 'Putatan', 132, 1936, 5.92580000, 116.06094000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76547', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76550, 'Ranau', 132, 1936, 5.95380000, 116.66410000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76550', 'dr5hn-2026-07-29'),
  (76553, 'Sandakan', 132, 1936, 5.84020000, 118.11790000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76553', 'dr5hn-2026-07-29'),
  (76558, 'Semporna', 132, 1936, 4.48178000, 118.61119000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76558', 'dr5hn-2026-07-29'),
  (76572, 'Taman Rajawali', 132, 1936, 5.89477000, 118.04576000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76572', 'dr5hn-2026-07-29'),
  (76581, 'Tawau', 132, 1936, 4.24482000, 117.89115000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76581', 'dr5hn-2026-07-29'),
  (76430, 'Bintulu', 132, 1937, 3.16667000, 113.03333000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76430', 'dr5hn-2026-07-29'),
  (76445, 'Data Kakus', 132, 1937, 2.65465000, 113.62249000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76445', 'dr5hn-2026-07-29'),
  (76479, 'Kapit', 132, 1937, 1.99546000, 112.93254000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76479', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76506, 'Kuching', 132, 1937, 1.55000000, 110.33333000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76506', 'dr5hn-2026-07-29'),
  (76515, 'Lawas', 132, 1937, 4.86040000, 115.40900000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76515', 'dr5hn-2026-07-29'),
  (76516, 'Lidung Jelo', 132, 1937, 2.64848000, 114.78653000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76516', 'dr5hn-2026-07-29'),
  (76517, 'Limbang', 132, 1937, 4.75000000, 115.00000000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76517', 'dr5hn-2026-07-29'),
  (76518, 'Long Ampan Aing or Abanang', 132, 1937, 2.65671000, 114.73675000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76518', 'dr5hn-2026-07-29'),
  (76522, 'Marudi', 132, 1937, 4.18333000, 114.31667000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76522', 'dr5hn-2026-07-29'),
  (76525, 'Miri', 132, 1937, 4.39928000, 113.99163000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76525', 'dr5hn-2026-07-29'),
  (76527, 'Mukah', 132, 1937, 2.89435000, 112.09145000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76527', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76554, 'Sarikei', 132, 1937, 2.11667000, 111.51667000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76554', 'dr5hn-2026-07-29'),
  (76562, 'Sibu', 132, 1937, 2.30000000, 111.81667000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76562', 'dr5hn-2026-07-29'),
  (76563, 'Simanggang', 132, 1937, 1.24722000, 111.45278000, 'Asia/Kuching', NULL, NULL, 'city', 'dr5hn:76563', 'dr5hn-2026-07-29'),
  (76411, 'Ampang', 132, 1944, 3.15000000, 101.76667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76411', 'dr5hn-2026-07-29'),
  (161559, 'Ampang Jaya', 132, 1944, 3.15000000, 101.76667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161559', 'dr5hn-2026-07-29'),
  (161560, 'Assam Jawa', 132, 1944, 3.05000000, 101.65000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161560', 'dr5hn-2026-07-29'),
  (76413, 'Bagan Pulau Ketam', 132, 1944, 3.01667000, 101.26667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76413', 'dr5hn-2026-07-29'),
  (161561, 'Bandar Baru Selayang', 132, 1944, 3.26900000, 101.65000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161561', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161562, 'Bandar Kundang', 132, 1944, 3.25500000, 101.54700000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161562', 'dr5hn-2026-07-29'),
  (161563, 'Bangi', 132, 1944, 2.98000000, 101.78400000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161563', 'dr5hn-2026-07-29'),
  (76418, 'Banting', 132, 1944, 2.81360000, 101.50185000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76418', 'dr5hn-2026-07-29'),
  (76419, 'Batang Berjuntai', 132, 1944, 3.38333000, 101.41667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76419', 'dr5hn-2026-07-29'),
  (161564, 'Batang Kali', 132, 1944, 3.45870100, 101.65953100, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161564', 'dr5hn-2026-07-29'),
  (76420, 'Batu Arang', 132, 1944, 3.31667000, 101.46667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76420', 'dr5hn-2026-07-29'),
  (161565, 'Batu Caves', 132, 1944, 3.23788400, 101.68403800, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161565', 'dr5hn-2026-07-29'),
  (161566, 'Beranang', 132, 1944, 2.98400000, 101.81900000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161566', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161567, 'Bestari Jaya', 132, 1944, 3.37795300, 101.40623700, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161567', 'dr5hn-2026-07-29'),
  (161568, 'Broga', 132, 1944, 2.84000000, 101.93000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161568', 'dr5hn-2026-07-29'),
  (161569, 'Bukit Rotan', 132, 1944, 3.45000000, 101.25000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161569', 'dr5hn-2026-07-29'),
  (161570, 'Cyberjaya', 132, 1944, 2.92000000, 101.65000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161570', 'dr5hn-2026-07-29'),
  (161571, 'Gombak', 132, 1944, 3.27425000, 101.57072200, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161571', 'dr5hn-2026-07-29'),
  (161572, 'Jenjarom', 132, 1944, 2.83000000, 101.23000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161572', 'dr5hn-2026-07-29'),
  (76451, 'Jenjarum', 132, 1944, 2.87240000, 101.49484000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76451', 'dr5hn-2026-07-29'),
  (161573, 'Kajang', 132, 1944, 2.98330000, 101.78780000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161573', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76458, 'Kampong Baharu Balakong', 132, 1944, 3.03333000, 101.75000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76458', 'dr5hn-2026-07-29'),
  (76466, 'Kampung Baru Subang', 132, 1944, 3.15000000, 101.53333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76466', 'dr5hn-2026-07-29'),
  (161574, 'Kampung Kuantan', 132, 1944, 3.34500000, 101.25000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161574', 'dr5hn-2026-07-29'),
  (76476, 'Kampung Tanjung Karang', 132, 1944, 3.42420000, 101.18490000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76476', 'dr5hn-2026-07-29'),
  (161575, 'Kapar', 132, 1944, 3.10000000, 101.42000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161575', 'dr5hn-2026-07-29'),
  (76485, 'Klang', 132, 1944, 3.03667000, 101.44333000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76485', 'dr5hn-2026-07-29'),
  (161576, 'Kuala Kubu Bharu', 132, 1944, 3.56093200, 101.65854600, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161576', 'dr5hn-2026-07-29'),
  (76500, 'Kuala Selangor', 132, 1944, 3.35000000, 101.25000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76500', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161577, 'Kuala Sungai Buloh', 132, 1944, 3.22000000, 101.57000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161577', 'dr5hn-2026-07-29'),
  (76504, 'Kuang', 132, 1944, 3.25940000, 101.55410000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76504', 'dr5hn-2026-07-29'),
  (76512, 'Ladang Seri Kundang', 132, 1944, 3.28560000, 101.51900000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76512', 'dr5hn-2026-07-29'),
  (161578, 'Lagong', 132, 1944, 3.15000000, 101.40000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161578', 'dr5hn-2026-07-29'),
  (161579, 'Meru', 132, 1944, 3.08000000, 101.45000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161579', 'dr5hn-2026-07-29'),
  (161580, 'Mutiara Damansara', 132, 1944, 3.18000000, 101.62000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161580', 'dr5hn-2026-07-29'),
  (161581, 'Padang Jawa', 132, 1944, 3.03000000, 101.58000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161581', 'dr5hn-2026-07-29'),
  (161582, 'Pandamaran', 132, 1944, 3.01000000, 101.42000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161582', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161583, 'Paya Jaras', 132, 1944, 3.17000000, 101.61000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161583', 'dr5hn-2026-07-29'),
  (76539, 'Pelabuhan Klang', 132, 1944, 2.99959000, 101.39287000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76539', 'dr5hn-2026-07-29'),
  (76543, 'Petaling Jaya', 132, 1944, 3.10726000, 101.60671000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76543', 'dr5hn-2026-07-29'),
  (161584, 'Port Klang', 132, 1944, 3.00507000, 101.40887000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161584', 'dr5hn-2026-07-29'),
  (153725, 'Puchong', 132, 1944, 3.03270000, 101.61880000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:153725', 'dr5hn-2026-07-29'),
  (76548, 'Putra Heights', 132, 1944, 2.99361000, 101.57255000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76548', 'dr5hn-2026-07-29'),
  (76552, 'Rawang', 132, 1944, 3.32130000, 101.57670000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76552', 'dr5hn-2026-07-29'),
  (161585, 'Sabak', 132, 1944, 3.77000000, 100.99000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161585', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161586, 'Salak Tinggi', 132, 1944, 2.77000000, 101.70000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161586', 'dr5hn-2026-07-29'),
  (161587, 'Sekinchan', 132, 1944, 3.50400000, 101.10300000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161587', 'dr5hn-2026-07-29'),
  (161588, 'Selayang', 132, 1944, 3.25000000, 101.65000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161588', 'dr5hn-2026-07-29'),
  (76557, 'Semenyih', 132, 1944, 2.95160000, 101.84300000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76557', 'dr5hn-2026-07-29'),
  (161589, 'Sepang', 132, 1944, 2.70000000, 101.70000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161589', 'dr5hn-2026-07-29'),
  (76560, 'Serendah', 132, 1944, 3.36460000, 101.60410000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76560', 'dr5hn-2026-07-29'),
  (161590, 'Seri Kembangan', 132, 1944, 3.03700000, 101.69500000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161590', 'dr5hn-2026-07-29'),
  (76561, 'Shah Alam', 132, 1944, 3.08507000, 101.53281000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76561', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76566, 'Subang Jaya', 132, 1944, 3.04384000, 101.58062000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76566', 'dr5hn-2026-07-29'),
  (161591, 'Sungai Air Tawar', 132, 1944, 3.68000000, 101.14000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161591', 'dr5hn-2026-07-29'),
  (76567, 'Sungai Besar', 132, 1944, 3.67460000, 100.98670000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76567', 'dr5hn-2026-07-29'),
  (161592, 'Sungai Buaya', 132, 1944, 3.36000000, 101.62000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161592', 'dr5hn-2026-07-29'),
  (161593, 'Sungai Burong', 132, 1944, 3.45000000, 101.23000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161593', 'dr5hn-2026-07-29'),
  (161594, 'Sungai Choh', 132, 1944, 3.25000000, 101.65000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161594', 'dr5hn-2026-07-29'),
  (161595, 'Sungai Pelek', 132, 1944, 2.65000000, 101.70000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161595', 'dr5hn-2026-07-29'),
  (76568, 'Sungai Pelek New Village', 132, 1944, 2.65000000, 101.70000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76568', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (161596, 'Sungai Pelong', 132, 1944, 3.45000000, 101.20000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161596', 'dr5hn-2026-07-29'),
  (161597, 'Sungai Tengi', 132, 1944, 3.28000000, 101.47000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161597', 'dr5hn-2026-07-29'),
  (161598, 'Taman Melawati', 132, 1944, 3.27000000, 101.74000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161598', 'dr5hn-2026-07-29'),
  (161599, 'Taman Tasik Semenyih', 132, 1944, 2.95000000, 101.84000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161599', 'dr5hn-2026-07-29'),
  (76577, 'Tanjung Sepat', 132, 1944, 2.65790000, 101.56290000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76577', 'dr5hn-2026-07-29'),
  (161600, 'Teluk Datok', 132, 1944, 3.00000000, 101.39000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161600', 'dr5hn-2026-07-29'),
  (161601, 'Ulu Yam', 132, 1944, 3.40000000, 101.55000000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:161601', 'dr5hn-2026-07-29'),
  (76436, 'Cukai', 132, 1942, 4.25000000, 103.41667000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76436', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76453, 'Jertih', 132, 1942, 5.73360000, 102.48970000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76453', 'dr5hn-2026-07-29'),
  (76472, 'Kampung Kuala Besut', 132, 1942, 5.83297000, 102.55061000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76472', 'dr5hn-2026-07-29'),
  (76483, 'Kertih', 132, 1942, 4.51410000, 103.44830000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76483', 'dr5hn-2026-07-29'),
  (76493, 'Kuala Besut', 132, 1942, 5.83303000, 102.55514000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76493', 'dr5hn-2026-07-29'),
  (76502, 'Kuala Terengganu', 132, 1942, 5.33020000, 103.14080000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76502', 'dr5hn-2026-07-29'),
  (76521, 'Marang', 132, 1942, 5.20560000, 103.20590000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76521', 'dr5hn-2026-07-29'),
  (76530, 'Paka', 132, 1942, 4.63740000, 103.43680000, 'Asia/Kuala_Lumpur', NULL, NULL, 'city', 'dr5hn:76530', 'dr5hn-2026-07-29');
