-- Cities for NA (Namibia): 48 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 6 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76626, 'Arandis', 152, 43, -22.41667000, 14.96667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76626', 'dr5hn-2026-07-29'),
  (76633, 'Hentiesbaai', 152, 43, -22.11667000, 14.28333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76633', 'dr5hn-2026-07-29'),
  (76636, 'Karibib', 152, 43, -21.93333000, 15.83333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76636', 'dr5hn-2026-07-29'),
  (76648, 'Omaruru', 152, 43, -21.43333000, 15.93333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76648', 'dr5hn-2026-07-29'),
  (76659, 'Otjimbingwe', 152, 43, -22.35000000, 16.13333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76659', 'dr5hn-2026-07-29'),
  (76666, 'Swakopmund', 152, 43, -22.67842000, 14.52663000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76666', 'dr5hn-2026-07-29'),
  (76667, 'Swakopmund Constituency', 152, 43, -22.63199000, 14.60119000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76667', 'dr5hn-2026-07-29'),
  (76670, 'Usakos', 152, 43, -22.00000000, 15.60000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76670', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76671, 'Walvis Bay', 152, 43, -22.95750000, 14.50528000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76671', 'dr5hn-2026-07-29'),
  (76627, 'Aranos', 152, 38, -24.13333000, 19.11667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76627', 'dr5hn-2026-07-29'),
  (76634, 'Hoachanas', 152, 38, -23.91667000, 18.05000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76634', 'dr5hn-2026-07-29'),
  (76643, 'Maltahöhe', 152, 38, -24.83333000, 16.98333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76643', 'dr5hn-2026-07-29'),
  (76644, 'Mariental', 152, 38, -24.63333000, 17.96667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76644', 'dr5hn-2026-07-29'),
  (76663, 'Rehoboth', 152, 38, -23.31700000, 17.09000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76663', 'dr5hn-2026-07-29'),
  (76629, 'Bethanie', 152, 45, -26.48333000, 17.15000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76629', 'dr5hn-2026-07-29'),
  (76635, 'Karasburg', 152, 45, -28.01667000, 18.75000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76635', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76639, 'Keetmanshoop', 152, 45, -26.58333000, 18.13333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76639', 'dr5hn-2026-07-29'),
  (76642, 'Lüderitz', 152, 45, -26.64807000, 15.15383000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76642', 'dr5hn-2026-07-29'),
  (76655, 'Oranjemund', 152, 45, -28.55000000, 16.43333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76655', 'dr5hn-2026-07-29'),
  (76668, 'Tses', 152, 45, -25.88333000, 18.00000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76668', 'dr5hn-2026-07-29'),
  (76672, 'Warmbad', 152, 45, -28.45000000, 18.73333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76672', 'dr5hn-2026-07-29'),
  (76664, 'Rundu', 152, 36, -17.93333000, 19.76667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76664', 'dr5hn-2026-07-29'),
  (76638, 'Katutura', 152, 44, -22.52306000, 17.06028000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76638', 'dr5hn-2026-07-29'),
  (76673, 'Windhoek', 152, 44, -22.55941000, 17.08323000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76673', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76630, 'Epupa Constituency', 152, 34, -17.00388000, 13.24825000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76630', 'dr5hn-2026-07-29'),
  (76640, 'Khorixas', 152, 34, -20.36667000, 14.96667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76640', 'dr5hn-2026-07-29'),
  (76641, 'Khorixas Constituency', 152, 34, -20.36792000, 14.95996000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76641', 'dr5hn-2026-07-29'),
  (76653, 'Opuwo', 152, 34, -18.06068000, 13.83998000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76653', 'dr5hn-2026-07-29'),
  (76654, 'Opuwo Constituency', 152, 34, -18.54247000, 13.51617000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76654', 'dr5hn-2026-07-29'),
  (76662, 'Outjo', 152, 34, -20.11667000, 16.15000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76662', 'dr5hn-2026-07-29'),
  (76665, 'Sesfontein Constituency', 152, 34, -19.56106000, 13.76530000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76665', 'dr5hn-2026-07-29'),
  (76657, 'Oshikango', 152, 40, -17.40000000, 15.88333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76657', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76631, 'Gobabis', 152, 41, -22.45000000, 18.96667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76631', 'dr5hn-2026-07-29'),
  (76646, 'Okahao', 152, 39, -17.88758000, 15.06677000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76646', 'dr5hn-2026-07-29'),
  (76651, 'Ongandjera', 152, 39, -17.88333000, 15.06667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76651', 'dr5hn-2026-07-29'),
  (76661, 'Outapi', 152, 39, -17.50000000, 14.98333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76661', 'dr5hn-2026-07-29'),
  (76650, 'Ondangwa', 152, 37, -17.91667000, 15.95000000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76650', 'dr5hn-2026-07-29'),
  (76652, 'Ongwediva', 152, 37, -17.78333000, 15.76667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76652', 'dr5hn-2026-07-29'),
  (76656, 'Oshakati', 152, 37, -17.78833000, 15.70436000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76656', 'dr5hn-2026-07-29'),
  (76649, 'Omuthiya', 152, 42, -18.36463000, 16.58146000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76649', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (76669, 'Tsumeb', 152, 42, -19.23333000, 17.71667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76669', 'dr5hn-2026-07-29'),
  (76632, 'Grootfontein', 152, 46, -19.56667000, 18.11667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76632', 'dr5hn-2026-07-29'),
  (76645, 'Okahandja', 152, 46, -21.98333000, 16.91667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76645', 'dr5hn-2026-07-29'),
  (76647, 'Okakarara', 152, 46, -20.58333000, 17.43333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76647', 'dr5hn-2026-07-29'),
  (76658, 'Otavi', 152, 46, -19.65000000, 17.33333000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76658', 'dr5hn-2026-07-29'),
  (76660, 'Otjiwarongo', 152, 46, -20.46369000, 16.64772000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76660', 'dr5hn-2026-07-29'),
  (76628, 'Bagani', 152, 47, -18.11065000, 21.61645000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76628', 'dr5hn-2026-07-29'),
  (76637, 'Katima Mulilo', 152, 47, -17.50000000, 24.26667000, 'Africa/Windhoek', NULL, NULL, 'city', 'dr5hn:76637', 'dr5hn-2026-07-29');
