-- Cities for NR (Nauru): 7 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79762, 'Arijejen', 153, 4656, -0.52545000, 166.91247000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79762', 'dr5hn-2026-07-29'),
  (79761, 'Anabar', 153, 4658, -0.50845000, 166.95326000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79761', 'dr5hn-2026-07-29'),
  (79763, 'Baiti', 153, 4660, -0.50803000, 166.92945000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79763', 'dr5hn-2026-07-29'),
  (79764, 'Ijuw', 153, 4661, -0.52100000, 166.95813000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79764', 'dr5hn-2026-07-29'),
  (79765, 'Menen', 153, 4657, -0.54539000, 166.94871000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79765', 'dr5hn-2026-07-29'),
  (79766, 'Uaboe', 153, 4655, -0.51393000, 166.92384000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79766', 'dr5hn-2026-07-29'),
  (79767, 'Yaren', 153, 4664, -0.55085000, 166.92520000, 'Pacific/Nauru', NULL, NULL, 'city', 'dr5hn:79767', 'dr5hn-2026-07-29');
