-- Cities for PA (Panama): 551 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 69 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79962, 'Almirante', 170, 1393, 9.30091000, -82.40180000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79962', 'dr5hn-2026-07-29'),
  (79982, 'Barranco', 170, 1393, 9.51984000, -82.70424000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79982', 'dr5hn-2026-07-29'),
  (79983, 'Barranco Adentro', 170, 1393, 9.52757000, -82.73344000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79983', 'dr5hn-2026-07-29'),
  (79986, 'Bastimentos', 170, 1393, 9.34707000, -82.20880000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79986', 'dr5hn-2026-07-29'),
  (80000, 'Bocas del Toro', 170, 1393, 9.34031000, -82.24204000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80000', 'dr5hn-2026-07-29'),
  (80036, 'Cauchero', 170, 1393, 9.15226000, -82.26450000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80036', 'dr5hn-2026-07-29'),
  (80054, 'Changuinola', 170, 1393, 9.43000000, -82.52000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80054', 'dr5hn-2026-07-29'),
  (80063, 'Chiriquí Grande', 170, 1393, 8.94557000, -82.11769000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80063', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80084, 'Distrito Chiriquí Grande', 170, 1393, 8.94748000, -82.12418000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80084', 'dr5hn-2026-07-29'),
  (80092, 'Distrito de Bocas del Toro', 170, 1393, 9.36235000, -82.26288000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80092', 'dr5hn-2026-07-29'),
  (80101, 'Distrito de Changuinola', 170, 1393, 9.25000000, -82.63333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80101', 'dr5hn-2026-07-29'),
  (80170, 'El Empalme', 170, 1393, 9.41667000, -82.51667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80170', 'dr5hn-2026-07-29'),
  (80202, 'El Silencio', 170, 1393, 9.37222000, -82.52877000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80202', 'dr5hn-2026-07-29'),
  (80217, 'Guabito', 170, 1393, 9.48968000, -82.61279000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80217', 'dr5hn-2026-07-29'),
  (80235, 'Isla Bastimentos', 170, 1393, 9.30000000, -82.13333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80235', 'dr5hn-2026-07-29'),
  (80354, 'Miramar', 170, 1393, 8.99482000, -82.24147000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80354', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80437, 'Punta Laurel', 170, 1393, 9.14100000, -82.12717000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80437', 'dr5hn-2026-07-29'),
  (80438, 'Punta Peña', 170, 1393, 8.91659000, -82.18488000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80438', 'dr5hn-2026-07-29'),
  (80439, 'Punta Róbalo', 170, 1393, 9.03631000, -82.24952000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80439', 'dr5hn-2026-07-29'),
  (80537, 'Valle del Risco', 170, 1393, 9.23064000, -82.42748000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80537', 'dr5hn-2026-07-29'),
  (79959, 'Alanje', 170, 1397, 8.39791000, -82.55947000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79959', 'dr5hn-2026-07-29'),
  (79961, 'Algarrobos Arriba', 170, 1397, 8.51550000, -82.42263000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79961', 'dr5hn-2026-07-29'),
  (79963, 'Alto Boquete', 170, 1397, 8.73458000, -82.43213000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79963', 'dr5hn-2026-07-29'),
  (79974, 'Aserrío de Gariché', 170, 1397, 8.48257000, -82.79086000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79974', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80012, 'Bágala', 170, 1397, 8.46399000, -82.52617000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80012', 'dr5hn-2026-07-29'),
  (79979, 'Bajo Boquete', 170, 1397, 8.77058000, -82.43306000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79979', 'dr5hn-2026-07-29'),
  (79985, 'Barrio Guadalupe', 170, 1397, 8.86482000, -82.56523000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79985', 'dr5hn-2026-07-29'),
  (79992, 'Bijagual', 170, 1397, 8.51486000, -82.33361000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79992', 'dr5hn-2026-07-29'),
  (79995, 'Boca Chica', 170, 1397, 8.21911000, -82.21592000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79995', 'dr5hn-2026-07-29'),
  (79999, 'Boca del Monte', 170, 1397, 8.35296000, -82.11379000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79999', 'dr5hn-2026-07-29'),
  (80001, 'Boquerón', 170, 1397, 8.50510000, -82.57025000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80001', 'dr5hn-2026-07-29'),
  (80003, 'Boquete', 170, 1397, 8.78024000, -82.44136000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80003', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80005, 'Breñón', 170, 1397, 8.62491000, -82.81277000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80005', 'dr5hn-2026-07-29'),
  (80010, 'Bugaba', 170, 1397, 8.48255000, -82.61991000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80010', 'dr5hn-2026-07-29'),
  (80011, 'Bugabita Arriba', 170, 1397, 8.52143000, -82.63638000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80011', 'dr5hn-2026-07-29'),
  (80019, 'Caimito', 170, 1397, 8.54162000, -82.41900000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80019', 'dr5hn-2026-07-29'),
  (80023, 'Caldera', 170, 1397, 8.64907000, -82.38058000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80023', 'dr5hn-2026-07-29'),
  (80038, 'Cañas Gordas', 170, 1397, 8.74309000, -82.91275000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80038', 'dr5hn-2026-07-29'),
  (80043, 'Celmira', 170, 1397, 8.54026000, -82.80022000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80043', 'dr5hn-2026-07-29'),
  (80051, 'Cerro Punta', 170, 1397, 8.84968000, -82.57261000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80051', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80052, 'Cerro Viejo', 170, 1397, 8.25349000, -81.57658000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80052', 'dr5hn-2026-07-29'),
  (80062, 'Chiriquí', 170, 1397, 8.39291000, -82.31993000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80062', 'dr5hn-2026-07-29'),
  (80070, 'Cochea Abajo', 170, 1397, 8.50512000, -82.35878000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80070', 'dr5hn-2026-07-29'),
  (80075, 'Cordillera', 170, 1397, 8.70683000, -82.60327000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80075', 'dr5hn-2026-07-29'),
  (80082, 'David', 170, 1397, 8.42729000, -82.43085000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80082', 'dr5hn-2026-07-29'),
  (80087, 'Distrito de Alanje', 170, 1397, 8.39842000, -82.64065000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80087', 'dr5hn-2026-07-29'),
  (80091, 'Distrito de Barú', 170, 1397, 8.29482000, -82.92726000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80091', 'dr5hn-2026-07-29'),
  (80093, 'Distrito de Boquerón', 170, 1397, 8.61667000, -82.56667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80093', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80094, 'Distrito de Boquete', 170, 1397, 8.74896000, -82.36842000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80094', 'dr5hn-2026-07-29'),
  (80095, 'Distrito de Bugaba', 170, 1397, 8.68786000, -82.67937000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80095', 'dr5hn-2026-07-29'),
  (80107, 'Distrito de David', 170, 1397, 8.40000000, -82.40000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80107', 'dr5hn-2026-07-29'),
  (80108, 'Distrito de Dolega', 170, 1397, 8.61667000, -82.45000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80108', 'dr5hn-2026-07-29'),
  (80110, 'Distrito de Gualaca', 170, 1397, 8.57398000, -82.22207000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80110', 'dr5hn-2026-07-29'),
  (80132, 'Distrito de Remedios', 170, 1397, 8.20253000, -81.81163000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80132', 'dr5hn-2026-07-29'),
  (80133, 'Distrito de Renacimiento', 170, 1397, 8.71667000, -82.76667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80133', 'dr5hn-2026-07-29'),
  (80137, 'Distrito de San Félix', 170, 1397, 8.27768000, -81.87377000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80137', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80138, 'Distrito de San Lorenzo', 170, 1397, 8.29366000, -82.08922000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80138', 'dr5hn-2026-07-29'),
  (80145, 'Distrito de Tolé', 170, 1397, 8.19015000, -81.66007000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80145', 'dr5hn-2026-07-29'),
  (80147, 'Divalá', 170, 1397, 8.41066000, -82.71332000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80147', 'dr5hn-2026-07-29'),
  (80148, 'Dolega', 170, 1397, 8.56667000, -82.41407000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80148', 'dr5hn-2026-07-29'),
  (80185, 'El Nancito', 170, 1397, 8.23811000, -81.73218000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80185', 'dr5hn-2026-07-29'),
  (80186, 'El Palmar', 170, 1397, 8.30098000, -82.85344000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80186', 'dr5hn-2026-07-29'),
  (80192, 'El Porvenir', 170, 1397, 8.22919000, -81.83278000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80192', 'dr5hn-2026-07-29'),
  (80203, 'El Tejar', 170, 1397, 8.42973000, -82.57294000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80203', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80210, 'Finca Blanco', 170, 1397, 8.37979000, -82.87385000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80210', 'dr5hn-2026-07-29'),
  (80229, 'Gómez', 170, 1397, 8.56085000, -82.74142000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80229', 'dr5hn-2026-07-29'),
  (80216, 'Guabal', 170, 1397, 8.57466000, -82.53730000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80216', 'dr5hn-2026-07-29'),
  (80218, 'Guaca Arriba', 170, 1397, 8.53733000, -82.49281000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80218', 'dr5hn-2026-07-29'),
  (80220, 'Gualaca', 170, 1397, 8.53006000, -82.29959000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80220', 'dr5hn-2026-07-29'),
  (80225, 'Guayabal', 170, 1397, 8.62193000, -82.57935000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80225', 'dr5hn-2026-07-29'),
  (80233, 'Horconcitos', 170, 1397, 8.31142000, -82.15102000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80233', 'dr5hn-2026-07-29'),
  (80247, 'La Concepción', 170, 1397, 8.51212000, -82.61858000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80247', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80252, 'La Esperanza', 170, 1397, 8.40344000, -82.79197000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80252', 'dr5hn-2026-07-29'),
  (80254, 'La Estrella', 170, 1397, 8.51572000, -82.67212000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80254', 'dr5hn-2026-07-29'),
  (80283, 'Lajas Adentro', 170, 1397, 8.24981000, -81.87779000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80283', 'dr5hn-2026-07-29'),
  (80284, 'Lajas de Tolé', 170, 1397, 8.16994000, -81.69654000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80284', 'dr5hn-2026-07-29'),
  (80294, 'Las Lajas', 170, 1397, 8.24184000, -81.86931000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80294', 'dr5hn-2026-07-29'),
  (80296, 'Las Lomas', 170, 1397, 8.42927000, -82.38743000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80296', 'dr5hn-2026-07-29'),
  (80311, 'Limones', 170, 1397, 8.10007000, -82.86679000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80311', 'dr5hn-2026-07-29'),
  (80328, 'Los Anastacios', 170, 1397, 8.53027000, -82.42295000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80328', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80343, 'Los Ángeles', 170, 1397, 8.52271000, -82.19997000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80343', 'dr5hn-2026-07-29'),
  (80338, 'Los Naranjos', 170, 1397, 8.79210000, -82.44665000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80338', 'dr5hn-2026-07-29'),
  (80347, 'Manaca Civil', 170, 1397, 8.32458000, -82.81570000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80347', 'dr5hn-2026-07-29'),
  (80348, 'Manaca Norte', 170, 1397, 8.33419000, -82.81003000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80348', 'dr5hn-2026-07-29'),
  (80351, 'Mata del Nance', 170, 1397, 8.45056000, -82.40057000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80351', 'dr5hn-2026-07-29'),
  (80360, 'Monte Lirio', 170, 1397, 8.78935000, -82.82865000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80360', 'dr5hn-2026-07-29'),
  (80378, 'Nuevo San Carlitos', 170, 1397, 8.45698000, -82.43712000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80378', 'dr5hn-2026-07-29'),
  (80387, 'Paja de Sombrero', 170, 1397, 8.68335000, -82.31911000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80387', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80390, 'Palmira', 170, 1397, 8.73401000, -82.45887000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80390', 'dr5hn-2026-07-29'),
  (80393, 'Palmira Centro', 170, 1397, 8.73956000, -82.45228000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80393', 'dr5hn-2026-07-29'),
  (80402, 'Paso Canoas Arriba', 170, 1397, 8.56516000, -82.82214000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80402', 'dr5hn-2026-07-29'),
  (80404, 'Pedregal', 170, 1397, 8.36586000, -82.43524000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80404', 'dr5hn-2026-07-29'),
  (80418, 'Plaza de Caisán', 170, 1397, 8.73672000, -82.81968000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80418', 'dr5hn-2026-07-29'),
  (80424, 'Potrerillos Abajo', 170, 1397, 8.63978000, -82.48560000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80424', 'dr5hn-2026-07-29'),
  (80425, 'Potrerillos Arriba', 170, 1397, 8.68547000, -82.49090000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80425', 'dr5hn-2026-07-29'),
  (80428, 'Progreso', 170, 1397, 8.44669000, -82.83859000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80428', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80430, 'Pueblo Viejo', 170, 1397, 8.25081000, -81.66259000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80430', 'dr5hn-2026-07-29'),
  (80431, 'Puerto Armuelles', 170, 1397, 8.27775000, -82.86206000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80431', 'dr5hn-2026-07-29'),
  (80440, 'Punta de Burica', 170, 1397, 8.03333000, -82.86667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80440', 'dr5hn-2026-07-29'),
  (80447, 'Quebrada de Piedra', 170, 1397, 8.09418000, -81.67915000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80447', 'dr5hn-2026-07-29'),
  (80449, 'Querévalo', 170, 1397, 8.37174000, -82.52670000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80449', 'dr5hn-2026-07-29'),
  (80450, 'Quinteño', 170, 1397, 8.47102000, -82.39352000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80450', 'dr5hn-2026-07-29'),
  (80451, 'Remedios', 170, 1397, 8.22436000, -81.82747000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80451', 'dr5hn-2026-07-29'),
  (80452, 'Rincón', 170, 1397, 8.46374000, -82.27951000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80452', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80465, 'Río Sereno', 170, 1397, 8.81741000, -82.85731000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80465', 'dr5hn-2026-07-29'),
  (80455, 'Rovira Arriba', 170, 1397, 8.63822000, -82.49965000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80455', 'dr5hn-2026-07-29'),
  (80471, 'San Andrés', 170, 1397, 8.60260000, -82.72588000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80471', 'dr5hn-2026-07-29'),
  (80478, 'San Félix', 170, 1397, 8.29063000, -81.86702000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80478', 'dr5hn-2026-07-29'),
  (80480, 'San Isidro', 170, 1397, 8.53032000, -82.82720000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80480', 'dr5hn-2026-07-29'),
  (80487, 'San Lorenzo', 170, 1397, 8.30561000, -82.10114000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80487', 'dr5hn-2026-07-29'),
  (80491, 'San Pablo Nuevo Abajo', 170, 1397, 8.42558000, -82.50173000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80491', 'dr5hn-2026-07-29'),
  (80492, 'San Pablo Viejo Abajo', 170, 1397, 8.45339000, -82.50179000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80492', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80499, 'Santa Cruz', 170, 1397, 8.23219000, -81.91323000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80499', 'dr5hn-2026-07-29'),
  (80503, 'Santa Marta', 170, 1397, 8.51406000, -82.69870000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80503', 'dr5hn-2026-07-29'),
  (80507, 'Santa Rosa', 170, 1397, 8.59958000, -82.68489000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80507', 'dr5hn-2026-07-29'),
  (80509, 'Santo Domingo', 170, 1397, 8.50803000, -82.71295000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80509', 'dr5hn-2026-07-29'),
  (80511, 'Santo Tomás', 170, 1397, 8.38959000, -82.65058000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80511', 'dr5hn-2026-07-29'),
  (80513, 'Sioguí Abajo', 170, 1397, 8.48678000, -82.66539000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80513', 'dr5hn-2026-07-29'),
  (80514, 'Sioguí Arriba', 170, 1397, 8.53865000, -82.68619000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80514', 'dr5hn-2026-07-29'),
  (80517, 'Sortova', 170, 1397, 8.54642000, -82.65170000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80517', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80520, 'Tijeras', 170, 1397, 8.47514000, -82.56058000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80520', 'dr5hn-2026-07-29'),
  (80521, 'Tinajas', 170, 1397, 8.55281000, -82.45963000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80521', 'dr5hn-2026-07-29'),
  (80525, 'Tolé', 170, 1397, 8.23989000, -81.67168000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80525', 'dr5hn-2026-07-29'),
  (80539, 'Veladero', 170, 1397, 8.23136000, -81.65417000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80539', 'dr5hn-2026-07-29'),
  (80550, 'Volcán', 170, 1397, 8.77291000, -82.63823000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80550', 'dr5hn-2026-07-29'),
  (79956, 'Aguadulce', 170, 1387, 8.24183000, -80.54609000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79956', 'dr5hn-2026-07-29'),
  (79957, 'Aguas Blancas', 170, 1387, 8.50351000, -80.31169000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79957', 'dr5hn-2026-07-29'),
  (79965, 'Alto de La Estancia', 170, 1387, 8.58792000, -80.18443000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79965', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79969, 'Antón', 170, 1387, 8.39733000, -80.26063000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79969', 'dr5hn-2026-07-29'),
  (79984, 'Barranco Colorado', 170, 1387, 8.38937000, -80.63546000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79984', 'dr5hn-2026-07-29'),
  (80013, 'Caballero', 170, 1387, 8.54343000, -80.19769000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80013', 'dr5hn-2026-07-29'),
  (80015, 'Cabuya', 170, 1387, 8.54703000, -80.16756000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80015', 'dr5hn-2026-07-29'),
  (80039, 'Cañaveral', 170, 1387, 8.51700000, -80.42916000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80039', 'dr5hn-2026-07-29'),
  (80032, 'Capellanía', 170, 1387, 8.29858000, -80.55480000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80032', 'dr5hn-2026-07-29'),
  (80058, 'Chigoré', 170, 1387, 8.53035000, -80.35117000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80058', 'dr5hn-2026-07-29'),
  (80059, 'Chiguirí Arriba', 170, 1387, 8.67187000, -80.18975000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80059', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80067, 'Churuquita Chiquita', 170, 1387, 8.57555000, -80.27161000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80067', 'dr5hn-2026-07-29'),
  (80068, 'Churuquita Grande', 170, 1387, 8.59449000, -80.27182000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80068', 'dr5hn-2026-07-29'),
  (80071, 'Coclé', 170, 1387, 8.45601000, -80.42899000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80071', 'dr5hn-2026-07-29'),
  (80086, 'Distrito de Aguadulce', 170, 1387, 8.21270000, -80.61441000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80086', 'dr5hn-2026-07-29'),
  (80088, 'Distrito de Antón', 170, 1387, 8.45394000, -80.18361000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80088', 'dr5hn-2026-07-29'),
  (80114, 'Distrito de La Pintada', 170, 1387, 8.71801000, -80.53946000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80114', 'dr5hn-2026-07-29'),
  (80122, 'Distrito de Natá', 170, 1387, 8.34416000, -80.60934000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80122', 'dr5hn-2026-07-29'),
  (80124, 'Distrito de Olá', 170, 1387, 8.48053000, -80.65324000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80124', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80085, 'Distrito Penonomé', 170, 1387, 8.63000000, -80.28333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80085', 'dr5hn-2026-07-29'),
  (80157, 'El Caño', 170, 1387, 8.40195000, -80.51791000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80157', 'dr5hn-2026-07-29'),
  (80159, 'El Chirú', 170, 1387, 8.39876000, -80.18721000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80159', 'dr5hn-2026-07-29'),
  (80165, 'El Copé', 170, 1387, 8.62036000, -80.58433000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80165', 'dr5hn-2026-07-29'),
  (80166, 'El Cortezo', 170, 1387, 8.34556000, -80.58721000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80166', 'dr5hn-2026-07-29'),
  (80168, 'El Cristo', 170, 1387, 8.25071000, -80.62093000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80168', 'dr5hn-2026-07-29'),
  (80198, 'El Retiro', 170, 1387, 8.48014000, -80.15426000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80198', 'dr5hn-2026-07-29'),
  (80201, 'El Roble', 170, 1387, 8.16850000, -80.65897000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80201', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80207, 'Entradero', 170, 1387, 8.56880000, -80.20743000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80207', 'dr5hn-2026-07-29'),
  (80209, 'Farallón', 170, 1387, 8.35658000, -80.13723000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80209', 'dr5hn-2026-07-29'),
  (80228, 'Guzman', 170, 1387, 8.51969000, -80.58405000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80228', 'dr5hn-2026-07-29'),
  (80275, 'La Pintada', 170, 1387, 8.59299000, -80.44349000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80275', 'dr5hn-2026-07-29'),
  (80293, 'Las Huacas del Quije', 170, 1387, 8.46702000, -80.75089000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80293', 'dr5hn-2026-07-29'),
  (80299, 'Las Marias', 170, 1387, 8.88809000, -80.21893000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80299', 'dr5hn-2026-07-29'),
  (80300, 'Las Minas', 170, 1387, 8.64118000, -80.39432000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80300', 'dr5hn-2026-07-29'),
  (80305, 'Las Sabanas', 170, 1387, 8.58141000, -80.67978000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80305', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80315, 'Llano Grande', 170, 1387, 8.63817000, -80.43848000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80315', 'dr5hn-2026-07-29'),
  (80320, 'Llano Marín', 170, 1387, 8.47696000, -80.32499000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80320', 'dr5hn-2026-07-29'),
  (80340, 'Los Pollos', 170, 1387, 8.39898000, -80.15731000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80340', 'dr5hn-2026-07-29'),
  (80366, 'Natá', 170, 1387, 8.33209000, -80.51969000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80366', 'dr5hn-2026-07-29'),
  (80370, 'Nuestro Amo', 170, 1387, 8.44485000, -80.58934000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80370', 'dr5hn-2026-07-29'),
  (80383, 'Olá', 170, 1387, 8.41807000, -80.65123000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80383', 'dr5hn-2026-07-29'),
  (80406, 'Penonomé', 170, 1387, 8.51889000, -80.35727000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80406', 'dr5hn-2026-07-29'),
  (80419, 'Pocrí', 170, 1387, 8.25814000, -80.55000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80419', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80462, 'Río Hato', 170, 1387, 8.37940000, -80.16621000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80462', 'dr5hn-2026-07-29'),
  (80486, 'San Juan de Dios', 170, 1387, 8.55119000, -80.22623000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80486', 'dr5hn-2026-07-29'),
  (80522, 'Toabré', 170, 1387, 8.65131000, -80.32017000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80522', 'dr5hn-2026-07-29'),
  (80528, 'Toza', 170, 1387, 8.34542000, -80.64012000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80528', 'dr5hn-2026-07-29'),
  (80007, 'Buena Vista', 170, 1386, 9.27356000, -79.69551000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80007', 'dr5hn-2026-07-29'),
  (80035, 'Cativá', 170, 1386, 9.36218000, -79.83232000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80035', 'dr5hn-2026-07-29'),
  (80072, 'Coclé del Norte', 170, 1386, 9.07540000, -80.57177000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80072', 'dr5hn-2026-07-29'),
  (80073, 'Colón', 170, 1386, 9.35451000, -79.90011000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80073', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80078, 'Cristóbal', 170, 1386, 9.35222000, -79.90444000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80078', 'dr5hn-2026-07-29'),
  (80099, 'Distrito de Chagres', 170, 1386, 9.12300000, -80.11841000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80099', 'dr5hn-2026-07-29'),
  (80106, 'Distrito de Colón', 170, 1386, 9.24313000, -79.79463000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80106', 'dr5hn-2026-07-29'),
  (80109, 'Distrito de Donoso', 170, 1386, 9.01999000, -80.42967000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80109', 'dr5hn-2026-07-29'),
  (80131, 'Distrito de Portobelo', 170, 1386, 9.49748000, -79.60730000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80131', 'dr5hn-2026-07-29'),
  (80140, 'Distrito de Santa Isabel', 170, 1386, 9.48333000, -79.31667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80140', 'dr5hn-2026-07-29'),
  (80174, 'El Giral', 170, 1386, 9.24509000, -79.69266000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80174', 'dr5hn-2026-07-29'),
  (80175, 'El Guabo', 170, 1386, 9.07842000, -80.08316000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80175', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80206, 'El Valle de la Unión', 170, 1386, 9.23630000, -79.65986000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80206', 'dr5hn-2026-07-29'),
  (80208, 'Escobal', 170, 1386, 9.14373000, -79.96439000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80208', 'dr5hn-2026-07-29'),
  (80214, 'Gatún', 170, 1386, 9.28922000, -79.77204000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80214', 'dr5hn-2026-07-29'),
  (80213, 'Gatuncillo', 170, 1386, 9.24346000, -79.64856000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80213', 'dr5hn-2026-07-29'),
  (80297, 'Las Margaritas', 170, 1386, 9.32603000, -79.89028000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80297', 'dr5hn-2026-07-29'),
  (80350, 'María Chiquita', 170, 1386, 9.43991000, -79.75455000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80350', 'dr5hn-2026-07-29'),
  (80368, 'Nombre de Dios', 170, 1386, 9.57937000, -79.47109000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80368', 'dr5hn-2026-07-29'),
  (80376, 'Nuevo Chagres', 170, 1386, 9.23979000, -80.08267000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80376', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80379, 'Nuevo San Juan', 170, 1386, 9.22205000, -79.66602000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80379', 'dr5hn-2026-07-29'),
  (80380, 'Nuevo Vigía', 170, 1386, 9.24263000, -79.60756000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80380', 'dr5hn-2026-07-29'),
  (80388, 'Palenque', 170, 1386, 9.56970000, -79.36341000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80388', 'dr5hn-2026-07-29'),
  (80389, 'Palmas Bellas', 170, 1386, 9.22838000, -80.08503000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80389', 'dr5hn-2026-07-29'),
  (80415, 'Playa Chiquita', 170, 1386, 9.56620000, -79.29185000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80415', 'dr5hn-2026-07-29'),
  (80423, 'Portobelo', 170, 1386, 9.55303000, -79.65693000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80423', 'dr5hn-2026-07-29'),
  (80433, 'Puerto Escondido', 170, 1386, 9.19333000, -80.08833000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80433', 'dr5hn-2026-07-29'),
  (80435, 'Puerto Pilón', 170, 1386, 9.36316000, -79.79333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80435', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80443, 'Quebrada Bonita Adentro', 170, 1386, 9.29662000, -79.70606000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80443', 'dr5hn-2026-07-29'),
  (80457, 'Río Alejandro', 170, 1386, 9.37149000, -79.78809000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80457', 'dr5hn-2026-07-29'),
  (80459, 'Río Duque', 170, 1386, 9.25688000, -79.67937000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80459', 'dr5hn-2026-07-29'),
  (80464, 'Río Rita', 170, 1386, 9.30296000, -79.79234000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80464', 'dr5hn-2026-07-29'),
  (80469, 'Sabanitas', 170, 1386, 9.34269000, -79.80961000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80469', 'dr5hn-2026-07-29'),
  (80502, 'Santa Isabel', 170, 1386, 9.53922000, -79.19570000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80502', 'dr5hn-2026-07-29'),
  (80506, 'Santa Rita Arriba', 170, 1386, 9.33032000, -79.79363000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80506', 'dr5hn-2026-07-29'),
  (80541, 'Viento Frío', 170, 1386, 9.58263000, -79.40690000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80541', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79997, 'Boca de Cupé', 170, 1385, 8.03003000, -77.58978000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79997', 'dr5hn-2026-07-29'),
  (80030, 'Camogantí', 170, 1385, 8.04171000, -77.88682000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80030', 'dr5hn-2026-07-29'),
  (80079, 'Cucunatí', 170, 1385, 8.57508000, -78.25671000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80079', 'dr5hn-2026-07-29'),
  (80102, 'Distrito de Chepigana', 170, 1385, 7.84374000, -77.83830000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80102', 'dr5hn-2026-07-29'),
  (80129, 'Distrito de Pinogana', 170, 1385, 7.89343000, -77.52562000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80129', 'dr5hn-2026-07-29'),
  (80212, 'Garachiné', 170, 1385, 8.06684000, -78.36436000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80212', 'dr5hn-2026-07-29'),
  (80236, 'Jaqué', 170, 1385, 7.51826000, -78.16343000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80236', 'dr5hn-2026-07-29'),
  (80353, 'Metetí', 170, 1385, 8.49909000, -77.97897000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80353', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80362, 'Mortí', 170, 1385, 8.84246000, -77.97539000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80362', 'dr5hn-2026-07-29'),
  (80442, 'Púcuro', 170, 1385, 7.97876000, -77.48758000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80442', 'dr5hn-2026-07-29'),
  (80552, 'Yaviza', 170, 1385, 8.15835000, -77.69276000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80552', 'dr5hn-2026-07-29'),
  (79987, 'Bayamón', 170, 1396, 7.96817000, -78.21648000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79987', 'dr5hn-2026-07-29'),
  (80081, 'Cémaco', 170, 1396, 8.08285000, -77.54210000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80081', 'dr5hn-2026-07-29'),
  (80470, 'Sambú', 170, 1396, 7.82013000, -78.11005000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80470', 'dr5hn-2026-07-29'),
  (80531, 'Unión Chocó', 170, 1396, 8.08404000, -77.53507000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80531', 'dr5hn-2026-07-29'),
  (80551, 'Yape', 170, 1396, 8.09839000, -77.59817000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80551', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79954, 'Achutupo', 170, 1388, 9.19827000, -77.98729000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79954', 'dr5hn-2026-07-29'),
  (79958, 'Ailigandí', 170, 1388, 9.22810000, -78.02778000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79958', 'dr5hn-2026-07-29'),
  (80034, 'Cartí Sugdup', 170, 1388, 9.46460000, -78.95931000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80034', 'dr5hn-2026-07-29'),
  (80363, 'Mulatupo', 170, 1388, 8.94672000, -77.75080000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80363', 'dr5hn-2026-07-29'),
  (80365, 'Narganá', 170, 1388, 9.44394000, -78.58666000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80365', 'dr5hn-2026-07-29'),
  (80417, 'Playón Chico', 170, 1388, 9.31128000, -78.23270000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80417', 'dr5hn-2026-07-29'),
  (80434, 'Puerto Obaldía', 170, 1388, 8.66632000, -77.41922000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80434', 'dr5hn-2026-07-29'),
  (80479, 'San Ignacio de Tupile', 170, 1388, 9.28905000, -78.15206000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80479', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80530, 'Tubualá', 170, 1388, 9.51667000, -79.03333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80530', 'dr5hn-2026-07-29'),
  (80534, 'Ustupo', 170, 1388, 9.13112000, -77.92620000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80534', 'dr5hn-2026-07-29'),
  (79998, 'Boca de Parita', 170, 1389, 8.00796000, -80.45320000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79998', 'dr5hn-2026-07-29'),
  (80049, 'Cerro Largo', 170, 1389, 7.83377000, -80.83168000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80049', 'dr5hn-2026-07-29'),
  (80064, 'Chitré', 170, 1389, 7.96082000, -80.42944000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80064', 'dr5hn-2026-07-29'),
  (80065, 'Chumical', 170, 1389, 7.84482000, -80.72627000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80065', 'dr5hn-2026-07-29'),
  (80066, 'Chupampa', 170, 1389, 8.07620000, -80.77656000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80066', 'dr5hn-2026-07-29'),
  (80105, 'Distrito de Chitré', 170, 1389, 7.98333000, -80.43333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80105', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80115, 'Distrito de Las Minas', 170, 1389, 7.76525000, -80.82249000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80115', 'dr5hn-2026-07-29'),
  (80118, 'Distrito de Los Pozos', 170, 1389, 7.70944000, -80.64311000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80118', 'dr5hn-2026-07-29'),
  (80123, 'Distrito de Ocú', 170, 1389, 7.90641000, -80.79752000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80123', 'dr5hn-2026-07-29'),
  (80126, 'Distrito de Parita', 170, 1389, 8.06240000, -80.56373000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80126', 'dr5hn-2026-07-29'),
  (80128, 'Distrito de Pesé', 170, 1389, 7.88194000, -80.63261000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80128', 'dr5hn-2026-07-29'),
  (80141, 'Distrito de Santa María', 170, 1389, 8.11667000, -80.68333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80141', 'dr5hn-2026-07-29'),
  (80153, 'El Calabacito', 170, 1389, 7.71843000, -80.59757000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80153', 'dr5hn-2026-07-29'),
  (80154, 'El Capurí', 170, 1389, 7.72571000, -80.64349000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80154', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80158, 'El Cedro', 170, 1389, 7.68565000, -80.65927000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80158', 'dr5hn-2026-07-29'),
  (80204, 'El Toro', 170, 1389, 7.75110000, -80.86943000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80204', 'dr5hn-2026-07-29'),
  (80241, 'La Arena', 170, 1389, 7.96766000, -80.46523000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80241', 'dr5hn-2026-07-29'),
  (80279, 'La Trinidad', 170, 1389, 7.91457000, -80.70332000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80279', 'dr5hn-2026-07-29'),
  (80312, 'Limón de Tijeras', 170, 1389, 7.81756000, -80.91335000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80312', 'dr5hn-2026-07-29'),
  (80314, 'Llano Bonito', 170, 1389, 7.97637000, -80.41646000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80314', 'dr5hn-2026-07-29'),
  (80321, 'Llano de La Cruz', 170, 1389, 7.95178000, -80.64239000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80321', 'dr5hn-2026-07-29'),
  (80330, 'Los Canelos', 170, 1389, 8.11722000, -80.70769000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80330', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80333, 'Los Cerritos', 170, 1389, 7.79746000, -80.61071000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80333', 'dr5hn-2026-07-29'),
  (80334, 'Los Cerros de Paja', 170, 1389, 7.71821000, -80.67273000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80334', 'dr5hn-2026-07-29'),
  (80341, 'Los Pozos', 170, 1389, 7.78300000, -80.64524000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80341', 'dr5hn-2026-07-29'),
  (80358, 'Monagrillo', 170, 1389, 7.98179000, -80.43764000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80358', 'dr5hn-2026-07-29'),
  (80382, 'Ocú', 170, 1389, 7.94052000, -80.77936000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80382', 'dr5hn-2026-07-29'),
  (80401, 'París', 170, 1389, 8.05053000, -80.55409000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80401', 'dr5hn-2026-07-29'),
  (80398, 'Parita', 170, 1389, 7.99393000, -80.52097000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80398', 'dr5hn-2026-07-29'),
  (80410, 'Peñas Chatas', 170, 1389, 8.01502000, -80.80366000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80410', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80408, 'Pesé', 170, 1389, 7.90863000, -80.61433000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80408', 'dr5hn-2026-07-29'),
  (80413, 'Pitaloza Arriba', 170, 1389, 7.64216000, -80.66788000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80413', 'dr5hn-2026-07-29'),
  (80422, 'Portobelillo', 170, 1389, 8.01738000, -80.59538000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80422', 'dr5hn-2026-07-29'),
  (80427, 'Potuga', 170, 1389, 8.06317000, -80.62271000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80427', 'dr5hn-2026-07-29'),
  (80448, 'Quebrada del Rosario', 170, 1389, 7.71238000, -80.74222000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80448', 'dr5hn-2026-07-29'),
  (80453, 'Rincón Hondo', 170, 1389, 7.84436000, -80.60397000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80453', 'dr5hn-2026-07-29'),
  (80485, 'San Juan Bautista', 170, 1389, 7.96099000, -80.41283000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80485', 'dr5hn-2026-07-29'),
  (80504, 'Santa María', 170, 1389, 8.11143000, -80.66582000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80504', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79955, 'Agua Buena', 170, 1390, 7.83465000, -80.39405000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79955', 'dr5hn-2026-07-29'),
  (79976, 'Ave María', 170, 1390, 7.32481000, -80.45361000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79976', 'dr5hn-2026-07-29'),
  (79978, 'Bahía Honda', 170, 1390, 7.70517000, -80.45342000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79978', 'dr5hn-2026-07-29'),
  (79980, 'Bajo Corral', 170, 1390, 7.60463000, -80.26016000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79980', 'dr5hn-2026-07-29'),
  (79988, 'Bayano', 170, 1390, 7.63014000, -80.38201000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79988', 'dr5hn-2026-07-29'),
  (79990, 'Bella Vista', 170, 1390, 7.75000000, -80.23333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79990', 'dr5hn-2026-07-29'),
  (80029, 'Cambutal', 170, 1390, 7.26534000, -80.49105000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80029', 'dr5hn-2026-07-29'),
  (80037, 'Cañas', 170, 1390, 7.44713000, -80.26480000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80037', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80042, 'Cedro Arriba', 170, 1390, 7.78097000, -80.53057000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80042', 'dr5hn-2026-07-29'),
  (80111, 'Distrito de Guararé', 170, 1390, 7.77021000, -80.37515000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80111', 'dr5hn-2026-07-29'),
  (80117, 'Distrito de Las Tablas', 170, 1390, 7.64843000, -80.29933000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80117', 'dr5hn-2026-07-29'),
  (80119, 'Distrito de Los Santos', 170, 1390, 7.88333000, -80.45000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80119', 'dr5hn-2026-07-29'),
  (80120, 'Distrito de Macaracas', 170, 1390, 7.65817000, -80.53526000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80120', 'dr5hn-2026-07-29'),
  (80127, 'Distrito de Pedasí', 170, 1390, 7.48528000, -80.12747000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80127', 'dr5hn-2026-07-29'),
  (80130, 'Distrito de Pocrí', 170, 1390, 7.63721000, -80.16470000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80130', 'dr5hn-2026-07-29'),
  (80146, 'Distrito de Tonosí', 170, 1390, 7.43597000, -80.45828000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80146', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80156, 'El Cañafístulo', 170, 1390, 7.61768000, -80.23322000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80156', 'dr5hn-2026-07-29'),
  (80155, 'El Carate', 170, 1390, 7.73124000, -80.29691000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80155', 'dr5hn-2026-07-29'),
  (80161, 'El Cocal', 170, 1390, 7.73697000, -80.27980000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80161', 'dr5hn-2026-07-29'),
  (80169, 'El Ejido', 170, 1390, 7.91634000, -80.38686000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80169', 'dr5hn-2026-07-29'),
  (80176, 'El Guásimo', 170, 1390, 7.80640000, -80.52991000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80176', 'dr5hn-2026-07-29'),
  (80177, 'El Hato', 170, 1390, 7.79316000, -80.38267000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80177', 'dr5hn-2026-07-29'),
  (80180, 'El Macano', 170, 1390, 7.68489000, -80.40309000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80180', 'dr5hn-2026-07-29'),
  (80181, 'El Manantial', 170, 1390, 7.78245000, -80.24713000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80181', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80184, 'El Muñoz', 170, 1390, 7.67582000, -80.32130000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80184', 'dr5hn-2026-07-29'),
  (80188, 'El Pedregoso', 170, 1390, 7.69173000, -80.32793000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80188', 'dr5hn-2026-07-29'),
  (80211, 'Flores', 170, 1390, 7.48157000, -80.40695000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80211', 'dr5hn-2026-07-29'),
  (80221, 'Guararé', 170, 1390, 7.81531000, -80.28345000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80221', 'dr5hn-2026-07-29'),
  (80222, 'Guararé Arriba', 170, 1390, 7.80023000, -80.35983000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80222', 'dr5hn-2026-07-29'),
  (80244, 'La Colorada', 170, 1390, 7.82362000, -80.55552000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80244', 'dr5hn-2026-07-29'),
  (80248, 'La Enea', 170, 1390, 7.83333000, -80.27417000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80248', 'dr5hn-2026-07-29'),
  (80253, 'La Espigadilla', 170, 1390, 7.88389000, -80.39039000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80253', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80260, 'La Laja', 170, 1390, 7.73102000, -80.25298000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80260', 'dr5hn-2026-07-29'),
  (80263, 'La Mesa', 170, 1390, 7.65670000, -80.61794000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80263', 'dr5hn-2026-07-29'),
  (80267, 'La Miel', 170, 1390, 7.56022000, -80.32736000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80267', 'dr5hn-2026-07-29'),
  (80270, 'La Palma', 170, 1390, 7.71667000, -80.38333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80270', 'dr5hn-2026-07-29'),
  (80272, 'La Pasera', 170, 1390, 7.79757000, -80.30342000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80272', 'dr5hn-2026-07-29'),
  (80278, 'La Tiza', 170, 1390, 7.75110000, -80.29216000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80278', 'dr5hn-2026-07-29'),
  (80280, 'La Tronosa', 170, 1390, 7.43609000, -80.58698000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80280', 'dr5hn-2026-07-29'),
  (80282, 'Lajamina', 170, 1390, 7.58587000, -80.13212000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80282', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80287, 'Las Cruces', 170, 1390, 7.82285000, -80.43003000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80287', 'dr5hn-2026-07-29'),
  (80289, 'Las Guabas', 170, 1390, 7.81469000, -80.50155000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80289', 'dr5hn-2026-07-29'),
  (80302, 'Las Palmas', 170, 1390, 7.68314000, -80.49728000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80302', 'dr5hn-2026-07-29'),
  (80304, 'Las Palmitas', 170, 1390, 7.76523000, -80.29350000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80304', 'dr5hn-2026-07-29'),
  (80306, 'Las Tablas', 170, 1390, 7.76472000, -80.27483000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80306', 'dr5hn-2026-07-29'),
  (80307, 'Las Trancas', 170, 1390, 7.73400000, -80.37384000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80307', 'dr5hn-2026-07-29'),
  (80313, 'Llano Abajo', 170, 1390, 7.78598000, -80.41060000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80313', 'dr5hn-2026-07-29'),
  (80322, 'Llano de Piedra', 170, 1390, 7.65972000, -80.56347000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80322', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80318, 'Llano Largo', 170, 1390, 7.90607000, -80.42561000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80318', 'dr5hn-2026-07-29'),
  (80329, 'Los Asientos', 170, 1390, 7.51656000, -80.13521000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80329', 'dr5hn-2026-07-29'),
  (80339, 'Los Olivos', 170, 1390, 7.91589000, -80.48884000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80339', 'dr5hn-2026-07-29'),
  (80342, 'Los Santos', 170, 1390, 7.93333000, -80.41667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80342', 'dr5hn-2026-07-29'),
  (80346, 'Macaracas', 170, 1390, 7.73168000, -80.55364000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80346', 'dr5hn-2026-07-29'),
  (80357, 'Mogollón', 170, 1390, 7.64261000, -80.45950000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80357', 'dr5hn-2026-07-29'),
  (80369, 'Nuario', 170, 1390, 7.53047000, -80.32692000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80369', 'dr5hn-2026-07-29'),
  (80385, 'Oria Arriba', 170, 1390, 7.50505000, -80.20567000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80385', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80395, 'Paraíso', 170, 1390, 7.68510000, -80.16082000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80395', 'dr5hn-2026-07-29'),
  (80399, 'Paritilla', 170, 1390, 7.62848000, -80.17240000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80399', 'dr5hn-2026-07-29'),
  (80403, 'Pedasí', 170, 1390, 7.53034000, -80.02699000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80403', 'dr5hn-2026-07-29'),
  (80409, 'Peña Blanca', 170, 1390, 7.71931000, -80.28366000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80409', 'dr5hn-2026-07-29'),
  (80407, 'Perales', 170, 1390, 7.77461000, -80.32494000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80407', 'dr5hn-2026-07-29'),
  (80463, 'Río Hondo', 170, 1390, 7.71192000, -80.35904000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80463', 'dr5hn-2026-07-29'),
  (80467, 'Sabana Grande', 170, 1390, 7.83543000, -80.36490000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80467', 'dr5hn-2026-07-29'),
  (80496, 'Santa Ana Arriba', 170, 1390, 7.93300000, -80.36369000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80496', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80512, 'Sesteadero', 170, 1390, 7.73885000, -80.24854000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80512', 'dr5hn-2026-07-29'),
  (80526, 'Tonosí', 170, 1390, 7.40684000, -80.44217000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80526', 'dr5hn-2026-07-29'),
  (80529, 'Tres Quebradas', 170, 1390, 7.84018000, -80.40740000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80529', 'dr5hn-2026-07-29'),
  (80536, 'Valle Rico', 170, 1390, 7.62011000, -80.35076000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80536', 'dr5hn-2026-07-29'),
  (80538, 'Vallerriquito', 170, 1390, 7.62163000, -80.31975000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80538', 'dr5hn-2026-07-29'),
  (80544, 'Villa Lourdes', 170, 1390, 7.81141000, -80.47029000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80544', 'dr5hn-2026-07-29'),
  (160100, 'Bonyik', 170, 5686, 9.35000000, -82.60000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:160100', 'dr5hn-2026-07-29'),
  (160099, 'San San Drui', 170, 5686, 9.30000000, -82.70000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:160099', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (160097, 'Sieyic', 170, 5686, 9.38333333, -82.65222222, 'America/Panama', NULL, NULL, 'city', 'dr5hn:160097', 'dr5hn-2026-07-29'),
  (160098, 'Teribe', 170, 5686, 9.38333333, -82.58333333, 'America/Panama', NULL, NULL, 'city', 'dr5hn:160098', 'dr5hn-2026-07-29'),
  (79977, 'Bahía Azul', 170, 1391, 9.14176000, -81.89425000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79977', 'dr5hn-2026-07-29'),
  (79991, 'Besiko', 170, 1391, 8.54863000, -82.08980000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79991', 'dr5hn-2026-07-29'),
  (79993, 'Bisira', 170, 1391, 8.89553000, -81.85352000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79993', 'dr5hn-2026-07-29'),
  (79996, 'Boca de Balsa', 170, 1391, 8.52995000, -82.03132000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79996', 'dr5hn-2026-07-29'),
  (80008, 'Buenos Aires', 170, 1391, 8.41384000, -81.48440000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80008', 'dr5hn-2026-07-29'),
  (80028, 'Camarón Arriba', 170, 1391, 8.38324000, -81.99345000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80028', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80046, 'Cerro Banco', 170, 1391, 8.45797000, -82.03081000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80046', 'dr5hn-2026-07-29'),
  (80048, 'Cerro Caña', 170, 1391, 8.35174000, -81.61050000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80048', 'dr5hn-2026-07-29'),
  (80050, 'Cerro Plata', 170, 1391, 8.47733000, -81.54585000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80050', 'dr5hn-2026-07-29'),
  (80057, 'Chichica', 170, 1391, 8.35885000, -81.66582000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80057', 'dr5hn-2026-07-29'),
  (80230, 'Hato Chami', 170, 1391, 8.44281000, -81.77196000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80230', 'dr5hn-2026-07-29'),
  (80231, 'Hato Corotú', 170, 1391, 8.33516000, -81.97030000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80231', 'dr5hn-2026-07-29'),
  (80239, 'Kankintú', 170, 1391, 8.89503000, -81.85750000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80239', 'dr5hn-2026-07-29'),
  (80240, 'Kusapín', 170, 1391, 9.17119000, -81.89621000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80240', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80285, 'Lajero Arriba', 170, 1391, 8.29060000, -81.77047000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80285', 'dr5hn-2026-07-29'),
  (80323, 'Llano Ñopo', 170, 1391, 8.41996000, -81.61865000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80323', 'dr5hn-2026-07-29'),
  (80325, 'Loma Yuca', 170, 1391, 8.71817000, -81.40492000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80325', 'dr5hn-2026-07-29'),
  (80356, 'Mirono', 170, 1391, 8.40469000, -81.83064000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80356', 'dr5hn-2026-07-29'),
  (80364, 'Müna', 170, 1391, 8.35035000, -81.67219000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80364', 'dr5hn-2026-07-29'),
  (80367, 'Nole Düima', 170, 1391, 8.32682000, -81.81531000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80367', 'dr5hn-2026-07-29'),
  (80381, 'Nurun', 170, 1391, 8.47815000, -81.47015000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80381', 'dr5hn-2026-07-29'),
  (80384, 'Oma', 170, 1391, 8.35019000, -81.80177000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80384', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80397, 'Paredón Arriba', 170, 1391, 8.45977000, -81.19592000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80397', 'dr5hn-2026-07-29'),
  (80414, 'Plan de Chorcha', 170, 1391, 8.46168000, -82.15924000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80414', 'dr5hn-2026-07-29'),
  (80429, 'Pueblo Nuevo', 170, 1391, 8.88070000, -82.22411000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80429', 'dr5hn-2026-07-29'),
  (80444, 'Quebrada Canoa', 170, 1391, 8.43333000, -81.78333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80444', 'dr5hn-2026-07-29'),
  (80445, 'Quebrada Tula', 170, 1391, 8.84037000, -81.99645000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80445', 'dr5hn-2026-07-29'),
  (80515, 'Sitio Prado', 170, 1391, 8.37233000, -81.58141000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80515', 'dr5hn-2026-07-29'),
  (80523, 'Tobobe', 170, 1391, 9.12111000, -81.82471000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80523', 'dr5hn-2026-07-29'),
  (79960, 'Alcalde Díaz', 170, 1395, 9.12016000, -79.55641000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79960', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79968, 'Ancón', 170, 1395, 8.96015000, -79.55140000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79968', 'dr5hn-2026-07-29'),
  (80006, 'Brujas', 170, 1395, 8.58536000, -78.53008000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80006', 'dr5hn-2026-07-29'),
  (80014, 'Cabra Número Uno', 170, 1395, 9.10863000, -79.33694000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80014', 'dr5hn-2026-07-29'),
  (80018, 'Caimitillo', 170, 1395, 9.15559000, -79.53974000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80018', 'dr5hn-2026-07-29'),
  (80027, 'Calzada Larga', 170, 1395, 9.17272000, -79.56212000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80027', 'dr5hn-2026-07-29'),
  (80041, 'Cañita', 170, 1395, 9.22236000, -78.89509000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80041', 'dr5hn-2026-07-29'),
  (80045, 'Cerro Azul', 170, 1395, 9.15735000, -79.42097000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80045', 'dr5hn-2026-07-29'),
  (80055, 'Chepillo', 170, 1395, 8.95396000, -79.12856000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80055', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80056, 'Chepo', 170, 1395, 9.17019000, -79.10083000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80056', 'dr5hn-2026-07-29'),
  (80060, 'Chilibre', 170, 1395, 9.15093000, -79.62098000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80060', 'dr5hn-2026-07-29'),
  (80061, 'Chimán', 170, 1395, 8.69125000, -78.63570000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80061', 'dr5hn-2026-07-29'),
  (80074, 'Contadora', 170, 1395, 8.62483000, -79.03748000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80074', 'dr5hn-2026-07-29'),
  (80080, 'Curundú', 170, 1395, 8.97092000, -79.54612000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80080', 'dr5hn-2026-07-29'),
  (80090, 'Distrito de Balboa', 170, 1395, 8.46667000, -79.00000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80090', 'dr5hn-2026-07-29'),
  (80103, 'Distrito de Chepo', 170, 1395, 9.17391000, -78.70374000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80103', 'dr5hn-2026-07-29'),
  (80104, 'Distrito de Chimán', 170, 1395, 8.76043000, -78.56470000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80104', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80125, 'Distrito de Panamá', 170, 1395, 9.30612000, -79.45246000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80125', 'dr5hn-2026-07-29'),
  (80144, 'Distrito de Taboga', 170, 1395, 8.78333000, -79.55833000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80144', 'dr5hn-2026-07-29'),
  (80160, 'El Chorrillo', 170, 1395, 8.94964000, -79.54715000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80160', 'dr5hn-2026-07-29'),
  (80196, 'El Progreso', 170, 1395, 9.26667000, -79.11667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80196', 'dr5hn-2026-07-29'),
  (80215, 'Gonzalillo', 170, 1395, 9.09183000, -79.51928000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80215', 'dr5hn-2026-07-29'),
  (80234, 'Howard', 170, 1395, 8.93942000, -79.59097000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80234', 'dr5hn-2026-07-29'),
  (80237, 'Juan Díaz', 170, 1395, 9.05000000, -79.45000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80237', 'dr5hn-2026-07-29'),
  (80242, 'La Cabima', 170, 1395, 9.11865000, -79.53660000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80242', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80249, 'La Ensenada', 170, 1395, 8.36618000, -78.84606000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80249', 'dr5hn-2026-07-29'),
  (80251, 'La Esmeralda', 170, 1395, 8.26817000, -78.92460000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80251', 'dr5hn-2026-07-29'),
  (80256, 'La Guinea', 170, 1395, 8.34250000, -78.93430000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80256', 'dr5hn-2026-07-29'),
  (80288, 'Las Cumbres', 170, 1395, 9.08916000, -79.52809000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80288', 'dr5hn-2026-07-29'),
  (80345, 'Lídice', 170, 1395, 8.74869000, -79.90974000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80345', 'dr5hn-2026-07-29'),
  (80337, 'Los Lotes', 170, 1395, 9.12425000, -79.28929000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80337', 'dr5hn-2026-07-29'),
  (80372, 'Nueva Esperanza', 170, 1395, 9.10210000, -79.33414000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80372', 'dr5hn-2026-07-29'),
  (80375, 'Nuevo Belén', 170, 1395, 9.07939000, -79.39556000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80375', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80386, 'Pacora', 170, 1395, 9.07937000, -79.28997000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80386', 'dr5hn-2026-07-29'),
  (80394, 'Panamá', 170, 1395, 8.99360000, -79.51973000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80394', 'dr5hn-2026-07-29'),
  (80400, 'Parque Lefevre', 170, 1395, 9.01667000, -79.48333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80400', 'dr5hn-2026-07-29'),
  (80441, 'Pásiga', 170, 1395, 8.93647000, -78.90917000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80441', 'dr5hn-2026-07-29'),
  (80456, 'Río Abajo', 170, 1395, 9.01667000, -79.50000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80456', 'dr5hn-2026-07-29'),
  (80472, 'San Antonio', 170, 1395, 9.17290000, -79.54743000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80472', 'dr5hn-2026-07-29'),
  (80476, 'San Felipe', 170, 1395, 8.95118000, -79.53726000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80476', 'dr5hn-2026-07-29'),
  (80489, 'San Miguel', 170, 1395, 8.45685000, -78.93695000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80489', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80490, 'San Miguelito', 170, 1395, 9.05032000, -79.47068000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80490', 'dr5hn-2026-07-29'),
  (80494, 'San Vicente', 170, 1395, 9.11445000, -79.59755000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80494', 'dr5hn-2026-07-29'),
  (80524, 'Tocumen', 170, 1395, 9.08939000, -79.38310000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80524', 'dr5hn-2026-07-29'),
  (80527, 'Tortí', 170, 1395, 8.92132000, -78.40546000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80527', 'dr5hn-2026-07-29'),
  (80533, 'Unión de Azuero', 170, 1395, 9.15256000, -79.17005000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80533', 'dr5hn-2026-07-29'),
  (80532, 'Unión Santeña', 170, 1395, 8.83525000, -78.65104000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80532', 'dr5hn-2026-07-29'),
  (80546, 'Villa Unida', 170, 1395, 9.18908000, -79.62452000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80546', 'dr5hn-2026-07-29'),
  (80548, 'Vista Hermosa', 170, 1395, 9.11178000, -79.36113000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80548', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79966, 'Alto del Espino', 170, 1394, 8.84213000, -79.84551000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79966', 'dr5hn-2026-07-29'),
  (79967, 'Altos de San Francisco', 170, 1394, 8.86167000, -79.79000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79967', 'dr5hn-2026-07-29'),
  (79971, 'Arenosa', 170, 1394, 9.03978000, -79.95128000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79971', 'dr5hn-2026-07-29'),
  (79972, 'Arosemena', 170, 1394, 8.97091000, -79.96641000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79972', 'dr5hn-2026-07-29'),
  (79973, 'Arraiján', 170, 1394, 8.95187000, -79.66011000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79973', 'dr5hn-2026-07-29'),
  (79989, 'Bejuco', 170, 1394, 8.60037000, -79.88988000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79989', 'dr5hn-2026-07-29'),
  (80033, 'Capira', 170, 1394, 8.75636000, -79.87996000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80033', 'dr5hn-2026-07-29'),
  (80044, 'Cermeño', 170, 1394, 8.74082000, -79.85299000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80044', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80047, 'Cerro Cama', 170, 1394, 9.02802000, -79.90744000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80047', 'dr5hn-2026-07-29'),
  (80053, 'Chame', 170, 1394, 8.57753000, -79.88595000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80053', 'dr5hn-2026-07-29'),
  (80069, 'Cirí de Los Sotos', 170, 1394, 8.97206000, -80.09209000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80069', 'dr5hn-2026-07-29'),
  (80083, 'Distrito Arraiján', 170, 1394, 8.95000000, -79.70000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80083', 'dr5hn-2026-07-29'),
  (80097, 'Distrito de Capira', 170, 1394, 8.76228000, -79.88275000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80097', 'dr5hn-2026-07-29'),
  (80100, 'Distrito de Chame', 170, 1394, 8.60000000, -79.91667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80100', 'dr5hn-2026-07-29'),
  (80112, 'Distrito de La Chorrera', 170, 1394, 8.95000000, -79.85000000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80112', 'dr5hn-2026-07-29'),
  (80135, 'Distrito de San Carlos', 170, 1394, 8.53196000, -80.06906000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80135', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80151, 'El Cacao', 170, 1394, 8.76134000, -80.01294000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80151', 'dr5hn-2026-07-29'),
  (80163, 'El Coco', 170, 1394, 8.87009000, -79.80415000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80163', 'dr5hn-2026-07-29'),
  (80171, 'El Espavé', 170, 1394, 8.66161000, -79.87584000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80171', 'dr5hn-2026-07-29'),
  (80172, 'El Espino', 170, 1394, 8.83795000, -79.84925000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80172', 'dr5hn-2026-07-29'),
  (80178, 'El Higo', 170, 1394, 8.44731000, -80.03603000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80178', 'dr5hn-2026-07-29'),
  (80179, 'El Líbano', 170, 1394, 8.61685000, -79.83483000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80179', 'dr5hn-2026-07-29'),
  (80219, 'Guadalupe', 170, 1394, 8.85452000, -79.81408000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80219', 'dr5hn-2026-07-29'),
  (80226, 'Guayabito', 170, 1394, 8.54828000, -80.01350000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80226', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80232, 'Hato Montaña', 170, 1394, 8.91938000, -79.73915000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80232', 'dr5hn-2026-07-29'),
  (80243, 'La Chorrera', 170, 1394, 8.88028000, -79.78333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80243', 'dr5hn-2026-07-29'),
  (80250, 'La Ermita', 170, 1394, 8.45622000, -80.06835000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80250', 'dr5hn-2026-07-29'),
  (80257, 'La Herradura', 170, 1394, 8.84848000, -79.80404000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80257', 'dr5hn-2026-07-29'),
  (80268, 'La Mitra', 170, 1394, 8.84091000, -79.78648000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80268', 'dr5hn-2026-07-29'),
  (80273, 'La Pesa', 170, 1394, 8.85073000, -79.82374000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80273', 'dr5hn-2026-07-29'),
  (80286, 'Las Colinas', 170, 1394, 8.55000000, -80.08333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80286', 'dr5hn-2026-07-29'),
  (80308, 'Las Uvas', 170, 1394, 8.45937000, -80.00075000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80308', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80336, 'Los Llanitos', 170, 1394, 8.59787000, -80.09503000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80336', 'dr5hn-2026-07-29'),
  (80352, 'Mendoza', 170, 1394, 9.01471000, -79.85073000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80352', 'dr5hn-2026-07-29'),
  (80371, 'Nueva Arenosa', 170, 1394, 8.86944000, -79.99472000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80371', 'dr5hn-2026-07-29'),
  (80373, 'Nueva Gorgona', 170, 1394, 8.55000000, -79.87547000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80373', 'dr5hn-2026-07-29'),
  (80374, 'Nuevo Arraiján', 170, 1394, 8.92453000, -79.72004000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80374', 'dr5hn-2026-07-29'),
  (80377, 'Nuevo Emperador', 170, 1394, 9.00273000, -79.73141000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80377', 'dr5hn-2026-07-29'),
  (80416, 'Playa Leona', 170, 1394, 8.78389000, -79.77547000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80416', 'dr5hn-2026-07-29'),
  (80426, 'Potrero Grande', 170, 1394, 8.88051000, -79.82795000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80426', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80432, 'Puerto Caimito', 170, 1394, 8.87022000, -79.71423000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80432', 'dr5hn-2026-07-29'),
  (80458, 'Río Congo', 170, 1394, 8.96666000, -79.76105000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80458', 'dr5hn-2026-07-29'),
  (80474, 'San Carlos', 170, 1394, 8.47323000, -79.96104000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80474', 'dr5hn-2026-07-29'),
  (80481, 'San José', 170, 1394, 8.93333000, -79.73333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80481', 'dr5hn-2026-07-29'),
  (80495, 'San Vicente de Bique', 170, 1394, 8.91143000, -79.67360000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80495', 'dr5hn-2026-07-29'),
  (80497, 'Santa Clara', 170, 1394, 9.02875000, -79.75443000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80497', 'dr5hn-2026-07-29'),
  (80505, 'Santa Rita', 170, 1394, 8.85681000, -79.87954000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80505', 'dr5hn-2026-07-29'),
  (80518, 'Sorá', 170, 1394, 8.63191000, -80.00888000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80518', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80540, 'Veracruz', 170, 1394, 8.88988000, -79.62603000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80540', 'dr5hn-2026-07-29'),
  (80543, 'Villa Carmen', 170, 1394, 8.79832000, -79.86929000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80543', 'dr5hn-2026-07-29'),
  (80545, 'Villa Rosario', 170, 1394, 8.77379000, -79.87547000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80545', 'dr5hn-2026-07-29'),
  (80547, 'Vista Alegre', 170, 1394, 8.92772000, -79.70280000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80547', 'dr5hn-2026-07-29'),
  (79964, 'Alto de Jesús', 170, 1392, 8.26152000, -81.48412000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79964', 'dr5hn-2026-07-29'),
  (79970, 'Arenas', 170, 1392, 7.36865000, -80.86268000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79970', 'dr5hn-2026-07-29'),
  (79975, 'Atalaya', 170, 1392, 8.04213000, -80.92528000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79975', 'dr5hn-2026-07-29'),
  (79981, 'Barnizal', 170, 1392, 8.40460000, -80.77765000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79981', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (79994, 'Bisvalles', 170, 1392, 8.18298000, -81.22092000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:79994', 'dr5hn-2026-07-29'),
  (80004, 'Boró', 170, 1392, 8.16933000, -81.30071000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80004', 'dr5hn-2026-07-29'),
  (80022, 'Calabacito', 170, 1392, 8.24817000, -81.08187000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80022', 'dr5hn-2026-07-29'),
  (80024, 'Calidonia', 170, 1392, 7.95756000, -81.38633000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80024', 'dr5hn-2026-07-29'),
  (80025, 'Calobre', 170, 1392, 8.31886000, -80.84067000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80025', 'dr5hn-2026-07-29'),
  (80026, 'Calovébora', 170, 1392, 8.78703000, -81.21056000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80026', 'dr5hn-2026-07-29'),
  (80040, 'Cañazas', 170, 1392, 8.32004000, -81.21152000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80040', 'dr5hn-2026-07-29'),
  (80031, 'Canto del Llano', 170, 1392, 8.12472000, -80.96374000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80031', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80076, 'Corozal', 170, 1392, 8.07712000, -81.43990000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80076', 'dr5hn-2026-07-29'),
  (80089, 'Distrito de Atalaya', 170, 1392, 8.02899000, -80.91739000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80089', 'dr5hn-2026-07-29'),
  (80096, 'Distrito de Calobre', 170, 1392, 8.39684000, -80.85124000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80096', 'dr5hn-2026-07-29'),
  (80098, 'Distrito de Cañazas', 170, 1392, 8.35596000, -81.28633000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80098', 'dr5hn-2026-07-29'),
  (80113, 'Distrito de La Mesa', 170, 1392, 8.10976000, -81.17767000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80113', 'dr5hn-2026-07-29'),
  (80116, 'Distrito de Las Palmas', 170, 1392, 8.14532000, -81.42849000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80116', 'dr5hn-2026-07-29'),
  (80121, 'Distrito de Montijo', 170, 1392, 7.95316000, -81.05301000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80121', 'dr5hn-2026-07-29'),
  (80134, 'Distrito de Río de Jesús', 170, 1392, 7.91438000, -81.16133000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80134', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80136, 'Distrito de San Francisco', 170, 1392, 8.26965000, -81.00108000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80136', 'dr5hn-2026-07-29'),
  (80139, 'Distrito de Santa Fé', 170, 1392, 8.72063000, -80.95858000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80139', 'dr5hn-2026-07-29'),
  (80142, 'Distrito de Santiago', 170, 1392, 8.12425000, -80.87827000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80142', 'dr5hn-2026-07-29'),
  (80143, 'Distrito de Soná', 170, 1392, 7.84378000, -81.36612000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80143', 'dr5hn-2026-07-29'),
  (80149, 'El Alto', 170, 1392, 8.51191000, -81.03646000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80149', 'dr5hn-2026-07-29'),
  (80150, 'El Barrito', 170, 1392, 7.96059000, -80.94801000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80150', 'dr5hn-2026-07-29'),
  (80162, 'El Coclá', 170, 1392, 8.32143000, -80.92069000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80162', 'dr5hn-2026-07-29'),
  (80173, 'El Espino de Santa Rosa', 170, 1392, 8.09286000, -80.82380000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80173', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80182, 'El Marañón', 170, 1392, 8.03582000, -81.21489000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80182', 'dr5hn-2026-07-29'),
  (80183, 'El María', 170, 1392, 8.02905000, -81.44384000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80183', 'dr5hn-2026-07-29'),
  (80197, 'El Pájaro', 170, 1392, 7.95342000, -81.12154000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80197', 'dr5hn-2026-07-29'),
  (80187, 'El Pantano', 170, 1392, 8.53755000, -81.06941000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80187', 'dr5hn-2026-07-29'),
  (80190, 'El Peñón', 170, 1392, 8.35000000, -80.97620000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80190', 'dr5hn-2026-07-29'),
  (80191, 'El Picador', 170, 1392, 8.37803000, -81.25621000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80191', 'dr5hn-2026-07-29'),
  (80194, 'El Potrero', 170, 1392, 8.37692000, -80.79434000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80194', 'dr5hn-2026-07-29'),
  (80199, 'El Rincón', 170, 1392, 8.18422000, -81.43333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80199', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80205, 'El Uvito', 170, 1392, 8.11648000, -80.98461000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80205', 'dr5hn-2026-07-29'),
  (80223, 'Guarumal', 170, 1392, 7.79404000, -81.25904000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80223', 'dr5hn-2026-07-29'),
  (80255, 'La Garceana', 170, 1392, 7.93708000, -81.01643000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80255', 'dr5hn-2026-07-29'),
  (80258, 'La Laguna', 170, 1392, 8.33882000, -80.72949000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80258', 'dr5hn-2026-07-29'),
  (80261, 'La Loma', 170, 1392, 7.43708000, -80.89118000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80261', 'dr5hn-2026-07-29'),
  (80269, 'La Montañuela', 170, 1392, 8.02487000, -80.86325000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80269', 'dr5hn-2026-07-29'),
  (80274, 'La Peña', 170, 1392, 8.12784000, -81.02693000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80274', 'dr5hn-2026-07-29'),
  (80276, 'La Raya de Calobre', 170, 1392, 8.21630000, -80.82729000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80276', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80277, 'La Raya de Santa María', 170, 1392, 8.16429000, -80.82143000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80277', 'dr5hn-2026-07-29'),
  (80281, 'La Yeguada', 170, 1392, 8.43060000, -80.85752000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80281', 'dr5hn-2026-07-29'),
  (80291, 'Las Guías Abajo', 170, 1392, 8.19451000, -80.75494000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80291', 'dr5hn-2026-07-29'),
  (80292, 'Las Huacas', 170, 1392, 7.90167000, -81.14056000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80292', 'dr5hn-2026-07-29'),
  (80309, 'Leones Arriba', 170, 1392, 7.75415000, -81.11556000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80309', 'dr5hn-2026-07-29'),
  (80324, 'Lolá', 170, 1392, 8.09326000, -81.47163000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80324', 'dr5hn-2026-07-29'),
  (80326, 'Los Algarrobos', 170, 1392, 8.10898000, -81.01355000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80326', 'dr5hn-2026-07-29'),
  (80331, 'Los Castillos', 170, 1392, 8.02326000, -81.11941000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80331', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80335, 'Los Higos', 170, 1392, 8.20553000, -80.86022000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80335', 'dr5hn-2026-07-29'),
  (80349, 'Mariato', 170, 1392, 7.67810000, -81.00409000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80349', 'dr5hn-2026-07-29'),
  (80359, 'Monjarás', 170, 1392, 8.36942000, -80.86667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80359', 'dr5hn-2026-07-29'),
  (80361, 'Montijo', 170, 1392, 7.98858000, -81.05643000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80361', 'dr5hn-2026-07-29'),
  (80411, 'Piedras Gordas', 170, 1392, 8.52419000, -80.91152000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80411', 'dr5hn-2026-07-29'),
  (80421, 'Ponuga', 170, 1392, 7.88245000, -80.97880000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80421', 'dr5hn-2026-07-29'),
  (80436, 'Puerto Vidal', 170, 1392, 8.04834000, -81.60499000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80436', 'dr5hn-2026-07-29'),
  (80446, 'Quebrada de Oro', 170, 1392, 8.03548000, -81.38692000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80446', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80466, 'Río de Jesús', 170, 1392, 7.97882000, -81.16162000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80466', 'dr5hn-2026-07-29'),
  (80460, 'Río Grande', 170, 1392, 7.71907000, -81.33423000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80460', 'dr5hn-2026-07-29'),
  (80454, 'Rodeo Viejo', 170, 1392, 8.11205000, -81.31684000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80454', 'dr5hn-2026-07-29'),
  (80473, 'San Bartolo', 170, 1392, 8.21063000, -81.27572000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80473', 'dr5hn-2026-07-29'),
  (80477, 'San Francisco', 170, 1392, 8.06667000, -81.36667000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80477', 'dr5hn-2026-07-29'),
  (80484, 'San Juan', 170, 1392, 8.30311000, -81.01575000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80484', 'dr5hn-2026-07-29'),
  (80488, 'San Marcelo', 170, 1392, 8.27252000, -81.15988000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80488', 'dr5hn-2026-07-29'),
  (80493, 'San Pedro del Espino', 170, 1392, 8.14011000, -81.08663000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80493', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (80500, 'Santa Fé', 170, 1392, 8.51063000, -81.07802000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80500', 'dr5hn-2026-07-29'),
  (80508, 'Santiago de Veraguas', 170, 1392, 8.10000000, -80.98333000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80508', 'dr5hn-2026-07-29'),
  (80516, 'Soná', 170, 1392, 8.01223000, -81.32163000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80516', 'dr5hn-2026-07-29'),
  (80519, 'Tebario', 170, 1392, 7.71369000, -80.97825000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80519', 'dr5hn-2026-07-29'),
  (80535, 'Utirá', 170, 1392, 7.97208000, -81.21777000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80535', 'dr5hn-2026-07-29'),
  (80542, 'Viguí', 170, 1392, 8.33921000, -81.49823000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80542', 'dr5hn-2026-07-29'),
  (80553, 'Zapotillo', 170, 1392, 8.00532000, -81.50653000, 'America/Panama', NULL, NULL, 'city', 'dr5hn:80553', 'dr5hn-2026-07-29');
