-- Cities for PG (Papua New Guinea): 100 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 13 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81029, 'Arawa', 171, 4831, -6.22977000, 155.56598000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81029', 'dr5hn-2026-07-29'),
  (81033, 'Central Bougainville', 171, 4831, -6.22806000, 155.56583000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81033', 'dr5hn-2026-07-29'),
  (81063, 'Kieta', 171, 4831, -6.21462000, 155.63251000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81063', 'dr5hn-2026-07-29'),
  (81091, 'North Bougainville', 171, 4831, -5.42194000, 154.67278000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81091', 'dr5hn-2026-07-29'),
  (81097, 'Panguna', 171, 4831, -6.31639000, 155.48483000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81097', 'dr5hn-2026-07-29'),
  (81109, 'South Bougainville', 171, 4831, -6.74593000, 155.69640000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81109', 'dr5hn-2026-07-29'),
  (81024, 'Abau', 171, 4847, -10.08333000, 148.91667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81024', 'dr5hn-2026-07-29'),
  (81041, 'Goilala', 171, 4847, -8.33333000, 147.00000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81041', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81055, 'Kairuku-Hiri', 171, 4847, -9.13648000, 147.27905000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81055', 'dr5hn-2026-07-29'),
  (81104, 'Rigo', 171, 4847, -9.75000000, 147.83333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81104', 'dr5hn-2026-07-29'),
  (81034, 'Chuave', 171, 4846, -6.16667000, 145.08333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81034', 'dr5hn-2026-07-29'),
  (81043, 'Gumine', 171, 4846, -6.25000000, 144.88333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81043', 'dr5hn-2026-07-29'),
  (81059, 'Karimui Nomane', 171, 4846, -6.58333000, 144.83333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81059', 'dr5hn-2026-07-29'),
  (81062, 'Kerowagi', 171, 4846, -5.93333000, 144.88333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81062', 'dr5hn-2026-07-29'),
  (81073, 'Kundiawa', 171, 4846, -5.91667000, 145.05000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81073', 'dr5hn-2026-07-29'),
  (81107, 'Sinasina Yonggamugl', 171, 4846, -6.08333000, 145.01667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81107', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81040, 'Gazelle', 171, 4834, -4.48333000, 151.86667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81040', 'dr5hn-2026-07-29'),
  (81069, 'Kokopo', 171, 4834, -4.40000000, 152.28333000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81069', 'dr5hn-2026-07-29'),
  (81098, 'Pomio', 171, 4834, -5.50000000, 151.33333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81098', 'dr5hn-2026-07-29'),
  (81102, 'Rabaul', 171, 4834, -4.18333000, 152.16667000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81102', 'dr5hn-2026-07-29'),
  (81036, 'Daulo', 171, 4845, -5.98333000, 145.23333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81036', 'dr5hn-2026-07-29'),
  (81042, 'Goroka', 171, 4845, -6.05000000, 145.38333000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81042', 'dr5hn-2026-07-29'),
  (81045, 'Henganofi', 171, 4845, -6.21667000, 145.66667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81045', 'dr5hn-2026-07-29'),
  (81054, 'Kainantu', 171, 4845, -6.41667000, 145.91667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81054', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81077, 'Lufa', 171, 4845, -6.45000000, 145.25000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81077', 'dr5hn-2026-07-29'),
  (81095, 'Obura Wonenara', 171, 4845, -6.55434000, 145.97328000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81095', 'dr5hn-2026-07-29'),
  (81096, 'Okapa', 171, 4845, -6.63333000, 145.50000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81096', 'dr5hn-2026-07-29'),
  (81118, 'Unggai Bena', 171, 4845, -6.11667000, 145.51667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81118', 'dr5hn-2026-07-29'),
  (81056, 'Kandep', 171, 4848, -5.83333000, 143.55000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81056', 'dr5hn-2026-07-29'),
  (81071, 'Kompiam Ambum', 171, 4848, -5.25000000, 144.00000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81071', 'dr5hn-2026-07-29'),
  (81075, 'Lagaip Porgera', 171, 4848, -5.38333000, 143.16667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81075', 'dr5hn-2026-07-29'),
  (81100, 'Porgera', 171, 4848, -5.46300000, 143.14800000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81100', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81122, 'Wabag', 171, 4848, -5.33333000, 143.65000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81122', 'dr5hn-2026-07-29'),
  (81123, 'Wapenamanda', 171, 4848, -5.66667000, 143.91667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81123', 'dr5hn-2026-07-29'),
  (81061, 'Kerema', 171, 4839, -7.79600000, 146.09300000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81061', 'dr5hn-2026-07-29'),
  (81064, 'Kikori', 171, 4839, -7.25000000, 144.33333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81064', 'dr5hn-2026-07-29'),
  (81070, 'Komo Margarima', 171, 4833, -6.11667000, 143.00000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81070', 'dr5hn-2026-07-29'),
  (81072, 'Koroba-Lake Kopiago', 171, 4833, -5.41667000, 142.50000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81072', 'dr5hn-2026-07-29'),
  (81114, 'Tari', 171, 4833, -5.84500000, 142.94667000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81114', 'dr5hn-2026-07-29'),
  (81115, 'Tari Pori', 171, 4833, -6.28333000, 142.83333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81115', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81028, 'Angalimp South Wahgi', 171, 4832, -6.05000000, 144.56667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81028', 'dr5hn-2026-07-29'),
  (81051, 'Jimi', 171, 4832, -5.53333000, 144.56667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81051', 'dr5hn-2026-07-29'),
  (81093, 'North Wahgi', 171, 4832, -5.80000000, 144.68333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81093', 'dr5hn-2026-07-29'),
  (81031, 'Bogia', 171, 4843, -4.50000000, 145.00000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81031', 'dr5hn-2026-07-29'),
  (81078, 'Madang', 171, 4843, -5.22152000, 145.78695000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81078', 'dr5hn-2026-07-29'),
  (81084, 'Middle Ramu', 171, 4843, -4.91667000, 144.75000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81084', 'dr5hn-2026-07-29'),
  (81103, 'Rai Coast', 171, 4843, -5.72303000, 146.46149000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81103', 'dr5hn-2026-07-29'),
  (81111, 'Sumkar', 171, 4843, -4.80000000, 145.55000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81111', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81119, 'Usino Bundi', 171, 4843, -5.53333000, 145.16667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81119', 'dr5hn-2026-07-29'),
  (81076, 'Lorengau', 171, 4842, -2.03410000, 147.27173000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81076', 'dr5hn-2026-07-29'),
  (81079, 'Manus', 171, 4842, -2.09626000, 146.96612000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81079', 'dr5hn-2026-07-29'),
  (81027, 'Alotau', 171, 4849, -10.25000000, 150.08333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81027', 'dr5hn-2026-07-29'),
  (81038, 'Esa’ala', 171, 4849, -9.58333000, 150.75000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81038', 'dr5hn-2026-07-29'),
  (81066, 'Kiriwina Goodenough', 171, 4849, -8.48333000, 151.06667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81066', 'dr5hn-2026-07-29'),
  (81105, 'Samarai', 171, 4849, -10.61038000, 150.66207000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81105', 'dr5hn-2026-07-29'),
  (81106, 'Samarai Murua', 171, 4849, -10.49636000, 150.54703000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81106', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81032, 'Bulolo', 171, 4835, -7.41667000, 146.75000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81032', 'dr5hn-2026-07-29'),
  (81039, 'Finschhafen', 171, 4835, -6.41667000, 147.50000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81039', 'dr5hn-2026-07-29'),
  (81046, 'Huon Gulf', 171, 4835, -7.18333000, 146.95000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81046', 'dr5hn-2026-07-29'),
  (81052, 'Kabwum', 171, 4835, -6.08333000, 147.00000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81052', 'dr5hn-2026-07-29'),
  (81074, 'Lae', 171, 4835, -6.50000000, 146.83333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81074', 'dr5hn-2026-07-29'),
  (81080, 'Markham', 171, 4835, -6.64153000, 146.86043000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81080', 'dr5hn-2026-07-29'),
  (81082, 'Menyamya', 171, 4835, -7.25000000, 146.16667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81082', 'dr5hn-2026-07-29'),
  (81089, 'Nawae', 171, 4835, -6.46667000, 146.96667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81089', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81117, 'Tewai Siassi', 171, 4835, -6.15000000, 147.53333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81117', 'dr5hn-2026-07-29'),
  (81124, 'Wau', 171, 4835, -7.33778000, 146.71649000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81124', 'dr5hn-2026-07-29'),
  (81060, 'Kavieng', 171, 4841, -3.00000000, 151.41667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81060', 'dr5hn-2026-07-29'),
  (81087, 'Namatanai', 171, 4841, -4.33333000, 152.83333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81087', 'dr5hn-2026-07-29'),
  (81049, 'Ijivitari', 171, 4838, -9.33333000, 148.58333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81049', 'dr5hn-2026-07-29'),
  (81068, 'Kokoda', 171, 4838, -8.87778000, 147.73642000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81068', 'dr5hn-2026-07-29'),
  (81099, 'Popondetta', 171, 4838, -8.76536000, 148.23252000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81099', 'dr5hn-2026-07-29'),
  (81108, 'Sohe', 171, 4838, -9.00000000, 147.91667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81108', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81088, 'National Capital', 171, 4837, -9.42257000, 147.16641000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81088', 'dr5hn-2026-07-29'),
  (81101, 'Port Moresby', 171, 4837, -9.47723000, 147.15089000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81101', 'dr5hn-2026-07-29'),
  (81025, 'Aitape', 171, 4836, -3.13697000, 142.34913000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81025', 'dr5hn-2026-07-29'),
  (81026, 'Aitape Lumi', 171, 4836, -3.25000000, 142.08333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81026', 'dr5hn-2026-07-29'),
  (81094, 'Nuku', 171, 4836, -3.66667000, 142.41667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81094', 'dr5hn-2026-07-29'),
  (81116, 'Telefomin', 171, 4836, -4.91667000, 141.66667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81116', 'dr5hn-2026-07-29'),
  (81120, 'Vanimo', 171, 4836, -2.68372000, 141.30195000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81120', 'dr5hn-2026-07-29'),
  (81121, 'Vanimo Green', 171, 4836, -3.36667000, 141.35000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81121', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81047, 'Ialibu', 171, 4844, -6.28208000, 143.99354000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81047', 'dr5hn-2026-07-29'),
  (81048, 'Ialibu Pangia', 171, 4844, -6.38401880, 144.08381900, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81048', 'dr5hn-2026-07-29'),
  (81053, 'Kagua Erave', 171, 4844, -6.66667000, 144.00000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81053', 'dr5hn-2026-07-29'),
  (81081, 'Mendi', 171, 4844, -6.14755000, 143.65633000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81081', 'dr5hn-2026-07-29'),
  (81090, 'Nipa Kutubu', 171, 4844, -6.33333000, 143.33333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81090', 'dr5hn-2026-07-29'),
  (81057, 'Kandrian', 171, 4830, -6.20655000, 149.54744000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81057', 'dr5hn-2026-07-29'),
  (81058, 'Kandrian Gloucester', 171, 4830, -6.08333000, 149.91667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81058', 'dr5hn-2026-07-29'),
  (81065, 'Kimbe', 171, 4830, -5.55085000, 150.13766000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81065', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81112, 'Talasea', 171, 4830, -5.66667000, 149.58333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81112', 'dr5hn-2026-07-29'),
  (81035, 'Daru', 171, 4850, -9.07786000, 143.20893000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81035', 'dr5hn-2026-07-29'),
  (81067, 'Kiunga', 171, 4850, -6.12193000, 141.29061000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81067', 'dr5hn-2026-07-29'),
  (81083, 'Middle Fly', 171, 4850, -7.16667000, 142.03333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81083', 'dr5hn-2026-07-29'),
  (81085, 'Morehead', 171, 4850, -8.71065000, 141.63668000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81085', 'dr5hn-2026-07-29'),
  (81092, 'North Fly', 171, 4850, -5.72896000, 141.37482000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81092', 'dr5hn-2026-07-29'),
  (81110, 'South Fly', 171, 4850, -8.61667000, 142.11667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81110', 'dr5hn-2026-07-29'),
  (81030, 'Baiyer Mul', 171, 4840, -5.53333000, 144.15000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81030', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (81037, 'Dei', 171, 4840, -5.68333000, 144.36667000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81037', 'dr5hn-2026-07-29'),
  (81044, 'Hagen', 171, 4840, -5.83333000, 144.28333000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81044', 'dr5hn-2026-07-29'),
  (81086, 'Mount Hagen', 171, 4840, -5.85746000, 144.23058000, 'Pacific/Port_Moresby', NULL, NULL, 'city', 'dr5hn:81086', 'dr5hn-2026-07-29'),
  (81113, 'Tambul Nebilyer', 171, 4840, -5.98333000, 144.15000000, 'Pacific/Bougainville', NULL, NULL, 'city', 'dr5hn:81113', 'dr5hn-2026-07-29');
