-- Cities for TD (Chad): 49 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 7 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (105152, 'Moussoro', 43, 3583, 13.64143000, 16.48941000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105152', 'dr5hn-2026-07-29'),
  (105120, 'Ati', 43, 3590, 13.21540000, 18.33530000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105120', 'dr5hn-2026-07-29'),
  (105154, 'Oum Hadjer', 43, 3590, 13.29540000, 19.69660000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105154', 'dr5hn-2026-07-29'),
  (105133, 'Faya-Largeau', 43, 3574, 17.92570000, 19.10428000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105133', 'dr5hn-2026-07-29'),
  (153256, 'Baguirmi Department', 43, 5114, 11.39833333, 16.16750000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153256', 'dr5hn-2026-07-29'),
  (153257, 'Bousso', 43, 5114, 10.48250000, 16.71611111, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153257', 'dr5hn-2026-07-29'),
  (153259, 'Dababa', 43, 5114, 12.38000000, 17.06000000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153259', 'dr5hn-2026-07-29'),
  (153260, 'Gaoui', 43, 5114, 12.18070000, 15.14760000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153260', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153261, 'Linia', 43, 5114, 12.05621410, 15.30379870, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153261', 'dr5hn-2026-07-29'),
  (153262, 'Mandjafa', 43, 5114, 11.19861111, 15.36111111, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153262', 'dr5hn-2026-07-29'),
  (153263, 'Massenya', 43, 5114, 11.40277778, 16.17000000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153263', 'dr5hn-2026-07-29'),
  (105132, 'Fada', 43, 3584, 17.18535000, 21.58114000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105132', 'dr5hn-2026-07-29'),
  (105124, 'Bitkine', 43, 3576, 11.98010000, 18.21380000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105124', 'dr5hn-2026-07-29'),
  (105149, 'Melfi', 43, 3576, 11.05980000, 17.93550000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105149', 'dr5hn-2026-07-29'),
  (105150, 'Mongo', 43, 3576, 12.18441000, 18.69303000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105150', 'dr5hn-2026-07-29'),
  (105125, 'Bokoro', 43, 3573, 12.37813000, 17.05876000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105125', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (105146, 'Massaguet', 43, 3573, 12.47554000, 15.43647000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105146', 'dr5hn-2026-07-29'),
  (105147, 'Massakory', 43, 3573, 12.99600000, 15.72927000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105147', 'dr5hn-2026-07-29'),
  (105145, 'Mao', 43, 3588, 14.12116000, 15.31030000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105145', 'dr5hn-2026-07-29'),
  (105126, 'Bol', 43, 3577, 13.46706000, 14.71363000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105126', 'dr5hn-2026-07-29'),
  (105122, 'Beïnamar', 43, 3585, 8.66980000, 15.38130000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105122', 'dr5hn-2026-07-29'),
  (105121, 'Benoy', 43, 3585, 8.98327000, 16.31991000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105121', 'dr5hn-2026-07-29'),
  (105143, 'Lac Wey', 43, 3585, 8.70502000, 15.98303000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105143', 'dr5hn-2026-07-29'),
  (105151, 'Moundou', 43, 3585, 8.56667000, 16.08333000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105151', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (105129, 'Bébédja', 43, 3591, 8.67610000, 16.56600000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105129', 'dr5hn-2026-07-29'),
  (105128, 'Béboto', 43, 3591, 8.26681000, 16.93898000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105128', 'dr5hn-2026-07-29'),
  (105131, 'Doba', 43, 3591, 8.65000000, 16.85000000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105131', 'dr5hn-2026-07-29'),
  (105134, 'Goundi', 43, 3589, 9.36267000, 17.36597000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105134', 'dr5hn-2026-07-29'),
  (105141, 'Koumra', 43, 3589, 8.91256000, 17.55392000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105141', 'dr5hn-2026-07-29'),
  (105153, 'Moïssala', 43, 3589, 8.34040000, 17.76630000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105153', 'dr5hn-2026-07-29'),
  (105127, 'Bongor', 43, 3580, 10.28056000, 15.37222000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105127', 'dr5hn-2026-07-29'),
  (105135, 'Gounou Gaya', 43, 3580, 9.62940000, 15.51320000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105135', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (105138, 'Guelendeng', 43, 3580, 10.91762000, 15.55011000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105138', 'dr5hn-2026-07-29'),
  (105148, 'Mboursou Léré', 43, 3571, 9.76390000, 14.15390000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105148', 'dr5hn-2026-07-29'),
  (105155, 'Pala', 43, 3571, 9.36420000, 14.90460000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105155', 'dr5hn-2026-07-29'),
  (105142, 'Kyabé', 43, 3570, 9.45149000, 18.94493000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105142', 'dr5hn-2026-07-29'),
  (105156, 'Sarh', 43, 3570, 9.14290000, 18.39230000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105156', 'dr5hn-2026-07-29'),
  (153264, 'N''Djamena', 43, 3586, 12.11000000, 15.05000000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:153264', 'dr5hn-2026-07-29'),
  (105116, 'Abéché', 43, 3582, 13.82916000, 20.83240000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105116', 'dr5hn-2026-07-29'),
  (105117, 'Adré', 43, 3582, 13.46648000, 22.19875000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105117', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (105137, 'Goz Béïda', 43, 3582, 13.94563000, 20.54680000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105137', 'dr5hn-2026-07-29'),
  (105118, 'Am Timan', 43, 3592, 11.02970000, 20.28270000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105118', 'dr5hn-2026-07-29'),
  (105136, 'Goz Beïda', 43, 3572, 12.22484000, 21.41034000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105136', 'dr5hn-2026-07-29'),
  (105130, 'Béré', 43, 3579, 9.32020000, 16.15520000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105130', 'dr5hn-2026-07-29'),
  (105140, 'Kelo', 43, 3579, 9.30859000, 15.80658000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105140', 'dr5hn-2026-07-29'),
  (105144, 'Laï', 43, 3579, 9.39720000, 16.30066000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105144', 'dr5hn-2026-07-29'),
  (105119, 'Aozou', 43, 3587, 21.83750000, 17.42750000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105119', 'dr5hn-2026-07-29'),
  (105123, 'Biltine', 43, 3581, 14.52791000, 20.92749000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105123', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (105139, 'Iriba', 43, 3581, 15.11667000, 22.25000000, 'Africa/Ndjamena', NULL, NULL, 'city', 'dr5hn:105139', 'dr5hn-2026-07-29');
