-- Cities for TN (Tunisia): 165 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 21 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106915, 'Ariana', 224, 2550, 36.86012000, 10.19337000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106915', 'dr5hn-2026-07-29'),
  (153381, 'Ettadhamen-Mnihla', 224, 2550, 36.86250000, 10.17030000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153381', 'dr5hn-2026-07-29'),
  (106955, 'Kalaat el-Andalous', 224, 2550, 36.88110000, 10.26220000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106955', 'dr5hn-2026-07-29'),
  (153380, 'La Soukra', 224, 2550, 36.85350000, 10.25250000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153380', 'dr5hn-2026-07-29'),
  (153382, 'Mnihla', 224, 2550, 36.83690000, 10.20020000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153382', 'dr5hn-2026-07-29'),
  (153378, 'Raoued', 224, 2550, 36.88500000, 10.24650000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153378', 'dr5hn-2026-07-29'),
  (153379, 'Sidi Thabet', 224, 2550, 36.83990000, 10.04030000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153379', 'dr5hn-2026-07-29'),
  (153377, 'Amdoun', 224, 2572, 36.74420000, 9.05130000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153377', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106930, 'Béja', 224, 2572, 36.72564000, 9.18169000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106930', 'dr5hn-2026-07-29'),
  (106956, 'Goubellat', 224, 2572, 36.59560000, 9.20780000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106956', 'dr5hn-2026-07-29'),
  (106986, 'Medjez el Bab', 224, 2572, 36.70640000, 9.61060000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106986', 'dr5hn-2026-07-29'),
  (106940, 'Nefza', 224, 2572, 36.60490000, 8.97020000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106940', 'dr5hn-2026-07-29'),
  (107031, 'Tabursuq', 224, 2572, 36.45692000, 9.24751000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107031', 'dr5hn-2026-07-29'),
  (153376, 'Téboursouk', 224, 2572, 36.71040000, 9.00080000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153376', 'dr5hn-2026-07-29'),
  (107035, 'Testour', 224, 2572, 36.50140000, 9.66640000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107035', 'dr5hn-2026-07-29'),
  (153375, 'Thibar', 224, 2572, 36.46560000, 9.06220000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153375', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106920, 'Ben Arous', 224, 2566, 36.75310000, 10.22940000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106920', 'dr5hn-2026-07-29'),
  (106959, 'Hammam Lif', 224, 2566, 36.72030000, 10.32610000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106959', 'dr5hn-2026-07-29'),
  (106977, 'Mornag', 224, 2566, 36.66160000, 10.14630000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106977', 'dr5hn-2026-07-29'),
  (106961, 'Mornaguia', 224, 2566, 36.72140000, 10.04940000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106961', 'dr5hn-2026-07-29'),
  (107007, 'Radès', 224, 2566, 36.76946000, 10.27468000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107007', 'dr5hn-2026-07-29'),
  (106913, 'Al Matlīn', 224, 2551, 37.24516000, 10.05000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106913', 'dr5hn-2026-07-29'),
  (106926, 'Bizerte', 224, 2551, 37.27442000, 9.87391000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106926', 'dr5hn-2026-07-29'),
  (106927, 'Bizerte Sud', 224, 2551, 37.25528000, 9.67915000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106927', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106938, 'Douar Tindja', 224, 2551, 37.16667000, 9.75000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106938', 'dr5hn-2026-07-29'),
  (106941, 'El Alia', 224, 2551, 37.16911000, 10.03478000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106941', 'dr5hn-2026-07-29'),
  (106983, 'Mateur', 224, 2551, 37.04045000, 9.66557000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106983', 'dr5hn-2026-07-29'),
  (106988, 'Menzel Abderhaman', 224, 2551, 37.23737000, 9.86313000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106988', 'dr5hn-2026-07-29'),
  (106989, 'Menzel Bourguiba', 224, 2551, 37.15368000, 9.78594000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106989', 'dr5hn-2026-07-29'),
  (106990, 'Menzel Jemil', 224, 2551, 37.23618000, 9.91448000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106990', 'dr5hn-2026-07-29'),
  (107008, 'Rafrāf', 224, 2551, 37.19043000, 10.18365000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107008', 'dr5hn-2026-07-29'),
  (107010, 'Rhar el Melah', 224, 2551, 37.16939000, 10.19064000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107010', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (107017, 'Sejenane', 224, 2551, 37.05722000, 9.23806000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107017', 'dr5hn-2026-07-29'),
  (107041, 'Zahānah', 224, 2551, 37.03959000, 10.03876000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107041', 'dr5hn-2026-07-29'),
  (106929, 'Bou Attouche', 224, 2558, 33.89927000, 9.78496000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106929', 'dr5hn-2026-07-29'),
  (106945, 'El Hamma', 224, 2558, 33.89152000, 9.79629000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106945', 'dr5hn-2026-07-29'),
  (106952, 'Gabès', 224, 2558, 33.88146000, 10.09820000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106952', 'dr5hn-2026-07-29'),
  (106984, 'Matmata', 224, 2558, 33.54445000, 9.97157000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106984', 'dr5hn-2026-07-29'),
  (106914, 'Ar Rudayyif', 224, 2556, 34.38270000, 8.15549000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106914', 'dr5hn-2026-07-29'),
  (106916, 'As Sanad', 224, 2556, 34.46280000, 9.26404000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106916', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106954, 'Gafsa', 224, 2556, 34.42500000, 8.78417000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106954', 'dr5hn-2026-07-29'),
  (106994, 'Metlaoui', 224, 2556, 34.32081000, 8.40157000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106994', 'dr5hn-2026-07-29'),
  (107000, 'Mu‘tamadīyat ar Rudayyif', 224, 2556, 34.40081000, 8.17057000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107000', 'dr5hn-2026-07-29'),
  (106951, 'Fernana', 224, 2552, 36.65547000, 8.69602000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106951', 'dr5hn-2026-07-29'),
  (106965, 'Jendouba', 224, 2552, 36.48519000, 8.82325000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106965', 'dr5hn-2026-07-29'),
  (107005, 'Oued Meliz', 224, 2552, 36.46813000, 8.54951000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107005', 'dr5hn-2026-07-29'),
  (107030, 'Tabarka', 224, 2552, 36.95442000, 8.75801000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107030', 'dr5hn-2026-07-29'),
  (106958, 'Haffouz', 224, 2564, 35.63235000, 9.67624000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106958', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106968, 'Kairouan', 224, 2564, 35.67810000, 10.09633000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106968', 'dr5hn-2026-07-29'),
  (107016, 'Sbikha', 224, 2564, 35.93325000, 10.02081000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107016', 'dr5hn-2026-07-29'),
  (106969, 'Kasserine', 224, 2570, 35.16758000, 8.83651000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106969', 'dr5hn-2026-07-29'),
  (107011, 'Rohia', 224, 2570, 35.65129000, 9.05306000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107011', 'dr5hn-2026-07-29'),
  (107015, 'Sbiba', 224, 2570, 35.54332000, 9.07370000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107015', 'dr5hn-2026-07-29'),
  (107036, 'Thala', 224, 2570, 35.57244000, 8.67031000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107036', 'dr5hn-2026-07-29'),
  (106939, 'Douz', 224, 2562, 33.46632000, 9.02030000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106939', 'dr5hn-2026-07-29'),
  (106944, 'El Golaa', 224, 2562, 33.48485000, 9.00678000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106944', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106964, 'Jemna', 224, 2562, 33.57778000, 9.01472000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106964', 'dr5hn-2026-07-29'),
  (106970, 'Kebili', 224, 2562, 33.70439000, 8.96903000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106970', 'dr5hn-2026-07-29'),
  (106917, 'As Sars', 224, 2561, 36.07640000, 9.02117000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106917', 'dr5hn-2026-07-29'),
  (106947, 'El Kef', 224, 2561, 36.17424000, 8.70486000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106947', 'dr5hn-2026-07-29'),
  (106948, 'El Ksour', 224, 2561, 35.89607000, 8.88493000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106948', 'dr5hn-2026-07-29'),
  (106992, 'Menzel Salem', 224, 2561, 35.85673000, 8.47654000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106992', 'dr5hn-2026-07-29'),
  (107002, 'Nibbar', 224, 2561, 36.29411000, 8.76657000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107002', 'dr5hn-2026-07-29'),
  (107013, 'Sakiet Sidi Youssef', 224, 2561, 36.22292000, 8.35547000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107013', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (107032, 'Tajerouine', 224, 2561, 35.89174000, 8.55276000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107032', 'dr5hn-2026-07-29'),
  (106932, 'Chebba', 224, 2568, 35.23722000, 11.11500000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106932', 'dr5hn-2026-07-29'),
  (106934, 'Chorbane', 224, 2568, 35.28581000, 10.38580000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106934', 'dr5hn-2026-07-29'),
  (106946, 'El Jem', 224, 2568, 35.30000000, 10.71667000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106946', 'dr5hn-2026-07-29'),
  (106974, 'Ksour Essaf', 224, 2568, 35.41808000, 10.99475000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106974', 'dr5hn-2026-07-29'),
  (106980, 'Mahdia', 224, 2568, 35.50472000, 11.06222000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106980', 'dr5hn-2026-07-29'),
  (106987, 'Melloulèche', 224, 2568, 35.16617000, 11.03504000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106987', 'dr5hn-2026-07-29'),
  (107014, 'Salakta', 224, 2568, 35.39444000, 11.04361000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107014', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (107020, 'Sidi Alouane', 224, 2568, 35.37505000, 10.93899000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107020', 'dr5hn-2026-07-29'),
  (107043, 'Zouila', 224, 2568, 35.50056000, 11.06056000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107043', 'dr5hn-2026-07-29'),
  (106942, 'El Battan', 224, 2555, 36.80368000, 9.84424000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106942', 'dr5hn-2026-07-29'),
  (106982, 'Manouba', 224, 2555, 36.81006000, 10.09557000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106982', 'dr5hn-2026-07-29'),
  (106999, 'Mu‘tamadīyat Manūbah', 224, 2555, 36.80907000, 10.09467000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106999', 'dr5hn-2026-07-29'),
  (107004, 'Oued Lill', 224, 2555, 36.83408000, 10.04057000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107004', 'dr5hn-2026-07-29'),
  (106921, 'Ben Gardane', 224, 2560, 33.13783000, 11.21965000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106921', 'dr5hn-2026-07-29'),
  (106923, 'Beni Kheddache', 224, 2560, 33.25279000, 10.19883000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106923', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106950, 'Erriadh', 224, 2560, 33.82063000, 10.85394000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106950', 'dr5hn-2026-07-29'),
  (106963, 'Houmt El Souk', 224, 2560, 33.87576000, 10.85745000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106963', 'dr5hn-2026-07-29'),
  (106966, 'Jerba Midoun', 224, 2560, 33.77918000, 10.95215000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106966', 'dr5hn-2026-07-29'),
  (106985, 'Medenine', 224, 2560, 33.35495000, 10.50548000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106985', 'dr5hn-2026-07-29'),
  (106996, 'Midoun', 224, 2560, 33.80813000, 10.99228000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106996', 'dr5hn-2026-07-29'),
  (107042, 'Zarzis', 224, 2560, 33.50398000, 11.11215000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107042', 'dr5hn-2026-07-29'),
  (106918, 'Banbalah', 224, 2553, 35.70000000, 10.80000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106918', 'dr5hn-2026-07-29'),
  (106919, 'Bekalta', 224, 2553, 35.61739000, 10.99466000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106919', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106922, 'Beni Hassane', 224, 2553, 35.56720000, 10.80869000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106922', 'dr5hn-2026-07-29'),
  (106937, 'Djemmal', 224, 2553, 35.62231000, 10.75696000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106937', 'dr5hn-2026-07-29'),
  (106972, 'Ksar Hellal', 224, 2553, 35.64773000, 10.89046000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106972', 'dr5hn-2026-07-29'),
  (106973, 'Ksibet el Mediouni', 224, 2553, 35.68561000, 10.84256000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106973', 'dr5hn-2026-07-29'),
  (106979, 'Lemta', 224, 2553, 35.66667000, 10.88333000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106979', 'dr5hn-2026-07-29'),
  (106991, 'Menzel Kamel', 224, 2553, 35.62477000, 10.66727000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106991', 'dr5hn-2026-07-29'),
  (106993, 'Mesdour', 224, 2553, 35.68206000, 10.72746000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106993', 'dr5hn-2026-07-29'),
  (106997, 'Monastir', 224, 2553, 35.77799000, 10.82617000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106997', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (107003, 'Ouardenine', 224, 2553, 35.70915000, 10.67397000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107003', 'dr5hn-2026-07-29'),
  (107012, 'Sahline', 224, 2553, 35.75166000, 10.71109000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107012', 'dr5hn-2026-07-29'),
  (107018, 'Seïada', 224, 2553, 35.66887000, 10.89246000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107018', 'dr5hn-2026-07-29'),
  (107021, 'Sidi Ben Nour', 224, 2553, 35.53333000, 10.91667000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107021', 'dr5hn-2026-07-29'),
  (107027, 'Skanes', 224, 2553, 35.78333000, 10.80000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107027', 'dr5hn-2026-07-29'),
  (107037, 'Touza', 224, 2553, 35.63544000, 10.82732000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107037', 'dr5hn-2026-07-29'),
  (153265, 'Azmour', 224, 5116, 36.92440000, 11.00690000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153265', 'dr5hn-2026-07-29'),
  (153266, 'Beni Khalled', 224, 5116, 36.65038000, 10.59004000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153266', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153268, 'Béni Khiar', 224, 5116, 36.46666667, 10.78333333, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153268', 'dr5hn-2026-07-29'),
  (153267, 'Bou Argoub', 224, 5116, 36.53853000, 10.55093000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153267', 'dr5hn-2026-07-29'),
  (153269, 'Dar Chaabane', 224, 5116, 36.47000000, 10.75000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153269', 'dr5hn-2026-07-29'),
  (153270, 'El Haouaria', 224, 5116, 37.05000000, 11.01111111, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153270', 'dr5hn-2026-07-29'),
  (153271, 'El Maâmoura', 224, 5116, 36.46666667, 10.80000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153271', 'dr5hn-2026-07-29'),
  (153272, 'El Mida', 224, 5116, 36.73333333, 10.85000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153272', 'dr5hn-2026-07-29'),
  (153273, 'El Mrezga', 224, 5116, 36.42163000, 10.66411000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153273', 'dr5hn-2026-07-29'),
  (153274, 'Grombalia', 224, 5116, 36.61000000, 10.50000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153274', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153275, 'Hammamet', 224, 5116, 36.41666667, 10.60000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153275', 'dr5hn-2026-07-29'),
  (153276, 'Kelibia', 224, 5116, 36.84750000, 11.09388889, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153276', 'dr5hn-2026-07-29'),
  (153277, 'Korba', 224, 5116, 36.56666667, 10.86666667, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153277', 'dr5hn-2026-07-29'),
  (153278, 'Korbous', 224, 5116, 36.81638889, 10.56861111, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153278', 'dr5hn-2026-07-29'),
  (153279, 'Menzel Bouzelfa', 224, 5116, 36.68170000, 10.58470000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153279', 'dr5hn-2026-07-29'),
  (153280, 'Menzel Horr', 224, 5116, 36.73333333, 10.95000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153280', 'dr5hn-2026-07-29'),
  (153281, 'Menzel Temime', 224, 5116, 36.78333333, 10.98333333, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153281', 'dr5hn-2026-07-29'),
  (153282, 'Nabeul', 224, 5116, 36.45138900, 10.73611100, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153282', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (153283, 'Soliman', 224, 5116, 36.69512600, 10.49125700, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153283', 'dr5hn-2026-07-29'),
  (153284, 'Takelsa', 224, 5116, 36.79000000, 10.63000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153284', 'dr5hn-2026-07-29'),
  (153285, 'Tazerka', 224, 5116, 36.55000000, 10.80000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153285', 'dr5hn-2026-07-29'),
  (153286, 'Zaouiet Djedidi', 224, 5116, 36.65000000, 10.60000000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153286', 'dr5hn-2026-07-29'),
  (153287, 'Zriba', 224, 5116, 36.35585000, 10.20603400, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:153287', 'dr5hn-2026-07-29'),
  (106910, 'Agareb', 224, 2557, 34.74406000, 10.46110000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106910', 'dr5hn-2026-07-29'),
  (106924, 'Bir Ali Ben Khalifa', 224, 2557, 34.73592000, 10.09240000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106924', 'dr5hn-2026-07-29'),
  (106936, 'Djebeniana', 224, 2557, 35.03500000, 10.90809000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106936', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106957, 'Gremda', 224, 2557, 34.75000000, 10.78333000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106957', 'dr5hn-2026-07-29'),
  (107019, 'Sfax', 224, 2557, 34.74056000, 10.76028000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107019', 'dr5hn-2026-07-29'),
  (107028, 'Skhira', 224, 2557, 34.29920000, 10.06999000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107028', 'dr5hn-2026-07-29'),
  (106925, 'Bir el Hafey', 224, 2567, 34.93212000, 9.19321000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106925', 'dr5hn-2026-07-29'),
  (106949, 'Er Regueb', 224, 2567, 34.85932000, 9.78654000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106949', 'dr5hn-2026-07-29'),
  (106967, 'Jilma', 224, 2567, 35.27311000, 9.42385000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106967', 'dr5hn-2026-07-29'),
  (106995, 'Mezzouna', 224, 2567, 34.57758000, 9.84193000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106995', 'dr5hn-2026-07-29'),
  (107024, 'Sidi Bouzid', 224, 2567, 35.03823000, 9.48494000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107024', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106928, 'Bou Arada', 224, 2563, 36.35251000, 9.62175000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106928', 'dr5hn-2026-07-29'),
  (106953, 'Gafour', 224, 2563, 36.32045000, 9.32424000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106953', 'dr5hn-2026-07-29'),
  (106971, 'Kesra', 224, 2563, 35.81363000, 9.36434000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106971', 'dr5hn-2026-07-29'),
  (106978, 'Le Krib', 224, 2563, 36.32802000, 9.13613000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106978', 'dr5hn-2026-07-29'),
  (106981, 'Maktar', 224, 2563, 35.85798000, 9.20072000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106981', 'dr5hn-2026-07-29'),
  (107026, 'Siliana', 224, 2563, 36.08497000, 9.37082000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107026', 'dr5hn-2026-07-29'),
  (106911, 'Akouda', 224, 2571, 35.86910000, 10.56530000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106911', 'dr5hn-2026-07-29'),
  (106960, 'Hammam Sousse', 224, 2571, 35.86090000, 10.60313000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106960', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106962, 'Harqalah', 224, 2571, 36.03027000, 10.50904000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106962', 'dr5hn-2026-07-29'),
  (106998, 'Msaken', 224, 2571, 35.72917000, 10.58082000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106998', 'dr5hn-2026-07-29'),
  (107006, 'Port el Kantaoui', 224, 2571, 35.89239000, 10.59434000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107006', 'dr5hn-2026-07-29'),
  (107022, 'Sidi Bou Ali', 224, 2571, 35.95667000, 10.47306000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107022', 'dr5hn-2026-07-29'),
  (107025, 'Sidi el Hani', 224, 2571, 35.67139000, 10.31583000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107025', 'dr5hn-2026-07-29'),
  (107029, 'Sousse', 224, 2571, 35.82539000, 10.63699000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107029', 'dr5hn-2026-07-29'),
  (107009, 'Remada', 224, 2559, 32.31662000, 10.39551000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107009', 'dr5hn-2026-07-29'),
  (107034, 'Tataouine', 224, 2559, 32.92967000, 10.45177000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107034', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106933, 'Chebika', 224, 2569, 34.31909000, 7.93519000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106933', 'dr5hn-2026-07-29'),
  (106935, 'Degache', 224, 2569, 33.97606000, 8.20810000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106935', 'dr5hn-2026-07-29'),
  (107001, 'Nefta', 224, 2569, 33.87309000, 7.87765000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107001', 'dr5hn-2026-07-29'),
  (107033, 'Tamaghzah', 224, 2569, 34.38849000, 7.94313000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107033', 'dr5hn-2026-07-29'),
  (107038, 'Tozeur', 224, 2569, 33.91968000, 8.13352000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107038', 'dr5hn-2026-07-29'),
  (106912, 'Al Marsá', 224, 2554, 36.87818000, 10.32466000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106912', 'dr5hn-2026-07-29'),
  (106931, 'Carthage', 224, 2554, 36.85961000, 10.32978000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106931', 'dr5hn-2026-07-29'),
  (106975, 'La Goulette', 224, 2554, 36.81825000, 10.30520000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106975', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (106976, 'La Mohammedia', 224, 2554, 36.67446000, 10.15633000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106976', 'dr5hn-2026-07-29'),
  (107023, 'Sidi Bou Saïd', 224, 2554, 36.86870000, 10.34174000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107023', 'dr5hn-2026-07-29'),
  (107039, 'Tunis', 224, 2554, 36.81897000, 10.16579000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107039', 'dr5hn-2026-07-29'),
  (106943, 'El Fahs', 224, 2565, 36.37419000, 9.90651000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:106943', 'dr5hn-2026-07-29'),
  (107040, 'Zaghouan', 224, 2565, 36.40291000, 10.14292000, 'Africa/Tunis', NULL, NULL, 'city', 'dr5hn:107040', 'dr5hn-2026-07-29');
