-- Cities for UG (Uganda): 91 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 12 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110880, 'Bukomansimbi', 229, 396, -0.12855000, 31.62527000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110880', 'dr5hn-2026-07-29'),
  (110886, 'Buvuma', 229, 396, -0.36744000, 33.20071000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110886', 'dr5hn-2026-07-29'),
  (110888, 'Bweyogerere', 229, 396, 0.35773000, 32.66332000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110888', 'dr5hn-2026-07-29'),
  (110890, 'Byakabanda', 229, 396, -0.74250000, 31.40639000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110890', 'dr5hn-2026-07-29'),
  (110891, 'Entebbe', 229, 396, 0.05621000, 32.47949000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110891', 'dr5hn-2026-07-29'),
  (110893, 'Gomba', 229, 396, 0.20017000, 31.75023000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110893', 'dr5hn-2026-07-29'),
  (110902, 'Kajansi', 229, 396, 0.21548000, 32.53453000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110902', 'dr5hn-2026-07-29'),
  (110903, 'Kampala', 229, 396, 0.31628000, 32.58219000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110903', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110904, 'Kampala District', 229, 396, 0.33508000, 32.58313000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110904', 'dr5hn-2026-07-29'),
  (110907, 'Kanoni', 229, 396, 0.17722000, 31.88111000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110907', 'dr5hn-2026-07-29'),
  (110911, 'Kayunga', 229, 396, 0.70250000, 32.88861000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110911', 'dr5hn-2026-07-29'),
  (110913, 'Kiboga', 229, 396, 0.91611000, 31.77417000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110913', 'dr5hn-2026-07-29'),
  (110917, 'Kireka', 229, 396, 0.34750000, 32.64917000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110917', 'dr5hn-2026-07-29'),
  (110924, 'Kyotera', 229, 396, -0.61556000, 31.51750000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110924', 'dr5hn-2026-07-29'),
  (110926, 'Lugazi', 229, 396, 0.36788000, 32.93760000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110926', 'dr5hn-2026-07-29'),
  (110927, 'Luwero', 229, 396, 0.84917000, 32.47306000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110927', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110928, 'Lyantonde', 229, 396, -0.40306000, 31.15722000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110928', 'dr5hn-2026-07-29'),
  (110930, 'Masaka', 229, 396, -0.33379000, 31.73409000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110930', 'dr5hn-2026-07-29'),
  (110936, 'Mityana', 229, 396, 0.41750000, 32.02278000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110936', 'dr5hn-2026-07-29'),
  (110939, 'Mpigi', 229, 396, 0.22500000, 32.31361000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110939', 'dr5hn-2026-07-29'),
  (110940, 'Mubende', 229, 396, 0.55849000, 31.39489000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110940', 'dr5hn-2026-07-29'),
  (110941, 'Mubende District', 229, 396, 0.50000000, 31.50000000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110941', 'dr5hn-2026-07-29'),
  (110943, 'Mukono', 229, 396, 0.35333000, 32.75528000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110943', 'dr5hn-2026-07-29'),
  (110944, 'Nakasongola', 229, 396, 1.30889000, 32.45639000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110944', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110945, 'Namasuba', 229, 396, 0.68944000, 32.42139000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110945', 'dr5hn-2026-07-29'),
  (110947, 'Njeru', 229, 396, 0.44166000, 33.17917000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110947', 'dr5hn-2026-07-29'),
  (110957, 'Sembabule', 229, 396, -0.07722000, 31.45667000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110957', 'dr5hn-2026-07-29'),
  (110961, 'Wakiso', 229, 396, 0.40444000, 32.45944000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110961', 'dr5hn-2026-07-29'),
  (110962, 'Wakiso District', 229, 396, 0.23763000, 32.47836000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110962', 'dr5hn-2026-07-29'),
  (110963, 'Wobulenzi', 229, 396, 0.72833000, 32.51222000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110963', 'dr5hn-2026-07-29'),
  (110878, 'Bugembe', 229, 372, 0.48213000, 33.24065000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110878', 'dr5hn-2026-07-29'),
  (110879, 'Bugiri', 229, 372, 0.57139000, 33.74167000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110879', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110881, 'Bukwa', 229, 372, 1.27115000, 34.66778000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110881', 'dr5hn-2026-07-29'),
  (110882, 'Bulambuli', 229, 372, 1.32055000, 34.28062000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110882', 'dr5hn-2026-07-29'),
  (110884, 'Busembatia', 229, 372, 0.77725000, 33.62364000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110884', 'dr5hn-2026-07-29'),
  (110885, 'Busia', 229, 372, 0.46588000, 34.09221000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110885', 'dr5hn-2026-07-29'),
  (110887, 'Buwenge', 229, 372, 0.64996000, 33.17128000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110887', 'dr5hn-2026-07-29'),
  (110898, 'Iganga', 229, 372, 0.60917000, 33.46861000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110898', 'dr5hn-2026-07-29'),
  (110899, 'Jinja', 229, 372, 0.43902000, 33.20317000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110899', 'dr5hn-2026-07-29'),
  (110905, 'Kamuli', 229, 372, 0.94722000, 33.11972000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110905', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110909, 'Kapchorwa', 229, 372, 1.40096000, 34.45038000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110909', 'dr5hn-2026-07-29'),
  (110914, 'Kibuku', 229, 372, 1.05000000, 33.80879000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110914', 'dr5hn-2026-07-29'),
  (110922, 'Kumi', 229, 372, 1.46083000, 33.93611000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110922', 'dr5hn-2026-07-29'),
  (110933, 'Mayuge', 229, 372, 0.45972000, 33.48028000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110933', 'dr5hn-2026-07-29'),
  (110934, 'Mbale', 229, 372, 1.08209000, 34.17503000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110934', 'dr5hn-2026-07-29'),
  (110955, 'Pallisa', 229, 372, 1.14500000, 33.70944000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110955', 'dr5hn-2026-07-29'),
  (110958, 'Sironko', 229, 372, 1.23132000, 34.24773000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110958', 'dr5hn-2026-07-29'),
  (110959, 'Soroti', 229, 372, 1.71464000, 33.61113000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110959', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110960, 'Tororo', 229, 372, 0.69299000, 34.18085000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110960', 'dr5hn-2026-07-29'),
  (110874, 'Adjumani', 229, 332, 3.37786000, 31.79090000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110874', 'dr5hn-2026-07-29'),
  (110875, 'Amudat', 229, 332, 1.95000000, 34.95000000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110875', 'dr5hn-2026-07-29'),
  (110876, 'Apac', 229, 332, 1.97556000, 32.53861000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110876', 'dr5hn-2026-07-29'),
  (110877, 'Arua', 229, 332, 3.02013000, 30.91105000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110877', 'dr5hn-2026-07-29'),
  (110894, 'Gulu', 229, 332, 2.77457000, 32.29899000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110894', 'dr5hn-2026-07-29'),
  (110920, 'Kitgum', 229, 332, 3.27833000, 32.88667000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110920', 'dr5hn-2026-07-29'),
  (110921, 'Kotido', 229, 332, 2.98056000, 34.13306000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110921', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110925, 'Lira', 229, 332, 2.24990000, 32.89985000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110925', 'dr5hn-2026-07-29'),
  (110937, 'Moroto', 229, 332, 2.53453000, 34.66659000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110937', 'dr5hn-2026-07-29'),
  (110938, 'Moyo', 229, 332, 3.66088000, 31.72474000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110938', 'dr5hn-2026-07-29'),
  (110946, 'Nebbi', 229, 332, 2.47826000, 31.08893000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110946', 'dr5hn-2026-07-29'),
  (110950, 'Otuke', 229, 332, 2.48372000, 33.34201000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110950', 'dr5hn-2026-07-29'),
  (110951, 'Oyam', 229, 332, 2.38129000, 32.50071000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110951', 'dr5hn-2026-07-29'),
  (110952, 'Pader', 229, 332, 3.05000000, 33.21667000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110952', 'dr5hn-2026-07-29'),
  (110953, 'Pader Palwo', 229, 332, 2.80056000, 33.13500000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110953', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110954, 'Paidha', 229, 332, 2.41669000, 30.98551000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110954', 'dr5hn-2026-07-29'),
  (110964, 'Yumbe', 229, 332, 3.46506000, 31.24689000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110964', 'dr5hn-2026-07-29'),
  (110883, 'Bundibugyo', 229, 370, 0.71117000, 30.06469000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110883', 'dr5hn-2026-07-29'),
  (110889, 'Bwizibwera', 229, 370, -0.59167000, 30.62861000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110889', 'dr5hn-2026-07-29'),
  (110892, 'Fort Portal', 229, 370, 0.66174000, 30.27480000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110892', 'dr5hn-2026-07-29'),
  (110895, 'Hoima', 229, 370, 1.43314000, 31.35241000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110895', 'dr5hn-2026-07-29'),
  (110896, 'Ibanda', 229, 370, -0.13398000, 30.49616000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110896', 'dr5hn-2026-07-29'),
  (110897, 'Ibanda District', 229, 370, -0.08100000, 30.55600000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110897', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110900, 'Kabale', 229, 370, -1.24857000, 29.98993000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110900', 'dr5hn-2026-07-29'),
  (110901, 'Kagadi', 229, 370, 0.93778000, 30.80889000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110901', 'dr5hn-2026-07-29'),
  (110906, 'Kamwenge', 229, 370, 0.18660000, 30.45393000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110906', 'dr5hn-2026-07-29'),
  (110908, 'Kanungu', 229, 370, -0.95750000, 29.78972000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110908', 'dr5hn-2026-07-29'),
  (110910, 'Kasese', 229, 370, 0.18333000, 30.08333000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110910', 'dr5hn-2026-07-29'),
  (110912, 'Kibale', 229, 370, 0.80000000, 31.06667000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110912', 'dr5hn-2026-07-29'),
  (110915, 'Kigorobya', 229, 370, 1.61620000, 31.30890000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110915', 'dr5hn-2026-07-29'),
  (110916, 'Kilembe', 229, 370, 0.19835000, 30.01302000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110916', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110918, 'Kiruhura', 229, 370, -0.19664000, 30.84446000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110918', 'dr5hn-2026-07-29'),
  (110919, 'Kisoro', 229, 370, -1.28538000, 29.68497000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110919', 'dr5hn-2026-07-29'),
  (110923, 'Kyenjojo', 229, 370, 0.63278000, 30.62139000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110923', 'dr5hn-2026-07-29'),
  (110929, 'Margherita', 229, 370, 0.41861000, 29.89111000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110929', 'dr5hn-2026-07-29'),
  (110931, 'Masindi', 229, 370, 1.67444000, 31.71500000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110931', 'dr5hn-2026-07-29'),
  (110932, 'Masindi Port', 229, 370, 1.69606000, 32.08608000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110932', 'dr5hn-2026-07-29'),
  (110935, 'Mbarara', 229, 370, -0.60467000, 30.64851000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110935', 'dr5hn-2026-07-29'),
  (110942, 'Muhororo', 229, 370, 0.93806000, 30.75944000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110942', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (110948, 'Ntungamo', 229, 370, -0.87944000, 30.26417000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110948', 'dr5hn-2026-07-29'),
  (110949, 'Nyachera', 229, 370, -0.90000000, 30.41667000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110949', 'dr5hn-2026-07-29'),
  (110956, 'Rukungiri', 229, 370, -0.84111000, 29.94194000, 'Africa/Kampala', NULL, NULL, 'city', 'dr5hn:110956', 'dr5hn-2026-07-29');
