-- Cities for WS (Samoa): 20 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130647, 'Fasito‘outa', 191, 4763, -13.81163000, -171.94063000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130647', 'dr5hn-2026-07-29'),
  (130649, 'Leulumoega', 191, 4763, -13.82297000, -171.96127000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130649', 'dr5hn-2026-07-29'),
  (130655, 'Nofoali‘i', 191, 4763, -13.82170000, -171.95873000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130655', 'dr5hn-2026-07-29'),
  (130658, 'Satapuala', 191, 4763, -13.83535000, -171.97963000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130658', 'dr5hn-2026-07-29'),
  (130654, 'Mulifanua', 191, 4761, -13.83183000, -172.03602000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130654', 'dr5hn-2026-07-29'),
  (130646, 'Falefa', 191, 4765, -13.88695000, -171.58805000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130646', 'dr5hn-2026-07-29'),
  (130650, 'Lotofagā', 191, 4765, -13.97643000, -171.85781000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130650', 'dr5hn-2026-07-29'),
  (130651, 'Lufilufi', 191, 4765, -13.87449000, -171.59857000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130651', 'dr5hn-2026-07-29');
  (130659, 'Solosolo', 191, 4765, -13.87504000, -171.64181000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130659', 'dr5hn-2026-07-29'),
  (130653, 'Matavai', 191, 4771, -14.03208000, -171.64768000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130653', 'dr5hn-2026-07-29'),
  (130656, 'Safotu', 191, 4771, -13.45132000, -172.40177000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130656', 'dr5hn-2026-07-29'),
  (130648, 'Gataivai', 191, 4767, -13.77360000, -172.38802000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130648', 'dr5hn-2026-07-29'),
  (130661, 'Vailoa', 191, 4767, -13.75551000, -172.30698000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130661', 'dr5hn-2026-07-29'),
  (130643, 'Afega', 191, 4770, -13.79726000, -171.85308000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130643', 'dr5hn-2026-07-29'),
  (130644, 'Apia', 191, 4770, -13.83333000, -171.76666000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130644', 'dr5hn-2026-07-29'),
  (130652, 'Malie', 191, 4770, -13.80044000, -171.84690000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130652', 'dr5hn-2026-07-29');
  (130660, 'Vailima', 191, 4770, -13.86417000, -171.76126000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130660', 'dr5hn-2026-07-29'),
  (130662, 'Vaiusu', 191, 4770, -13.82678000, -171.79333000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130662', 'dr5hn-2026-07-29'),
  (130657, 'Samamea', 191, 4768, -13.93375000, -171.53122000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130657', 'dr5hn-2026-07-29'),
  (130645, 'Asau', 191, 4766, -13.51963000, -172.63784000, 'Pacific/Apia', NULL, NULL, 'city', 'dr5hn:130645', 'dr5hn-2026-07-29');
