-- Cities for YE (Yemen): 339 cities from dr5hn
-- Generated by: scripts/seed/107_generate_cities.py
-- Split into 43 INSERT statements of 8 rows each (D1 ~100-var/INSERT limit)

INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130673, 'Ahwar', 245, 1237, 13.68530000, 46.75560000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130673', 'dr5hn-2026-07-29'),
  (130714, 'Al Mahfad', 245, 1237, 13.97050000, 46.75600000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130714', 'dr5hn-2026-07-29'),
  (130752, 'Al Wade''a', 245, 1237, 13.71360000, 46.01220000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130752', 'dr5hn-2026-07-29'),
  (130880, 'Jawf al Maqbābah', 245, 1237, 13.83783000, 45.83488000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130880', 'dr5hn-2026-07-29'),
  (130881, 'Jayshan', 245, 1237, 14.16620000, 46.17230000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130881', 'dr5hn-2026-07-29'),
  (130887, 'Khanfir', 245, 1237, 13.42049000, 45.68707000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130887', 'dr5hn-2026-07-29'),
  (130900, 'Lawdar', 245, 1237, 13.80590000, 45.80080000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130900', 'dr5hn-2026-07-29'),
  (130928, 'Mudiyah', 245, 1237, 13.90960000, 46.21960000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130928', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130952, 'Rasad', 245, 1237, 13.72310000, 45.28140000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130952', 'dr5hn-2026-07-29'),
  (130967, 'Sarar', 245, 1237, 13.58300000, 45.35080000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130967', 'dr5hn-2026-07-29'),
  (130981, 'Sibah', 245, 1237, 13.80910000, 45.40230000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130981', 'dr5hn-2026-07-29'),
  (131008, 'Zingibar', 245, 1237, 13.13420000, 45.43040000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131008', 'dr5hn-2026-07-29'),
  (131009, 'Zinjibār', 245, 1237, 13.12871000, 45.38073000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131009', 'dr5hn-2026-07-29'),
  (157058, 'Ad Dali''', 245, 5467, 13.70000000, 44.73000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:157058', 'dr5hn-2026-07-29'),
  (130669, 'Aden', 245, 1242, 12.77944000, 45.03667000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130669', 'dr5hn-2026-07-29'),
  (130683, 'Al Buraiqeh', 245, 1242, 12.80377000, 44.77615000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130683', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130719, 'Al Mansura', 245, 1242, 12.85320000, 44.97240000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130719', 'dr5hn-2026-07-29'),
  (130735, 'Al Mualla', 245, 1242, 12.65843000, 43.42743000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130735', 'dr5hn-2026-07-29'),
  (130789, 'Ash Shaikh Outhman', 245, 1242, 12.88640000, 45.01560000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130789', 'dr5hn-2026-07-29'),
  (130801, 'Attawahi', 245, 1242, 12.77410000, 44.99410000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130801', 'dr5hn-2026-07-29'),
  (130830, 'Craiter', 245, 1242, 12.77310000, 45.03810000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130830', 'dr5hn-2026-07-29'),
  (130831, 'Dar Sad', 245, 1242, 12.90700000, 44.97840000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130831', 'dr5hn-2026-07-29'),
  (130676, 'Al A''rsh', 245, 1240, 14.36560000, 44.77780000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130676', 'dr5hn-2026-07-29'),
  (130680, 'Al Bayda', 245, 1240, 13.98523000, 45.57272000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130680', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130682, 'Al Bayḑā’', 245, 1240, 13.93666000, 45.54822000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130682', 'dr5hn-2026-07-29'),
  (130717, 'Al Malagim', 245, 1240, 14.36540000, 45.38510000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130717', 'dr5hn-2026-07-29'),
  (130750, 'Al Quraishyah', 245, 1240, 14.60500000, 44.88960000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130750', 'dr5hn-2026-07-29'),
  (130769, 'Ar Ryashyyah', 245, 1240, 14.24240000, 44.77540000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130769', 'dr5hn-2026-07-29'),
  (130778, 'As Sawadiyah', 245, 1240, 14.45198000, 45.36973000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130778', 'dr5hn-2026-07-29'),
  (130781, 'As Sawma''ah', 245, 1240, 14.16670000, 45.83110000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130781', 'dr5hn-2026-07-29'),
  (130791, 'Ash Sharafayn', 245, 1240, 14.30697000, 45.12634000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130791', 'dr5hn-2026-07-29'),
  (130796, 'At Taffah', 245, 1240, 14.19830000, 45.35810000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130796', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130804, 'Az Zahir', 245, 1240, 13.99180000, 45.42180000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130804', 'dr5hn-2026-07-29'),
  (130837, 'Dhi Na''im', 245, 1240, 14.11110000, 45.46420000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130837', 'dr5hn-2026-07-29'),
  (130916, 'Maswarah', 245, 1240, 14.40270000, 45.70330000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130916', 'dr5hn-2026-07-29'),
  (130930, 'Mukayras', 245, 1240, 14.03200000, 45.79640000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130930', 'dr5hn-2026-07-29'),
  (130934, 'Na''man', 245, 1240, 14.59390000, 45.52860000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130934', 'dr5hn-2026-07-29'),
  (130936, 'Nati''', 245, 1240, 14.55390000, 45.58500000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130936', 'dr5hn-2026-07-29'),
  (130947, 'Radā‘', 245, 1240, 14.34000000, 44.90874000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130947', 'dr5hn-2026-07-29'),
  (130946, 'Radman Al Awad', 245, 1240, 14.48360000, 45.27440000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130946', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130959, 'Sabah', 245, 1240, 14.27590000, 44.67000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130959', 'dr5hn-2026-07-29'),
  (130998, 'Wald Rabi''', 245, 1240, 14.55574000, 44.90596000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130998', 'dr5hn-2026-07-29'),
  (130665, 'Ad Dahi', 245, 1241, 15.22320000, 43.19350000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130665', 'dr5hn-2026-07-29'),
  (130667, 'Ad Durayhimi', 245, 1241, 14.60460000, 43.07180000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130667', 'dr5hn-2026-07-29'),
  (130686, 'Al Garrahi', 245, 1241, 14.10580000, 43.40940000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130686', 'dr5hn-2026-07-29'),
  (130692, 'Al Hajjaylah', 245, 1241, 14.99070000, 43.58230000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130692', 'dr5hn-2026-07-29'),
  (130693, 'Al Hali', 245, 1241, 14.82500000, 43.00140000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130693', 'dr5hn-2026-07-29'),
  (130695, 'Al Hawak', 245, 1241, 14.76010000, 42.99780000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130695', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130757, 'Al Ḩudaydah', 245, 1241, 14.79781000, 42.95452000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130757', 'dr5hn-2026-07-29'),
  (130720, 'Al Mansuriyah', 245, 1241, 14.69030000, 43.36820000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130720', 'dr5hn-2026-07-29'),
  (130722, 'Al Marawi''ah', 245, 1241, 14.83460000, 43.19650000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130722', 'dr5hn-2026-07-29'),
  (130731, 'Al Mighlaf', 245, 1241, 15.31110000, 43.18360000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130731', 'dr5hn-2026-07-29'),
  (130733, 'Al Mina', 245, 1241, 14.80775000, 42.93732000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130733', 'dr5hn-2026-07-29'),
  (130740, 'Al Munirah', 245, 1241, 15.35280000, 42.90620000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130740', 'dr5hn-2026-07-29'),
  (130748, 'Al Qanawis', 245, 1241, 15.49206000, 43.13782000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130748', 'dr5hn-2026-07-29'),
  (130762, 'Alluheyah', 245, 1241, 15.63628000, 42.87157000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130762', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130777, 'As Salif', 245, 1241, 15.22882000, 42.72542000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130777', 'dr5hn-2026-07-29'),
  (130785, 'As Sukhnah', 245, 1241, 14.74840000, 43.33420000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130785', 'dr5hn-2026-07-29'),
  (130799, 'At Tuhayat', 245, 1241, 14.10994000, 43.15979000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130799', 'dr5hn-2026-07-29'),
  (130805, 'Az Zaydīyah', 245, 1241, 15.29586000, 43.06452000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130805', 'dr5hn-2026-07-29'),
  (130806, 'Az Zuhrah', 245, 1241, 15.71730000, 43.06370000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130806', 'dr5hn-2026-07-29'),
  (130829, 'Bājil', 245, 1241, 15.07561000, 43.17350000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130829', 'dr5hn-2026-07-29'),
  (130823, 'Bayt al Faqīh', 245, 1241, 14.48738000, 43.27815000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130823', 'dr5hn-2026-07-29'),
  (130828, 'Bura', 245, 1241, 14.89820000, 43.47530000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130828', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130863, 'Hays', 245, 1241, 13.93320000, 43.49840000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130863', 'dr5hn-2026-07-29'),
  (130877, 'Jabal Ra''s', 245, 1241, 14.03090000, 43.62780000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130877', 'dr5hn-2026-07-29'),
  (130884, 'Kamaran', 245, 1241, 15.36050000, 42.58540000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130884', 'dr5hn-2026-07-29'),
  (131006, 'Zabīd', 245, 1241, 14.27742000, 43.36841000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131006', 'dr5hn-2026-07-29'),
  (130758, 'Al ‘Inān', 245, 1243, 16.72189000, 44.31252000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130758', 'dr5hn-2026-07-29'),
  (130688, 'Al Ghayl', 245, 1243, 16.09140000, 44.68520000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130688', 'dr5hn-2026-07-29'),
  (130698, 'Al Hazm', 245, 1243, 16.03780000, 44.95850000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130698', 'dr5hn-2026-07-29'),
  (130699, 'Al Humaydat', 245, 1243, 16.46670000, 44.42990000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130699', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130706, 'Al Khalq', 245, 1243, 16.06810000, 44.79700000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130706', 'dr5hn-2026-07-29'),
  (130725, 'Al Maslub', 245, 1243, 16.09610000, 44.56670000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130725', 'dr5hn-2026-07-29'),
  (130726, 'Al Matammah', 245, 1243, 16.19840000, 44.39020000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130726', 'dr5hn-2026-07-29'),
  (130727, 'Al Maton', 245, 1243, 16.28720000, 44.63890000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130727', 'dr5hn-2026-07-29'),
  (130821, 'Barţ al ‘Anān', 245, 1243, 16.91972000, 44.51882000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130821', 'dr5hn-2026-07-29'),
  (130885, 'Khabb wa ash Sha''af', 245, 1243, 16.59750000, 45.78530000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130885', 'dr5hn-2026-07-29'),
  (130888, 'Kharab Al Marashi', 245, 1243, 16.61070000, 44.22550000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130888', 'dr5hn-2026-07-29'),
  (130950, 'Rajuzah', 245, 1243, 16.63420000, 44.50420000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130950', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130687, 'Al Ghaydah', 245, 1251, 16.26180000, 52.08160000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130687', 'dr5hn-2026-07-29'),
  (130689, 'Al Ghayz̧ah', 245, 1251, 16.20787000, 52.17605000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130689', 'dr5hn-2026-07-29'),
  (130724, 'Al Masilah', 245, 1251, 15.63990000, 50.64450000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130724', 'dr5hn-2026-07-29'),
  (130857, 'Hat', 245, 1251, 17.80310000, 51.67500000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130857', 'dr5hn-2026-07-29'),
  (130859, 'Hawf', 245, 1251, 16.69530000, 52.81820000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130859', 'dr5hn-2026-07-29'),
  (130870, 'Huswain', 245, 1251, 15.72300000, 51.91240000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130870', 'dr5hn-2026-07-29'),
  (130908, 'Man''ar', 245, 1251, 16.55050000, 50.98790000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130908', 'dr5hn-2026-07-29'),
  (130943, 'Qishn', 245, 1251, 15.69990000, 51.32400000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130943', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130968, 'Sayhut', 245, 1251, 15.53450000, 51.28690000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130968', 'dr5hn-2026-07-29'),
  (130974, 'Shahan', 245, 1251, 17.59230000, 52.59400000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130974', 'dr5hn-2026-07-29'),
  (130705, 'Al Khabt', 245, 1235, 15.48170000, 43.36770000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130705', 'dr5hn-2026-07-29'),
  (130715, 'Al Mahwait', 245, 1235, 15.41170000, 43.56630000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130715', 'dr5hn-2026-07-29'),
  (130729, 'Al Maḩwīt', 245, 1235, 15.47007000, 43.54481000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130729', 'dr5hn-2026-07-29'),
  (130768, 'Ar Rujum', 245, 1235, 15.41010000, 43.66060000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130768', 'dr5hn-2026-07-29'),
  (130808, 'Aţ Ţawīlah', 245, 1235, 15.44165000, 43.77484000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130808', 'dr5hn-2026-07-29'),
  (130817, 'Bani Sa''d', 245, 1235, 15.23550000, 43.51560000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130817', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130868, 'Hufash', 245, 1235, 15.37470000, 43.42650000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130868', 'dr5hn-2026-07-29'),
  (130925, 'Milhan', 245, 1235, 15.32240000, 43.33180000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130925', 'dr5hn-2026-07-29'),
  (130980, 'Shibām Kawkabān', 245, 1235, 15.50277000, 43.84237000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130980', 'dr5hn-2026-07-29'),
  (130964, 'Sanaa', 245, 1232, 15.35472000, 44.20667000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130964', 'dr5hn-2026-07-29'),
  (131013, '‘Amrān', 245, 1250, 15.65940000, 43.94385000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131013', 'dr5hn-2026-07-29'),
  (130679, 'Al Ashah', 245, 1250, 16.32400000, 43.78740000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130679', 'dr5hn-2026-07-29'),
  (130709, 'Al Madan', 245, 1250, 16.23280000, 43.63900000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130709', 'dr5hn-2026-07-29'),
  (130745, 'Al Qaflah', 245, 1250, 16.33859000, 43.70361000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130745', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130779, 'As Sawd', 245, 1250, 15.81340000, 43.77700000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130779', 'dr5hn-2026-07-29'),
  (130784, 'As Sudah', 245, 1250, 15.96640000, 43.77560000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130784', 'dr5hn-2026-07-29'),
  (130818, 'Bani Suraim', 245, 1250, 16.12530000, 43.96020000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130818', 'dr5hn-2026-07-29'),
  (130836, 'Dhi Bin', 245, 1250, 16.02760000, 44.15150000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130836', 'dr5hn-2026-07-29'),
  (130847, 'Habur Zulaymah', 245, 1250, 16.03500000, 43.73380000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130847', 'dr5hn-2026-07-29'),
  (130855, 'Harf Sufyan', 245, 1250, 16.41389000, 43.98571000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130855', 'dr5hn-2026-07-29'),
  (130866, 'Hooth', 245, 1250, 16.28397000, 43.97811000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130866', 'dr5hn-2026-07-29'),
  (130872, 'Iyal Surayh', 245, 1250, 15.71460000, 43.99740000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130872', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130875, 'Jabal Iyal Yazid', 245, 1250, 15.77170000, 43.90510000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130875', 'dr5hn-2026-07-29'),
  (130886, 'Khamir', 245, 1250, 15.97653000, 43.93371000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130886', 'dr5hn-2026-07-29'),
  (130889, 'Kharif', 245, 1250, 15.84700000, 44.08220000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130889', 'dr5hn-2026-07-29'),
  (130915, 'Maswar', 245, 1250, 15.59860000, 43.69250000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130915', 'dr5hn-2026-07-29'),
  (130953, 'Raydah', 245, 1250, 15.74056000, 44.05634000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130953', 'dr5hn-2026-07-29'),
  (130975, 'Shahārah', 245, 1250, 16.18000000, 43.70942000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130975', 'dr5hn-2026-07-29'),
  (130983, 'Suwayr', 245, 1250, 16.06110000, 43.62120000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130983', 'dr5hn-2026-07-29'),
  (130990, 'Thula', 245, 1250, 15.60100000, 43.82520000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130990', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (131014, '‘Ans', 245, 1246, 14.43606000, 44.38889000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131014', 'dr5hn-2026-07-29'),
  (130691, 'Al Hada', 245, 1246, 14.80760000, 44.56790000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130691', 'dr5hn-2026-07-29'),
  (130718, 'Al Manar', 245, 1246, 14.65300000, 44.11640000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130718', 'dr5hn-2026-07-29'),
  (130761, 'Al-Medy Village قرية المدي', 245, 1246, 14.40152000, 43.79178000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130761', 'dr5hn-2026-07-29'),
  (130833, 'Dawran Aness', 245, 1246, 14.82880000, 44.11430000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130833', 'dr5hn-2026-07-29'),
  (130834, 'Dhamār', 245, 1246, 14.54274000, 44.40514000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130834', 'dr5hn-2026-07-29'),
  (130873, 'Jabal Ash sharq', 245, 1246, 14.72960000, 43.90620000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130873', 'dr5hn-2026-07-29'),
  (130878, 'Jahran', 245, 1246, 14.73310000, 44.31430000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130878', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130904, 'Maghirib Ans', 245, 1246, 14.46530000, 44.12330000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130904', 'dr5hn-2026-07-29'),
  (130919, 'Mayfa''at Anss', 245, 1246, 14.51520000, 44.61060000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130919', 'dr5hn-2026-07-29'),
  (130994, 'Utmah', 245, 1246, 14.47380000, 43.94830000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130994', 'dr5hn-2026-07-29'),
  (131000, 'Wusab Al Ali', 245, 1246, 14.33440000, 43.79470000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131000', 'dr5hn-2026-07-29'),
  (131001, 'Wusab As Safil', 245, 1246, 14.25480000, 43.63250000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131001', 'dr5hn-2026-07-29'),
  (130666, 'Ad Dis', 245, 1238, 15.09490000, 50.01590000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130666', 'dr5hn-2026-07-29'),
  (130668, 'Ad Dīs ash Sharqīyah', 245, 1238, 14.90840000, 49.94847000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130668', 'dr5hn-2026-07-29'),
  (130670, 'Adh Dhlia''ah', 245, 1238, 15.01390000, 47.89720000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130670', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130678, 'Al Abr', 245, 1238, 15.91370000, 47.22880000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130678', 'dr5hn-2026-07-29'),
  (130755, 'Al Ḩamdī', 245, 1238, 15.94727000, 48.77965000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130755', 'dr5hn-2026-07-29'),
  (130737, 'Al Mukalla', 245, 1238, 14.72920000, 48.91990000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130737', 'dr5hn-2026-07-29'),
  (130744, 'Al Qaf', 245, 1238, 17.42870000, 48.94050000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130744', 'dr5hn-2026-07-29'),
  (130749, 'Al Qatn', 245, 1238, 15.92320000, 48.21460000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130749', 'dr5hn-2026-07-29'),
  (130763, 'Amd', 245, 1238, 15.34860000, 47.92860000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130763', 'dr5hn-2026-07-29'),
  (130767, 'Ar Raydah Wa Qusayar', 245, 1238, 15.18410000, 50.31330000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130767', 'dr5hn-2026-07-29'),
  (130780, 'As Sawm', 245, 1238, 15.99800000, 49.66860000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130780', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130793, 'Ash Shihr', 245, 1238, 14.97230000, 49.55260000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130793', 'dr5hn-2026-07-29'),
  (130797, 'At Taḩāluf', 245, 1238, 15.93786000, 48.78641000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130797', 'dr5hn-2026-07-29'),
  (130827, 'Brom Mayfa', 245, 1238, 14.34230000, 48.72810000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130827', 'dr5hn-2026-07-29'),
  (130832, 'Daw''an', 245, 1238, 15.05070000, 48.30720000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130832', 'dr5hn-2026-07-29'),
  (130843, 'Ghayl Ba Wazir', 245, 1238, 14.87780000, 49.02450000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130843', 'dr5hn-2026-07-29'),
  (130844, 'Ghayl Bin Yamin', 245, 1238, 15.38960000, 49.28540000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130844', 'dr5hn-2026-07-29'),
  (130849, 'Hagr As Sai''ar', 245, 1238, 16.30560000, 47.95370000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130849', 'dr5hn-2026-07-29'),
  (130851, 'Hajr', 245, 1238, 14.47080000, 48.27740000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130851', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130869, 'Huraidhah', 245, 1238, 15.55425000, 48.17505000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130869', 'dr5hn-2026-07-29'),
  (130893, 'Kilmia', 245, 1238, 12.18576000, 52.23332000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130893', 'dr5hn-2026-07-29'),
  (130929, 'Mukalla', 245, 1238, 14.54248000, 49.12424000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130929', 'dr5hn-2026-07-29'),
  (130951, 'Rakhyah', 245, 1238, 15.46180000, 47.77280000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130951', 'dr5hn-2026-07-29'),
  (130955, 'Rumah', 245, 1238, 17.81450000, 51.07590000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130955', 'dr5hn-2026-07-29'),
  (130961, 'Sah', 245, 1238, 15.53420000, 48.89550000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130961', 'dr5hn-2026-07-29'),
  (130969, 'Sayun', 245, 1238, 15.98310000, 48.83150000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130969', 'dr5hn-2026-07-29'),
  (130979, 'Shibam', 245, 1238, 15.87030000, 48.65340000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130979', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130984, 'Suḩayl Shibām', 245, 1238, 15.91448000, 48.63864000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130984', 'dr5hn-2026-07-29'),
  (130986, 'Tarim', 245, 1238, 16.06600000, 49.02290000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130986', 'dr5hn-2026-07-29'),
  (130989, 'Thamud', 245, 1238, 17.60310000, 49.73610000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130989', 'dr5hn-2026-07-29'),
  (130997, 'Wadi Al Ayn', 245, 1238, 15.74033000, 48.14747000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130997', 'dr5hn-2026-07-29'),
  (131002, 'Yabuth', 245, 1238, 14.71820000, 47.73580000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131002', 'dr5hn-2026-07-29'),
  (131007, 'Zamakh wa Manwakh', 245, 1238, 17.20320000, 47.70330000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131007', 'dr5hn-2026-07-29'),
  (130664, 'Abs', 245, 1244, 16.02150000, 43.04850000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130664', 'dr5hn-2026-07-29'),
  (130671, 'Aflah Al Yaman', 245, 1244, 15.97890000, 43.41110000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130671', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130672, 'Aflah Ash Shawm', 245, 1244, 16.05280000, 43.41200000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130672', 'dr5hn-2026-07-29'),
  (130703, 'Al Jamimah', 245, 1244, 16.02840000, 43.52970000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130703', 'dr5hn-2026-07-29'),
  (130712, 'Al Maghrabah', 245, 1244, 15.89370000, 43.60910000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130712', 'dr5hn-2026-07-29'),
  (130713, 'Al Mahabishah', 245, 1244, 15.92870000, 43.44800000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130713', 'dr5hn-2026-07-29'),
  (130730, 'Al Miftah', 245, 1244, 15.96100000, 43.51470000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130730', 'dr5hn-2026-07-29'),
  (130787, 'Ash Shaghadirah', 245, 1244, 15.60610000, 43.49920000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130787', 'dr5hn-2026-07-29'),
  (130788, 'Ash Shahil', 245, 1244, 15.85530000, 43.45160000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130788', 'dr5hn-2026-07-29'),
  (130795, 'Aslem', 245, 1244, 16.06000000, 43.29390000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130795', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130811, 'Bakil Al Mir', 245, 1244, 16.50690000, 43.36150000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130811', 'dr5hn-2026-07-29'),
  (130819, 'Banī al ‘Awwām', 245, 1244, 15.58119000, 43.58727000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130819', 'dr5hn-2026-07-29'),
  (130812, 'Bani Al Awam', 245, 1244, 15.58100000, 43.60790000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130812', 'dr5hn-2026-07-29'),
  (130816, 'Bani Qa''is', 245, 1244, 15.63460000, 43.33720000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130816', 'dr5hn-2026-07-29'),
  (130850, 'Hajjah', 245, 1244, 15.68160000, 43.44996000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130850', 'dr5hn-2026-07-29'),
  (130854, 'Harad', 245, 1244, 16.40447000, 43.07739000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130854', 'dr5hn-2026-07-29'),
  (130862, 'Hayran', 245, 1244, 16.25080000, 43.05990000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130862', 'dr5hn-2026-07-29'),
  (130890, 'Khayran Al Muharraq', 245, 1244, 16.08964000, 43.35755000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130890', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130895, 'Ku''aydinah', 245, 1244, 15.81830000, 43.35990000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130895', 'dr5hn-2026-07-29'),
  (130896, 'Kuhlan Affar', 245, 1244, 15.75540000, 43.69700000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130896', 'dr5hn-2026-07-29'),
  (130897, 'Kuhlan Ash Sharaf', 245, 1244, 16.02310000, 43.48630000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130897', 'dr5hn-2026-07-29'),
  (130898, 'Kushar', 245, 1244, 16.17090000, 43.47200000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130898', 'dr5hn-2026-07-29'),
  (130903, 'Mabyan', 245, 1244, 15.77170000, 43.55100000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130903', 'dr5hn-2026-07-29'),
  (130924, 'Midi', 245, 1244, 16.19202000, 42.88913000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130924', 'dr5hn-2026-07-29'),
  (130931, 'Mustaba', 245, 1244, 16.27360000, 43.26850000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130931', 'dr5hn-2026-07-29'),
  (130935, 'Najrah', 245, 1244, 15.65270000, 43.54520000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130935', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130939, 'Qafl Shamer', 245, 1244, 15.90870000, 43.36400000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130939', 'dr5hn-2026-07-29'),
  (130941, 'Qarah', 245, 1244, 16.40190000, 43.47400000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130941', 'dr5hn-2026-07-29'),
  (130978, 'Sharas', 245, 1244, 15.72860000, 43.65460000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130978', 'dr5hn-2026-07-29'),
  (130996, 'Wadhrah', 245, 1244, 15.71420000, 43.46670000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130996', 'dr5hn-2026-07-29'),
  (130999, 'Washḩah', 245, 1244, 16.32158000, 43.37555000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130999', 'dr5hn-2026-07-29'),
  (130759, 'Al ‘Udayn', 245, 1233, 13.96112000, 43.96608000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130759', 'dr5hn-2026-07-29'),
  (130685, 'Al Dhihar', 245, 1233, 13.97900000, 44.15260000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130685', 'dr5hn-2026-07-29'),
  (130716, 'Al Makhādir', 245, 1233, 14.13965000, 44.20330000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130716', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130723, 'Al Mashannah', 245, 1233, 13.95730000, 44.17000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130723', 'dr5hn-2026-07-29'),
  (130746, 'Al Qafr', 245, 1233, 14.31290000, 44.03000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130746', 'dr5hn-2026-07-29'),
  (130764, 'An Nādirah', 245, 1233, 14.07398000, 44.49925000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130764', 'dr5hn-2026-07-29'),
  (130765, 'Ar Radmah', 245, 1233, 14.21200000, 44.56420000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130765', 'dr5hn-2026-07-29'),
  (130772, 'As Sabrah', 245, 1233, 13.84270000, 44.33860000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130772', 'dr5hn-2026-07-29'),
  (130773, 'As Saddah', 245, 1233, 14.16610000, 44.37510000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130773', 'dr5hn-2026-07-29'),
  (130782, 'As Sayyani', 245, 1233, 13.82240000, 44.21180000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130782', 'dr5hn-2026-07-29'),
  (130786, 'Ash Sha''ir', 245, 1233, 14.03180000, 44.36190000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130786', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130810, 'Ba''dan', 245, 1233, 13.98870000, 44.32360000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130810', 'dr5hn-2026-07-29'),
  (130839, 'Dhī as Sufāl', 245, 1233, 13.82137000, 44.07775000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130839', 'dr5hn-2026-07-29'),
  (130841, 'Far Al Udayn', 245, 1233, 13.95780000, 43.78270000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130841', 'dr5hn-2026-07-29'),
  (130864, 'Hazm Al Udayn', 245, 1233, 14.16984000, 43.93814000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130864', 'dr5hn-2026-07-29'),
  (130867, 'Hubaysh', 245, 1233, 14.11600000, 44.08240000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130867', 'dr5hn-2026-07-29'),
  (130871, 'Ibb', 245, 1233, 13.96667000, 44.18333000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130871', 'dr5hn-2026-07-29'),
  (130882, 'Jiblah', 245, 1233, 13.91480000, 44.12130000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130882', 'dr5hn-2026-07-29'),
  (130927, 'Mudhaykhirah', 245, 1233, 13.86608000, 43.96866000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130927', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (131005, 'Yarīm', 245, 1233, 14.25388000, 44.31176000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131005', 'dr5hn-2026-07-29'),
  (130754, 'Al Ḩabīlayn', 245, 1245, 13.52002000, 44.85076000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130754', 'dr5hn-2026-07-29'),
  (130690, 'Al Had', 245, 1245, 13.97830000, 45.25530000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130690', 'dr5hn-2026-07-29'),
  (130675, 'Al Hawtah', 245, 1245, 13.06240000, 44.88160000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130675', 'dr5hn-2026-07-29'),
  (130710, 'Al Madaribah Wa Al Arah', 245, 1245, 12.85690000, 43.99060000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130710', 'dr5hn-2026-07-29'),
  (130711, 'Al Maflahy', 245, 1245, 13.77670000, 45.10880000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130711', 'dr5hn-2026-07-29'),
  (130721, 'Al Maqatirah', 245, 1245, 13.13720000, 44.14040000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130721', 'dr5hn-2026-07-29'),
  (130732, 'Al Milah', 245, 1245, 13.32020000, 44.92670000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130732', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130741, 'Al Musaymir', 245, 1245, 13.42910000, 44.59140000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130741', 'dr5hn-2026-07-29'),
  (130743, 'Al Qabbaytah', 245, 1245, 13.32750000, 44.50250000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130743', 'dr5hn-2026-07-29'),
  (130846, 'Habil Jabr', 245, 1245, 13.59210000, 45.07370000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130846', 'dr5hn-2026-07-29'),
  (130852, 'Halimayn', 245, 1245, 13.70880000, 44.94430000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130852', 'dr5hn-2026-07-29'),
  (130901, 'Laḩij', 245, 1245, 13.05667000, 44.88194000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130901', 'dr5hn-2026-07-29'),
  (130945, 'Radfan', 245, 1245, 13.46670000, 44.99000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130945', 'dr5hn-2026-07-29'),
  (130991, 'Tuban', 245, 1245, 13.09210000, 44.87840000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130991', 'dr5hn-2026-07-29'),
  (130992, 'Tur Al Bahah', 245, 1245, 13.04269000, 44.41154000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130992', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (131003, 'Yafa''a', 245, 1245, 13.86200000, 45.20140000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131003', 'dr5hn-2026-07-29'),
  (131004, 'Yahr', 245, 1245, 13.72270000, 45.13050000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131004', 'dr5hn-2026-07-29'),
  (130677, 'Al Abdiyah', 245, 1234, 14.71700000, 45.39340000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130677', 'dr5hn-2026-07-29'),
  (130704, 'Al Jubah', 245, 1234, 15.12490000, 45.28680000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130704', 'dr5hn-2026-07-29'),
  (130824, 'Bidbadah', 245, 1234, 15.39810000, 44.74730000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130824', 'dr5hn-2026-07-29'),
  (131012, 'Ḩarīb', 245, 1234, 14.93045000, 45.36820000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131012', 'dr5hn-2026-07-29'),
  (130856, 'Harib Al Qaramish', 245, 1234, 15.47350000, 44.61530000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130856', 'dr5hn-2026-07-29'),
  (130876, 'Jabal Murad', 245, 1234, 15.04740000, 45.18870000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130876', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130902, 'Ma''rib', 245, 1234, 15.46253000, 45.32581000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130902', 'dr5hn-2026-07-29'),
  (130905, 'Mahliyah', 245, 1234, 14.68210000, 45.18320000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130905', 'dr5hn-2026-07-29'),
  (130907, 'Majzar', 245, 1234, 15.82770000, 44.79410000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130907', 'dr5hn-2026-07-29'),
  (130912, 'Marib', 245, 1234, 15.62130000, 46.01110000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130912', 'dr5hn-2026-07-29'),
  (130921, 'Medghal', 245, 1234, 15.63840000, 45.00380000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130921', 'dr5hn-2026-07-29'),
  (130948, 'Raghwan', 245, 1234, 15.79020000, 45.06940000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130948', 'dr5hn-2026-07-29'),
  (130949, 'Rahabah', 245, 1234, 14.95100000, 45.08850000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130949', 'dr5hn-2026-07-29'),
  (130982, 'Sirwah', 245, 1234, 15.43690000, 45.01150000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130982', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130701, 'Al Jabin', 245, 1248, 14.68990000, 43.61960000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130701', 'dr5hn-2026-07-29'),
  (130702, 'Al Jafariyah', 245, 1248, 14.51960000, 43.58170000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130702', 'dr5hn-2026-07-29'),
  (130776, 'As Salafiyah', 245, 1248, 14.68660000, 43.82160000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130776', 'dr5hn-2026-07-29'),
  (130826, 'Bilad At Ta''am', 245, 1248, 14.83820000, 43.60780000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130826', 'dr5hn-2026-07-29'),
  (130899, 'Kusmah', 245, 1248, 14.54740000, 43.68330000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130899', 'dr5hn-2026-07-29'),
  (130920, 'Mazhar', 245, 1248, 14.57090000, 43.76070000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130920', 'dr5hn-2026-07-29'),
  (130684, 'Al Dhaher', 245, 1249, 16.73140000, 43.27530000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130684', 'dr5hn-2026-07-29'),
  (130694, 'Al Hashwah', 245, 1249, 16.88840000, 44.27380000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130694', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130774, 'As Safra', 245, 1249, 17.01420000, 43.85660000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130774', 'dr5hn-2026-07-29'),
  (130792, 'Ash Shawātī', 245, 1249, 16.78314000, 43.81265000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130792', 'dr5hn-2026-07-29'),
  (130820, 'Baqim', 245, 1249, 17.37810000, 43.46350000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130820', 'dr5hn-2026-07-29'),
  (130842, 'Ghamr', 245, 1249, 16.98301000, 43.31608000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130842', 'dr5hn-2026-07-29'),
  (130860, 'Haydan', 245, 1249, 16.72870000, 43.48490000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130860', 'dr5hn-2026-07-29'),
  (130894, 'Kitaf wa Al Boqe''e', 245, 1249, 17.08080000, 44.39620000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130894', 'dr5hn-2026-07-29'),
  (130906, 'Majz', 245, 1249, 17.09230000, 43.51040000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130906', 'dr5hn-2026-07-29'),
  (130926, 'Monabbih', 245, 1249, 17.16930000, 43.27910000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130926', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130942, 'Qatabir', 245, 1249, 17.33680000, 43.33110000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130942', 'dr5hn-2026-07-29'),
  (130956, 'Rāziḩ', 245, 1249, 16.93704000, 43.26080000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130956', 'dr5hn-2026-07-29'),
  (130957, 'Sa''dah', 245, 1249, 16.94021000, 43.76393000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130957', 'dr5hn-2026-07-29'),
  (131010, 'Şa‘dah', 245, 1249, 16.91733000, 43.76000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:131010', 'dr5hn-2026-07-29'),
  (130972, 'Saḩār', 245, 1249, 16.88522000, 43.68306000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130972', 'dr5hn-2026-07-29'),
  (130966, 'Saqayn', 245, 1249, 16.86010000, 43.47160000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130966', 'dr5hn-2026-07-29'),
  (130973, 'Shada''a', 245, 1249, 16.89130000, 43.18710000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130973', 'dr5hn-2026-07-29'),
  (130696, 'Al Haymah Ad Dakhiliyah', 245, 1236, 15.27220000, 43.83930000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130696', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130697, 'Al Haymah Al Kharijiyah', 245, 1236, 15.02670000, 43.85000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130697', 'dr5hn-2026-07-29'),
  (130700, 'Al Husn', 245, 1236, 15.02060000, 44.50440000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130700', 'dr5hn-2026-07-29'),
  (130707, 'Al Khāniq', 245, 1236, 15.50253000, 44.18158000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130707', 'dr5hn-2026-07-29'),
  (130770, 'Arhab', 245, 1236, 15.79950000, 44.24660000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130770', 'dr5hn-2026-07-29'),
  (130802, 'Attyal', 245, 1236, 15.32931000, 44.57739000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130802', 'dr5hn-2026-07-29'),
  (130813, 'Bani Dhabyan', 245, 1236, 15.04810000, 44.87180000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130813', 'dr5hn-2026-07-29'),
  (130814, 'Bani Hushaysh', 245, 1236, 15.45050000, 44.37820000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130814', 'dr5hn-2026-07-29'),
  (130815, 'Bani Matar', 245, 1236, 15.21500000, 44.04980000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130815', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130825, 'Bilad Ar Rus', 245, 1236, 15.03510000, 44.25140000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130825', 'dr5hn-2026-07-29'),
  (130853, 'Hamdān', 245, 1236, 15.50662000, 44.06030000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130853', 'dr5hn-2026-07-29'),
  (130883, 'Jihanah', 245, 1236, 15.19190000, 44.51950000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130883', 'dr5hn-2026-07-29'),
  (130892, 'Khwlan', 245, 1236, 15.27490000, 44.76860000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130892', 'dr5hn-2026-07-29'),
  (130909, 'Manakhah', 245, 1236, 15.07170000, 43.68620000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130909', 'dr5hn-2026-07-29'),
  (130937, 'Nihm', 245, 1236, 15.75160000, 44.57460000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130937', 'dr5hn-2026-07-29'),
  (130958, 'Sa''fan', 245, 1236, 15.07120000, 43.58270000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130958', 'dr5hn-2026-07-29'),
  (130971, 'Saḩar', 245, 1236, 15.31637000, 44.30880000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130971', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130965, 'Sanhan', 245, 1236, 15.22520000, 44.30570000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130965', 'dr5hn-2026-07-29'),
  (130970, 'Sayyān', 245, 1236, 15.17177000, 44.32442000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130970', 'dr5hn-2026-07-29'),
  (130674, 'Ain', 245, 1247, 14.95030000, 45.60040000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130674', 'dr5hn-2026-07-29'),
  (130760, 'Al ‘Āqir', 245, 1247, 14.56816000, 45.91156000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130760', 'dr5hn-2026-07-29'),
  (130751, 'Al Talh', 245, 1247, 15.08260000, 47.35140000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130751', 'dr5hn-2026-07-29'),
  (130663, 'AL-khashā upper', 245, 1247, 14.34044000, 46.71365000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130663', 'dr5hn-2026-07-29'),
  (130766, 'Ar Rawdah', 245, 1247, 14.49560000, 47.27460000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130766', 'dr5hn-2026-07-29'),
  (130771, 'Arma', 245, 1247, 15.41270000, 47.23450000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130771', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130775, 'As Said', 245, 1247, 14.27660000, 46.86930000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130775', 'dr5hn-2026-07-29'),
  (130800, 'Ataq', 245, 1247, 14.53767000, 46.83187000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130800', 'dr5hn-2026-07-29'),
  (130822, 'Bayhan', 245, 1247, 14.76190000, 45.74820000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130822', 'dr5hn-2026-07-29'),
  (130835, 'Dhar', 245, 1247, 15.50360000, 47.60580000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130835', 'dr5hn-2026-07-29'),
  (130845, 'Habban', 245, 1247, 14.28780000, 47.13610000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130845', 'dr5hn-2026-07-29'),
  (130858, 'Hatib', 245, 1247, 14.18020000, 46.44390000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130858', 'dr5hn-2026-07-29'),
  (130879, 'Jardan', 245, 1247, 15.19000000, 46.73380000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130879', 'dr5hn-2026-07-29'),
  (130891, 'Khimār', 245, 1247, 14.31980000, 46.73922000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130891', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130918, 'Mayfa''a', 245, 1247, 14.39780000, 47.74040000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130918', 'dr5hn-2026-07-29'),
  (130922, 'Merkhah Al Ulya', 245, 1247, 14.48470000, 45.92990000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130922', 'dr5hn-2026-07-29'),
  (130923, 'Merkhah As Sufla', 245, 1247, 14.69990000, 46.15630000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130923', 'dr5hn-2026-07-29'),
  (130938, 'Nisab', 245, 1247, 14.52570000, 46.44770000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130938', 'dr5hn-2026-07-29'),
  (130954, 'Rudum', 245, 1247, 14.03759000, 47.83824000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130954', 'dr5hn-2026-07-29'),
  (130993, 'Usaylan', 245, 1247, 15.17030000, 46.02740000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130993', 'dr5hn-2026-07-29'),
  (130848, 'Hadibu', 245, 1239, 12.64881000, 54.01895000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130848', 'dr5hn-2026-07-29'),
  (130865, 'Hidaybu', 245, 1239, 12.50250000, 54.00820000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130865', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130940, 'Qalansīyah', 245, 1239, 12.68958000, 53.48709000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130940', 'dr5hn-2026-07-29'),
  (130944, 'Qulensya Wa Abd Al Kuri', 245, 1239, 12.55479000, 53.58671000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130944', 'dr5hn-2026-07-29'),
  (130708, 'Al Ma''afer', 245, 1231, 13.37420000, 43.92620000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130708', 'dr5hn-2026-07-29'),
  (130728, 'Al Mawasit', 245, 1231, 13.30420000, 44.10050000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130728', 'dr5hn-2026-07-29'),
  (130734, 'Al Misrakh', 245, 1231, 13.47020000, 44.03770000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130734', 'dr5hn-2026-07-29'),
  (130736, 'Al Mudhaffar', 245, 1231, 13.58310000, 43.99270000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130736', 'dr5hn-2026-07-29'),
  (130739, 'Al Mukhā’', 245, 1231, 13.51998000, 43.42798000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130739', 'dr5hn-2026-07-29'),
  (130747, 'Al Qahirah', 245, 1231, 13.58490000, 44.01010000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130747', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130753, 'Al Wazi''iyah', 245, 1231, 13.18460000, 43.72980000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130753', 'dr5hn-2026-07-29'),
  (130783, 'As Silw', 245, 1231, 13.34590000, 44.20720000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130783', 'dr5hn-2026-07-29'),
  (130790, 'Ash Shamayatayn', 245, 1231, 13.18220000, 43.98000000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130790', 'dr5hn-2026-07-29'),
  (130798, 'At Ta‘izzīyah', 245, 1231, 13.69479000, 44.00941000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130798', 'dr5hn-2026-07-29'),
  (130838, 'Dhubab', 245, 1231, 12.96590000, 43.47240000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130838', 'dr5hn-2026-07-29'),
  (130840, 'Dimnat Khadir', 245, 1231, 13.43860000, 44.25420000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130840', 'dr5hn-2026-07-29'),
  (130861, 'Hayfan', 245, 1231, 13.29060000, 44.26070000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130861', 'dr5hn-2026-07-29'),
  (130874, 'Jabal Habashy', 245, 1231, 13.46650000, 43.88100000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130874', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130911, 'Maqbanah', 245, 1231, 13.62120000, 43.66740000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130911', 'dr5hn-2026-07-29'),
  (130914, 'Mashra''a Wa Hadnan', 245, 1231, 13.54170000, 43.99830000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130914', 'dr5hn-2026-07-29'),
  (130932, 'Māwīyah', 245, 1231, 13.58461000, 44.31912000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130932', 'dr5hn-2026-07-29'),
  (130917, 'Mawza', 245, 1231, 13.37820000, 43.61450000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130917', 'dr5hn-2026-07-29'),
  (130960, 'Sabir Al Mawadim', 245, 1231, 13.53180000, 44.04620000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130960', 'dr5hn-2026-07-29'),
  (130962, 'Salh', 245, 1231, 13.58390000, 44.04020000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130962', 'dr5hn-2026-07-29'),
  (130963, 'Sama', 245, 1231, 13.38090000, 44.11660000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130963', 'dr5hn-2026-07-29'),
  (130976, 'Shara''b Ar Rawnah', 245, 1231, 13.73360000, 43.76720000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130976', 'dr5hn-2026-07-29');
INSERT INTO cities (id, name, country_id, state_id, latitude, longitude, timezone, population, feature_code, place_type, source_id, source_version) VALUES
  (130977, 'Shara''b As Salam', 245, 1231, 13.78320000, 43.88610000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130977', 'dr5hn-2026-07-29'),
  (130988, 'Ta‘izz', 245, 1231, 13.57952000, 44.02091000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130988', 'dr5hn-2026-07-29'),
  (130995, 'Village of Alamrah', 245, 1231, 13.74318000, 43.72992000, 'Asia/Aden', NULL, NULL, 'city', 'dr5hn:130995', 'dr5hn-2026-07-29');
